### ISSUE TITLE
Improve readability of output stats

### ISSUE THREAD

**Issue by egoist** [egoist/poi#125]
<img width="548" alt="2017-02-19 7 08 17" src="https://cloud.githubusercontent.com/assets/8784712/23101786/ce13fe6e-f6d6-11e6-938f-0325c3a67982.png">

The current output might look like this, looks cool but unreadable. It's hard to find the `client.js` from all other files and sourcemaps

**Comment by egoist** [comment]
Maybe resort this list of files and use some gray color for sourcemap files

**Comment by mblarsen** [comment]
Or use something like https://github.com/FormidableLabs/webpack-dashboard

**Comment by throrin19** [comment]
I think you should use current output with no options and set others outputs with specific poi command argument : 

- log : Output without color or special chars. In example, in AWS codebuild, the output is like that :
    ```
    cc [1mAsset[39m[22m [1mSize[39m[22m [1mChunks[39m[22m [1m[39m[22m [1m[39m[22m [1mChunk Names[39m[22m
    [1m[32mmanifest.90ad1d7c.js.map[39m[22m 14.4 kB [1m4[39m[22m [1m[32m[emitted][39m[22m manifest
    [1m[32mdashboard.a7284196.chunk.js[39m[22m 9.22 kB [1m0[39m[22m [1m[32m[emitted][39m[22m dashboard
    [1m[33mvendor.cf1ecef6.js[39m[22m [1m[33m521 kB[39m[22m [1m2[39m[22m [1m[32m[emitted][39m[22m [1m[33m[big][39m[22m vendor
    [1m[32mclient.c817fb9a.js[39m[22m 29.4 kB [1m3[39m[22m [1m[32m[emitted][39m[22m client
    [1m[32mmanifest.90ad1d7c.js[39m[22m 1.53 kB [1m4[39m[22m [1m[32m[emitted][39m[22m manifest
    [1m[32mclient.72599567.css[39m[22m 6.91 kB [1m3[39m[22m [1m[32m[emitted][39m[22m client
    ```
- sourcemap : gray sourcemap color
- default : current output format

I think it's really cool to do that and, if you want use custom output like webpack-dashboard, create a specific poi-preset to use that.
