### ISSUE TITLE
Component generator

### ISSUE THREAD

**Issue by egoist** [egoist/poi#127]
```bash
vbuild init:component UserCard
```

Love it? Hate it?

**Comment by Anonyfox** [comment]
idea: namespacing (optional)

`vbuild init:component folderName:UserCard` -> `/components/folderName/UserCard.vue`

**Comment by Rayraegah** [comment]
I think we can do better. How about

    $ vBuild init

as a starting command and then display a list of things to init

    (x) App
    ( ) Component
    ( ) Namespaced Component

You can install more configurations like `vuejs component` or `svelte component` etc.

**Comment by egoist** [comment]
not going to happen (at least here) ☹️
