### ISSUE TITLE
Any plans for using Rollup as an option instead of Webpack?

### ISSUE THREAD

**Issue by chrishrtmn** [egoist/poi#161]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently only Webpack is used to create a Vue app config, but I would prefer to use Rollup and thought it'd be great to have that as an option.

**Comment by egoist** [comment]
Rollup is better for bundling libraries, see https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by egoist** [comment]
So in conclusion, Rollup isn't for bundling web apps, thanks for the suggestion anyways.
