### ISSUE TITLE
[Bug] extendWebpack isn't called early enough for poi build

### ISSUE THREAD

**Issue by Async0x42** [egoist/poi#166]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
extendWebpack(config) isn't called in time for poi build

**If the current behavior is a bug, please provide the steps to reproduce.**
Add to your poi.config.js
```
  extendWebpack(config) {
    config.module.rule('markdown')
      .test(/\.md$/)
      .use('md')
        .loader(require.resolve('vue-markdown-loader'));
  }
```

**What is the expected behavior?**
poi build should call extendWebpack before webpack needs it so things can be modified by webpackChain

(This worked in rc.7)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
fixed in rc.9
