### ISSUE TITLE
Force our own vue-loader version

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#167]
Hi,
It's possible to use our own vue-loader version ? 
In the 12.0.0 it introduce a "small breaking change"  that is not so small. If I compile my project with this version, this breaking change break all my components css and directive components css.

If I compile with the previous version `11.0.0` I have no problem. But poi force the usage of the latest vue-loader version. It's possible to change that ? (or disable the lazy-inject of components style)

Thanks

**Comment by egoist** [comment]
As per doc, you have full access to default webpack config:

```js
module.exports = {
  extendWebpack(config) {
    config.module.rule('vue')
      .use('vue')
      .loader(require.resolve('vue-loader'))
  }
}
```

Maybe we should set default loader to `vue-loader` instead of `require.resolve('vue-loader')`

**Comment by throrin19** [comment]
Thanks it works fine :)
