### ISSUE TITLE
Discussion about using POI programatically

### ISSUE THREAD

**Issue by miljan-aleksic** [egoist/poi#169]
Hi, I am trying to use POI under the hood for Vuikit Explorer, a project inspired by vue-play.

Vuikit Explorer aims to require no configuration at all from the host project while setting up custom HTML and other configurations for POI under the hood. It simplifies the init to just:

```js
const explorer = require('vuikit-explorer')

explorer.add(...).run()
```

Vuikit Explorer would run POI with a custom HTML tmpl and other configurations that will work out of the box. The disadvantage is that this way webpack is not available and adding .vue components would not be supported, among others.

So far it's just an experiment and I thought to open this ticket to get/provide ideas on how this could be solved or if should be solved at all.

**Comment by egoist** [comment]
1. If you only need to modify webpack config, you can build a [preset](https://poi.js.org/#/presets) for it.

2. It's actually possible to build a tool upon Poi's API, you can already use the API via `const poi = require('poi')`, see [lib/index.js](https://github.com/egoist/poi/blob/master/packages/poi/lib/index.js), maybe I should add it to the docs later. (note: the API does not load babel/postcss config files.)

**Comment by miljan-aleksic** [comment]
Presets could be the answer. If it's possible to set all POI options there, in the host module could be loaded and work out of a box without losing the customization possibility.

Thanks for the support!
