### ISSUE TITLE
Use poi to build a Chrome Extension

### ISSUE THREAD

**Issue by stursby** [egoist/poi#170]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

I would love to build a Chrome Extension using Vue. I've got `poi` setup in my project and everything in the `/src` folder, but I'm trying to figure out a nice dev process (with Live Reload, etc) inside a Chrome Extension.

**If the current behavior is a bug, please provide the steps to reproduce.**

No, not a bug.

A Google Chrome Extension requires a `manifest.json`, and HTML file. ([DOCS](https://developer.chrome.com/extensions/getstarted)). Just wondering if I could use poi for this!

**What is the expected behavior?**

Poi is working fine, but Chrome complains when trying to load the extension from the `/dist` folder.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Feature request... and honestly, this is probaly just a config issue that I can't wrap my head around. Any help would be much appreciated! 👍 

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Chrome 58.*, poi 8.0.0-rc.13

**Comment by egoist** [comment]
You might use such structure:

.project-folder
- src/ - App source
- extension/ - The folder that Chrome loads
  - manifest.json
- poi.config.js

Basically you compile `src/index.js` to `extension/dist` folder, you may also turn off `vendor` option in config file. [like this](https://github.com/egoist/github-improved/blob/master/vbuild.config.js).

**Comment by stursby** [comment]
@egoist great! I've got most of it working now, thanks!

So for my Extension, I'm using a popup window. How would I go about using the nice dev live reload, etc with that `index.html` file needs to be in the `/extension` folder too.

**Comment by egoist** [comment]
Maybe you should tweak the publicPath in dev mode:

```js
module.exports = options => ({
  extendWebpack(config) {
     if (options.mode === 'development') {
      // Default value is '/'
      config.output.publicPath('http://localhost:4000/')
    }
  }
})
```

**Comment by stursby** [comment]
@egoist Hmmm, tried that, still getting the same error. Not sure if I explained it correctly... so the Extension is looking for an HTML file in the `/extension` folder, but that doesn't exist until I run `yarn dev`?

**Comment by egoist** [comment]
@stursby I guess you need to populate two html files manually, one for dev, the other one for prod, here's a similar project with such structure: https://github.com/jhen0409/react-chrome-extension-boilerplate

**Comment by stursby** [comment]
@egoist Ok, I'll take a look! Thanks for the help 👍
