### ISSUE TITLE
Discussion: workboxjs as a feature for PWA or preset in poi?

### ISSUE THREAD

**Issue by Rayraegah** [egoist/poi#174]
[PWA](https://poi.js.org/#/recipes/progressive-web-app) with [workboxjs](https://workboxjs.org/#get-started) or workboxjs as a preset in poi?

**Comment by egoist** [comment]
It looks similar to @NekR 's [offline-plugin(https://github.com/NekR/offline-plugin), and we have a [preset](https://github.com/egoist/poi/issues/174) for that.

> Poi could offer a simple switch to turn on/off workboxjs plugin in its webpack build.

Does a preset sound good enough for your use case?

**Comment by Rayraegah** [comment]
I think a preset is more than enough. I'll be happy to make it myself and give you a RP.

**Comment by egoist** [comment]
@Rayraegah Hi do you have a working workbox preset now? It seems the doc is lacking

**Comment by Rayraegah** [comment]
Made one, but we ended up scrapping it and defaulted to the PWA option in poi. Haven't gotten around to it yet.
