### ISSUE TITLE
Docs seems out of sync

### ISSUE THREAD

**Issue by zigomir** [egoist/poi#177]
**Do you want to request a *feature* or report a *bug*?**

bug/wrong docs

**What is the current behavior?**

[tl;dr](https://poi.js.org/#/home?id=tldr) is not in sync with [Modes](https://poi.js.org/#/home?id=modes).

**What is the expected behavior?**

`Modes` should say that `dev` is default mode and that there is also `poi build` mode.

I first clicked on a Pencil button to do a PR that fixes this but then found out that this repo's README.md file is not same.

**Comment by egoist** [comment]
fixed at https://github.com/egoist/poi.js.org, thanks for catching this 👍
