### ISSUE TITLE
Extending webpack config in poi.config.src (sass-loader -> includePath) for external packages

### ISSUE THREAD

**Issue by JesusCrow** [egoist/poi#178]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When importing CSS package or library from NPM, using something like this:
``` vue
<style src="@/../node_modules/package-name/style.css"></style>
```
When importing a component with SCSS:
``` vue
<style lang="scss">
  @import '~@material/drawer/mdc-drawer';
</style>
```
But if component is written in different config for imports, it fails.

> > The sass-loader uses node-sass' custom importer feature to pass all queries to the Webpack resolving engine. Thus you can import your Sass modules from `node_modules`. Just prepend them with a `~` to tell Webpack that this is not a relative import. [...] Webpack needs to distinguish between bootstrap and `~bootstrap` because CSS and Sass files have no special syntax for importing relative files. Writing `@import "file"` is the same as `@import "./file"`.

> Since material-components-web isn't using the standard sass-loader resolution mechanism I need to add a similar `includePaths` hack to my own Webpack config in order to avoid resolution errors for transitive dependencies when I `@import` its Sass files from my components' Sass files:
`includePaths: [path.join(__dirname, 'node_modules')]`

_Why did this happen?_
> [...] unfortunately, `~` is only Webpack-specific, and we want our Sass to be able to be used by our standalone packages. Thus, we need to keep our import paths the way they currently are [...]

_Why should someone care?_
Because there are more libraries that use different standards. And other options to make them work is a pain in the ass (finding a buggy fork / downloading lib and changing imports / etc)

**If the current behavior is a bug, please provide the steps to reproduce.**
``` bash
create-vue-app
yarn add node-sass sass-loader --dev
```
Import something:
``` vue
<style lang="scss">
  @import '~@material/drawer/mdc-drawer';
</style>
```
``` bash
poi
```
Error log:
``` bash
ERROR in ./~/css-loader?{"autoprefixer":false,"sourceMap":true,"minimize":false}!./~/vue-loader/lib/style-
compiler?{"vue":true,"id":"data-v-3ec93e2f","scoped":false,"hasInlineConfig":true}!./~/sass-loader/lib/loa
der.js?{"sourceMap":true}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Drawer.vue
Module build failed: 
undefined
^
      File to import not found or unreadable: @material/rtl/mixins.
Parent style sheet: C:/varna/playgorund/drawer/node_modules/@material/drawer/persistent/mdc-persistent-dra
wer.scss
      in C:\varna\playgorund\drawer\node_modules\@material\drawer\persistent\mdc-persistent-drawer.scss (l
ine 17, column 1)
 @ ./~/vue-style-loader?{"sourceMap":true}!./~/css-loader?{"autoprefixer":false,"sourceMap":true,"minimize
":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3ec93e2f","scoped":false,"hasInlineCon
fig":true}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/vue-loader/lib/selector.js?type=styles&ind
ex=0!./src/components/Drawer.vue 4:14-415 13:3-17:5 14:22-423
 @ ./src/components/Drawer.vue
 @ ./index.js
 @ multi ./~/poi/app/dev-client.es6 ./index.js
```

_Why error happend?_
Package that I tried to import, had SCSS that tried to import other SCSS inside of it. It had different Webpack config, so it failed.

**What is the expected behavior?**
Import lib with code-splitting.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Improving docs on import would help idiots like me (I tried webpack, sass-loader, poi, webpack-merge and few other repository documentations and issue tracker logs to find information, but I failed to do what I intended).

While looking at [poi Docs](poi.js.org) I tried to write Webpack config import and failed miserably:
``` js
module.exports = {
  module: {
    rules: [
      {
        test: /\.(sass|scss)$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
        options: { 
          includePaths: [path.resolve(__dirname, './node_modules')]
        }
      }
    ]
  }
}
``` 
``` js
module.exports = {
  extendWebpack(config) {
    config.merge({
      scssLoader: {
        includePaths: [path.join(__dirname, 'node_modules')]
      }
    })
  }
}
```
Then I figured out that I only need to add `module.rules.options.includePaths`, but I still failed
``` js
module.exports = {
  mergeConfig: {
    // following options will be merged
    module: {
      rules: [
        {
          test: /\.(sass|scss)$/,
          use: [
            'style-loader',
            'css-loader',
            { loader: 'sass-loader',
              options: {
                sourceMap: true,

                // mdc-web doesn't use sass-loader's normal syntax for imports
                // across modules, so we add all module directories containing
                // mdc-web components to the Sass include path
                // https://github.com/material-components/material-components-web/issues/351
                includePaths: glob.sync(
                  path.join(__dirname, '**/node_modules/@material')
                ).map((dir) => path.dirname(dir)),
              },
            },
          ],
        }
      ]
    }
  }
}
```
And then I tried to do it like [preset examples](https://github.com/egoist/poi/tree/master/packages)
``` js
module.exports = () => {
  return poi => {
    const config = poi.webpackConfig

    config.module.rule('scss')
      .use('sass-loader')
      .tap(options => {
        return poi.merge(options, {
          includePaths: glob.sync(
            path.join(__dirname, '**/node_modules/@material')
          ).map((dir) => path.dirname(dir))
        })
      })
  } 
}
```

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

- Node: 7.9
- poi: 8.1.1
- npm: 4.2.0
- yarn: 0.24.4
- OS: Windows 10
- Shell: Hyper -> Git Bash

**Comment by egoist** [comment]
The last one should work, but you should update scss options for vue-loader instead:

```js
config.module.rule('vue')
  .use('vue-loader')
  .tap(options => {
    const scss = options.loaders.scss.pop()
    scss.options.includePaths = [path.resolve('node_modules')]
    options.loaders.scss.push(scss)
    return options
  })
```

Update `poi` to `8.1.2` first, `.use('vue')` is changed to `.use('vue-loader')`

***

Maybe this should be the default behavior for sass-loader

**Comment by JesusCrow** [comment]
Updated poi and pushed [test repo](https://github.com/JesusCrow/mdc-poi-drawer-test) online.

`import '@material/drawer/mdc-drawer.scss'` works inside `script tag`

But it still dies during compilation of imported package, when inside of it one `.scss` file imports other `.scss` file. 
1. `Drawer.vue` -> `import '@material/drawer/mdc-drawer.scss'`
2. `@material/drawer/.../file.scss` -> `@import "@material/rtl/mixins"` (which is `_mixins.scss`)
3. it chokes during no.2
Same error:
``` shell
ERROR in ./~/css-loader?{"autoprefixer":false,"sourceMap":true,"minimize":false}!./~/postcss-loader?{"sourceMap":true,"plu
gins":[null]}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/@material/drawer/mdc-drawer.scss
Module build failed: 
undefined
^
      File to import not found or unreadable: @material/rtl/mixins.
Parent style sheet: C:/varna/playgorund/drawer/node_modules/@material/drawer/persistent/mdc-persistent-drawer.scss
      in C:\varna\playgorund\drawer\node_modules\@material\drawer\persistent\mdc-persistent-drawer.scss (line 17, column 1
)
 @ ./~/@material/drawer/mdc-drawer.scss 4:14-162 13:3-17:5 14:22-170
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Drawer.vue
 @ ./src/components/Drawer.vue
 @ ./index.js
 @ multi ./~/poi/app/dev-client.es6 ./index.js

 FAIL  Compiled with Errors!
```

Shouldn't it be `sass-loader` problem and not `vue-loader` in this case?

**Comment by egoist** [comment]
You should change webpack config like this:

```js
// poi.config.js
module.exports = {
  extendWebpack(config) {
    config.rule //...
  }
}
```

**Comment by JesusCrow** [comment]
Awesome! It works.
Sorry for wasting Your time.
Also adding these two snippets, someone might need this ✌️ 
``` js 
// poi.config.js
module.exports = {
  extendWebpack(config) {
    config.module.rule('vue')
      .use('vue-loader')
      .tap(options => {
        const scss = options.loaders.scss.pop()
        scss.options.includePaths = [path.resolve(__dirname, './node_modules')]
        options.loaders.scss.push(scss)
        return options
      })
  }
}
```
``` js
// poi.config.js
module.exports = {
  extendWebpack(config) {
    config.module.rule('scss')
      .use('sass-loader')
      .tap(options => {
        options.includePaths = [path.resolve(__dirname, './node_modules')]
        return options
      })
  }
}
```
