### ISSUE TITLE
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING :4000/__webpack_hmr 

### ISSUE THREAD

**Issue by Rayraegah** [egoist/poi#179]
**Do you want to request a *feature* or report a *bug*?**
Bug in poi dependency: webpack-hot-middleware

**What is the current behavior?**
HMR chunk reload failures. Ends up with multiple patches; none of which are applied.
```
http://localhost:4000/0.322aa0d9f0c91b63d9bc.hot-update.js
http://localhost:4000/0.5e13ae915be20f1241e1.hot-update.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's what I did. 
 * I uninstalled my nodejs (v7) software and did a fresh install (v8) using brew this morning after npm v5 messed up all my global packages
 * Seeing that error since re-installation.
 * My poi dependencies are local so reinstallation should not have affected it.
 * I cleaned all cache and local node_modules. Error still persists.

**What is the expected behavior?**
hmr patches should be applied.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
 * Chrome 58.0.3029.110 (64-bit)
 * Node v8.0.0
 * yarn v0.24.6
 * poi v8.1.1
 * OSX 10.12.5

**Comment by egoist** [comment]
Hmm, weird, it works in node 7 but fails in node 8

**Comment by egoist** [comment]
Just tried [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack), also got a `net::ERR_INCOMPLETE_CHUNKED_ENCODING` error, maybe a webpack-hot-middleware bug then

**Comment by Rayraegah** [comment]
Update: It takes about 30 ~ 40 seconds, but hmr kicks in and works again. Then it randomly breaks :) I have no lol. I haven't seen any open tickets on webpack-hot-middleware. Might make one.

**Comment by egoist** [comment]
It should work properly in `v8.1.3` now,
