### ISSUE TITLE
Expose the Webpack config object to use with ESLint

### ISSUE THREAD

**Issue by skyrpex** [egoist/poi#182]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
There's no way to retrieve the Webpack configuration object to be used in ESLint's Webpack import resolver plugin.

**If the current behavior is a bug, please provide the steps to reproduce.**
-

**What is the expected behavior?**
To be able to easily configure ESLint's Webpack import resolver plugin.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Let's say one use Poi as the building tool. You also want to use ESLint with a configuration like this (or even simpler, using a ESLint plugin):
```json
{
  "root": true,
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module"
  },
  "extends": "airbnb-base",
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "poi/packages/poi-eslint"
      }
    }
  }
}
```

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
You can set webpack config in eslint config manully or use such setup: https://gist.github.com/egoist/b2af5853454166c2ff5d33dbbe6ec3ea

But when you use the Poi api, it will not load babel/postcss config files like `.babelrc`. 

And we didn't run `poi.process()` here to apply `presets`options from Poi config,  since `presets` are loaded asynchronously.

**Comment by skyrpex** [comment]
That's awesome, I didn't know there was such API. Thanks for the quick response.

I think that the import plugin doesn't care about Webpack loaders, so it's fine not loading presets (I guess 👍).

**Comment by sergeystoma** [comment]
Sounds this approach is no longer working as app.webpackConfig is generated in prepare() which runs asynchronously... Is there an alternate workout?

**Comment by sergeystoma** [comment]
Answering my question... this hack works:

```
const createConfig = require('poi/lib/create-config');
const config = require('./poi.config');

const webpackConfig = createConfig(config).toConfig();

...

settings: {
    'import/resolver': {
        webpack: {
            config: webpackConfig
        },
    },
},
```

**Comment by egoist** [comment]
@sergeystoma https://github.com/poi-examples/eslint-example
