### ISSUE TITLE
add .jsx extension to webpack resolve.extensions

### ISSUE THREAD

**Issue by magicdawn** [egoist/poi#186]
**Do you want to request a *feature* or report a *bug*?**
add .jsx to resolve.extensions

**What is the current behavior?**
https://github.com/egoist/poi/blob/v7.3.0/packages/poi/lib/create-config.js#L93-L95

current `.jsx` is not in the extension list, and jsx can not be resolved

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
add `.jsx` to resolve.extensions in core package or poi-preset-react

**Comment by egoist** [comment]
Just added it in core package, while you can always require `.jsx` file explicitly like `import ap pfrom './app.jsx'`, but I think it's not necessary to use `.jsx` extension 👌

**Comment by egoist** [comment]
Released in [`v9.0.0`](https://github.com/egoist/poi/releases/tag/v9.0.0), don't forget to update presets to latest version as well.
