### ISSUE TITLE
Sourcemap not working with Chrome debug in vscode

### ISSUE THREAD

**Issue by layanto** [egoist/poi#187]
Don't think this is a bug but not sure how to ask question other than raising github issue.

With Visual Studio Code, I have configured the workspaceroot to point to c:/projects/myproject. Under myproject/, I have client/ (root of frontend poi project) and server/ (root of backend node project).

This is what I currently have in my c:/projects/myproject/.vscode/launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:4000",
            "webRoot": "${workspaceRoot}/client/src",
            "skipFiles": [
                "**/node_modules/**/*"
            ]
        }
    ]
}
```
It appears that vscode can't find the sourcemap and because of this when I add breakpoints, usually ended up breaking at the wrong part.

**Comment by layanto** [comment]
I think the issue is sourcemap generated by poi/webpack has incorrect source.

For example, this is shown in chrome dev tool
```
c:\projects\myproject\client\Catalogue.vue?6f7799a7
```
But the correct path is
```
c:\projects\myproject\client\src\components\Catalogue.vue
```
Another example, this is shown in chrome dev tool:
```
c:\projects\myproject\client\MainView.vue?f4c46120
```
But the correct path to the source file is:
```
c:\projects\myproject\client\src\views\MainView.vue
```

Maybe something wrong with my poi config?

**Comment by layanto** [comment]
poi version 9.0.0
node version 6.11.0
os Windows 10
browser chrome 59

**Comment by egoist** [comment]
The path is relative to root because of https://github.com/webpack/webpack/issues/3603

I have no clue what's going on with vscode, does it work for a normal webpack project? If so it should work for a Poi project as well.

**Comment by layanto** [comment]
If the path is relative to root, what is the root? C:/projects/myproject/client or C:/projects/myproject/client/src?

Also why are Catalogue.vue and MainView.vue both shown as if they are located in the same directory c:/projects/myproject/client when one is located in client/src/components and the other client/src/views?
Works fine in Chrome directly possibly because chrome uses the inline sourcemap and not looking for the actual source files unlike vscode.

**Comment by layanto** [comment]
Looks like this issue is already raised in vscode github https://github.com/Microsoft/vscode-chrome-debug/issues/430

**Comment by layanto** [comment]
Closing here as already raised in vscode github
