### ISSUE TITLE
Question: If I had to add support for Riotjs what should I change?

### ISSUE THREAD

**Issue by Rayraegah** [egoist/poi#188]
I've been using Poi a lot for all my vuejs based web apps. I'm also a avid user of Riotjs, so having poi support riot accomplishes a great deal more.

In order to support Riotjs or any other library out there like [Svelte](https://github.com/egoist/poi/tree/master/packages/poi-preset-svelte), Inferno etc. what should I change or add to poi other than a preset?

**Comment by egoist** [comment]
Check out its webpack example: https://github.com/riot/examples/tree/gh-pages/webpack

Seems you only need to add the [riot-tag-loader](https://github.com/riot/tag-loader)

**Comment by egoist** [comment]
Like the [svelte preset](https://github.com/egoist/poi/blob/master/packages/poi-preset-svelte/index.js), but when you're using a poi config file without preset, all you need is to update webpack config in `extendWebpack` or `webpack` option
