### ISSUE TITLE
hot load is no work

### ISSUE THREAD

**Issue by ckken** [egoist/poi#191]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by zephraph** [comment]
Um. Wat?

**Comment by egoist** [comment]
Closed due to inactivity.
