### ISSUE TITLE
vue dependency version mismatch

### ISSUE THREAD

**Issue by Rayraegah** [egoist/poi#192]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Breaks with following error

```shell
Error in ./app/app-root.vue
Module build failed: Error:
Vue packages version mismatch:

- vue@2.3.4
- vue-template-compiler@2.3.3

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Add latest version Vue as dependency and run script dev.

**What is the expected behavior?**
automatically fix version mismatch or disallow local npm dependency (always use vue version from poi's package.json)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
poi v9.0.2, node v8.1.1, npm v5

**Comment by Rayraegah** [comment]
It only happens if you have vue as a dependency in project package.json and you bump its version.

**Comment by egoist** [comment]
If you want to use your own version of Vue, you need to install both `vue` and `vue-template-compiler` in your project.

**Comment by Rayraegah** [comment]
Got it. Thanks.

**Comment by egoist** [comment]
Yeah, I might add a more detailed error message to the CLI output when this error occurs.

**Comment by egoist** [comment]
This is how it will look like:

<img width="806" alt="2017-06-16 10 20 58" src="https://user-images.githubusercontent.com/8784712/27230507-1afd1500-52e2-11e7-85a5-b946a6b48c9d.png">

**Comment by Rayraegah** [comment]
Looks good imo.
