### ISSUE TITLE
Add option to create HTTPS development server

### ISSUE THREAD

**Issue by skyrpex** [egoist/poi#195]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

**What is the current behavior?**
There's no support for secure dev servers (HTTPS).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To be able to use an HTTPS server.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm currently using a secure localhost server to develop features, because my development assets need to load on a HTTPS page.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
I can make a PR. There's code for self-signed certificates in [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/v2.5.0/lib/Server.js#L355-L410), so it would be basically copy&paste.

**Comment by egoist** [comment]
nice, PR is welcome, maybe an `https` option?

**Comment by skyrpex** [comment]
Sure, I'll go for it.

**Comment by egoist** [comment]
> because my development assets need to load on a HTTPS page.

Oh, I didn't get this, why it has to be https?

**Comment by skyrpex** [comment]
I'm working on a Salesforce managed application. In order to develop with HMR, I have to inject my bundle scripts (aka http://localhost:4000/app.js) into a Salesforce page which is under HTTPS.

I have to work that way because my assets rely on some global JS objects and methods that are present on those Salesforce pages.

**Comment by quimarche** [comment]
Please, can you explain how this is used?

(I want to constrain all requests to use HTTPS so I can add a CSP tag:
<meta content="upgrade-insecure-requests" http-equiv="Content-Security-Policy">

**Comment by egoist** [comment]
@quimarche it's released on the `next` channel: `yarn add poi@next --dev`, its usage is the same as the official webpack cli since they both use `webpack-dev-server`: https://webpack.js.org/configuration/dev-server/#devserver-https

While in Poi there're two ways to set `devServer`:

1. set it in webpack config
2. set it in poi config:

```js
module.exports = {
  devServer: {}
}
```

**Comment by egoist** [comment]
It's available in `9.1.0`: https://poi.js.org/#/home?id=dev-server
