### ISSUE TITLE
ESLint check don't working

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#199]
Hi,

In the older versions of POI (in vbuild), the project was tested with eslint and return warnings or errors if the rules were not respected.

Now, it appears that checking is not enabled. It's possible to reactivate that ?

Thanks

**Comment by QingWei-Li** [comment]
See https://github.com/egoist/poi/tree/master/packages/poi-preset-eslint#preseteslint

>options.mode (string | Array<string>) In which mode to run ESLint. It could be a wildcard symbol * which means all modes, or an array of modes like ['production', 'test'] (optional, default 'production')

**Comment by egoist** [comment]
Yup, like the information above, it simply adds eslint-loader to the webpack rules.

**Comment by throrin19** [comment]
It works fine. Thanks
