### ISSUE TITLE
What means “poi” name?

### ISSUE THREAD

**Issue by Grawl** [egoist/poi#201]
It's abbreviation of “point of interest” or like fireshow equipment?

![e99008c1109d263e1d30082b824f2bc9](https://user-images.githubusercontent.com/846774/27778381-b92a8f50-5ffd-11e7-87dc-3749b4a23bb4.jpg)

**Comment by egoist** [comment]
lol, this is actually from a japanese word:

> Poi (っぽい) is a Japanese word roughly translated to “supposedly,” which has become associated with the Kantai Collection character Yuudachi. Additionally, because of Kancolle’s focus on warships, the word has also become a commonly spammed word in the chat for the similarly-themed game World of Warships.

Maybe @kazupon knows more about this 😂

And it's easy to type... that's it..
