### ISSUE TITLE
Poi 9.1.0, "Failed to mount component: template or render function not defined."

### ISSUE THREAD

**Issue by hypercub3d** [egoist/poi#202]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
On startup, HMR attempts to load the app, and then displays this message. The App does not fully mount.

The app simply loads Vue, Vue-Router, an app.vue and a dashboard.vue.

The index.js file mounts app.vue which contains a parent div and a <router-view></router-view> tag.

The dashboard.vue, simply contains, a parent div with the word dashboard.

Navigating to the router endpoint /dashboard should simply mount the dashboard.vue component into the app.vue.

But the console then shows this error.

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <App> at src/app.vue
         <Root>

```

These problems seem to be related to the latest version of vue-loader.

https://github.com/vuejs/vue-loader/issues/863

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The application should load without any errors. This all worked without issue in version 9.0.4.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Latest Chrome and Safari.
Node 6.10.3
Poi 9.1.0
vue-router 2.7.0

**Comment by egoist** [comment]
Can you provide a simple repo to reproduce or your poi config file?

**Comment by hypercub3d** [comment]
Hi,
Yes, here you go.

https://github.com/hypercub3d/poi-test

I updated my original comment to note that this worked fine with version 9.0.4

I don't have a poi.config.js, I am using the default settings.

**Comment by egoist** [comment]
I think you need to:

```diff
- component: require( '@/dashboard.vue' )
+ component: require( '@/dashboard.vue' ).default
```

See the release not: https://github.com/vuejs/vue-loader/releases/tag/v13.0.0

**Comment by hypercub3d** [comment]
Yes, that certainly fixed the problem. :) Thank you very much for your help and time.

I should have read the vue-loader docs more carefully.

I love poi by the way. It's a wonderful idea. Do you have a Patreon or development fund? I'd love to pitch in a few bucks.

**Comment by egoist** [comment]
I added a release note [here](https://github.com/egoist/poi/releases/tag/v9.1.0) btw. Sorry for didn't mention the breaking change 😅

And yup, here it is: https://github.com/egoist/donate

**Comment by egoist** [comment]
looks like the problem in https://github.com/vuejs/vue-loader/issues/863 still exists, hmr in `<template>` tag is broken, as a workaround:

```bash
yarn add vue
yarn add vue-loader@12 vue-template-compiler --dev
```

Use `vue-loader@12` for now, and it requires `vue-template-compiler` as a peerdendency, and you need to install `vue` as well to prevent from version mismatching.
