### ISSUE TITLE
Add a PWA preset

### ISSUE THREAD

**Issue by egoist** [egoist/poi#204]
- Choose a plugin
  - workbox?
  - swprecache?
  - offline-plugin?
- Auto-generate manifest.json
- Auto-insert relevant meta tags to `index.html`
- etc?

**Comment by JesusCrow** [comment]
- Should consider Service Worker aggressive caching. After releasing new app on top of old ones domain you might notice that some Service Workers load local offline data instead of new server data because of mismatch
- Config for caching policy

**Comment by BruceHem** [comment]
any progress on this?

**Comment by egoist** [comment]
@BruceHem for now use https://github.com/egoist/poi/tree/master/packages/poi-preset-offline or https://github.com/egoist/poi/tree/master/packages/poi-preset-sw-precache

**Comment by BruceHem** [comment]
@egoist thanks

**Comment by edDimensi** [comment]
@egoist offline-plugin deprecate `ServiceWorker.navigateFallbackURL` property in 3.9 version.
