### ISSUE TITLE
Electron Vue Preset

### ISSUE THREAD

**Issue by steambap** [egoist/poi#205]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I navigate to https://poi.js.org/#/recipes/electron-app and got `[todo]`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
(maybe) yarn add poi-preset-electron-vue

**If this is a feature request, what is motivation or use case for changing the behavior?**
I guess Vue is a common choice for an electron app.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
I think following changes would be enough for an Electron app?

```js
module.exports = {
  webpack(config) {
    config.target = 'electron-renderer'
    return config
  }
}
```

**Comment by steambap** [comment]
Ok, there will work for me

**Comment by egoist** [comment]
The [recipe](https://poi.js.org/#/recipes/electron-app) has been updated, I also added poi support to the simple [electron template](https://github.com/egoist/template-electron).

**Comment by egoist** [comment]
I will create an Electron preset, a few additional configurations are required for large apps.
