### ISSUE TITLE
Can't get mp4 to load

### ISSUE THREAD

**Issue by stursby** [egoist/poi#208]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Trying to load a static mp4 from `/src/static/video.mp4`

and then in my `App.vue`

```html
<template>
  <div>
    <video controls>
      <source src="./static/video.mp4">
    </video>
  </div>
</template>
```

![image](https://user-images.githubusercontent.com/527849/28132952-ff6322b8-6703-11e7-8350-2ef934fa280b.png)

And the output is the following (in Browser and Console)

![image](https://user-images.githubusercontent.com/527849/28133024-3c60e358-6704-11e7-990f-7213523e580d.png)

![image](https://user-images.githubusercontent.com/527849/28133032-405ff5b6-6704-11e7-83e0-f0000805286d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Te reproduce, place a video in `/src/static` and try to load in a `.vue` component.

**What is the expected behavior?**

The video would load.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

I figured that `file-loader` wasn't correctly handling a `.mp4` file, so I tried using `extendWebpack()` in my `poi.config.js` file... but no luck.

Here's what I tried in my config:

```js
module.exports = {
  extendWebpack(config) {
    config.module.rule('static')
      .test(/\.mp4$/)
      .loader('file-loader')
  }
}
```

Any help would be much appreciated, thanks!

**Comment by egoist** [comment]
This will entirely reset `test` value: 

```js
config.module.rule('static')
      .test(/\.mp4$/)
```

But I think it should work for `.mp4` file. Can you provide a repo to reproduce?

**Comment by stursby** [comment]
Yes, I can make a quick repo.

I was also trying to add `.mp4` in the [source code](https://github.com/egoist/poi/blob/master/packages/poi/lib/create-config.js#L194), but that didn't work either.

**Comment by egoist** [comment]
btw, you can also modify webpack config directly:

```js
module.exports = {
  webpack(config) {
    config.module.rules.push({})
    return config
  }
}
```

**Comment by stursby** [comment]
Interesting... so I got it to work by moving the `static/` folder to the project root.

before:
```
src/static/video.mp4
```

after:
```
static/video.mp4
```

**Comment by egoist** [comment]
https://poi.js.org/#/home?id=copy-static-files
