### ISSUE TITLE
polyfills get loaded too late

### ISSUE THREAD

**Issue by fiws** [egoist/poi#209]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3409958/28162589-efe78b98-67c7-11e7-81ec-af4fbdd8cb46.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
set `polyfills: true` and use `Object.assign`. Old browsers fail because the polyfills get loaded too late.

**What is the expected behavior?**
The polyfills script tag should be first. **Edit**: should be after the vendor.js

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Poi: v9.1.2
node: v8.1.4
os: Arch Linux

**Comment by egoist** [comment]
hmm, seems it's difficult to add a polyfill entry before other entries, maybe remove this option

**Comment by fiws** [comment]
soo, how would you do this without poi? :sweat_smile:

**Comment by egoist** [comment]
Simply import polyfills in your entry file.

**Comment by egoist** [comment]
for example: https://github.com/egoist/codepan/blob/master/src/index.js#L1

**Comment by fiws** [comment]
thx. That's pretty easy. I would be fine if the `polyfills` feature is removed and this ↑ is just documented instead.
