### ISSUE TITLE
run poi foo.js show the error `Module not found: Error: Can't resolve 'loglevel`

### ISSUE THREAD

**Issue by luxp** [egoist/poi#214]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When run `boi foo.js`, the terminal log this
```
Module not found: Error: Can't resolve 'loglevel'
```
**If the current behavior is a bug, please provide the steps to reproduce.**
- npm install -g poi
- create  foo.js
- poi foo.js

**What is the expected behavior?**
- start the dev server and compile the js file

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
- nodejs@8.1.3
- poi@9.1.4

**Comment by egoist** [comment]
Ah it's webpack-dev-server bug: https://github.com/webpack/webpack-dev-server/issues/984

They accidentally added `loglevel` to `devDependencies` instead of `dependencies`, for a quick fix: `yarn add loglevel --dev` in your project

**Comment by luxp** [comment]
I just found out that a minute ago, and solved it with the same way....
Thanks, happy weekend 😄

**Comment by egoist** [comment]
It should be fixed now.
