### ISSUE TITLE
Vue async components not working

### ISSUE THREAD

**Issue by stursby** [egoist/poi#216]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm trying to use the new Vue 2.4 async components. So I've changed my imports from:

before
```js
import SignaturePreview from '@/components/SignaturePreview'
import Instructions from '@/components/Instructions'
```

after
```js
const SignaturePreview = import('@/components/SignaturePreview')
const Instructions = import('@/components/Instructions')
```

And here's the rest of <script> code

```js
...
export default {
  name: 'App',
  components: {
    SignatureForm,
    SignaturePreview,
    Instructions
  }
}
</script>
```

And I get the following output in the console:

![image](https://user-images.githubusercontent.com/527849/28630036-c2fa176e-71ee-11e7-8fb9-f00a35c9f63f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
That the `SignaturePreview` and `Instructions` components will load async

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
Should be `() => import('@/components/SignaturePreview')`?

**Comment by stursby** [comment]
Nice! Worked. Was hoping it was something that simple. Thanks!

solution
```js
const SignaturePreview = () => import('@/components/SignaturePreview')
const Instructions = () => import('@/components/Instructions')
```

PS - I had to restart poi dev server for changes to take effect.
