### ISSUE TITLE
Webpack hot reload not working

### ISSUE THREAD

**Issue by layanto** [egoist/poi#217]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When making Vue template change, page refreshed instead of webpack hot reload. 
**If the current behavior is a bug, please provide the steps to reproduce.**
Was working fine with power 9.1.2. Tested not working on point 9.1.7 and 9.1.8.

**What is the expected behavior?**
Page reload via webpack hot reload.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Node 6.11.1
Poi 9.1.8
Is Win 10

**Comment by layanto** [comment]
Auto correct!!
Was working fine with poi 9.1.2. Tested not working on poi 9.1.7 and 9.1.8.

**Comment by egoist** [comment]
Hmm tried poi 9.1.8 and HMR works fine with template, tested with this template: https://github.com/egoist/template-poi-minimal

**Comment by layanto** [comment]
With my project, poi 9.1.2 works fine but poi 9.1.3 HMR not working properly. How to find out what was changed between poi 9.1.2 and 9.1.3?

**Comment by layanto** [comment]
Seems to do with this commit: https://github.com/egoist/poi/commit/459749f1c389934a81cef08f21ef82e3672e26d9

If I add the ModuleConcatenationPlugin in the above commit to poi 9.1.2, HMR stops working for me.

**Comment by egoist** [comment]
ok seems `ModuleConcatenationPlugin` is still experimental, I just removed it in latest version.

**Comment by layanto** [comment]
https://github.com/webpack/webpack-dev-server/issues/949
