### ISSUE TITLE
Build errors in latest version

### ISSUE THREAD

**Issue by Rayraegah** [egoist/poi#219]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Build fails

error information
```
> Bundling with Webpack 3.4.1
> Creating an optimized production build:


client.329a5794.js from UglifyJs
TypeError: Cannot read property 'reset' of undefined
```

Compile with 
```
minimize: false,
```

in poi.config.js and the build completes without errors.

**If the current behavior is a bug, please provide the steps to reproduce.**

npm run build on a previously working codebase

**What is the expected behavior?**

Build should complete without errors

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
poi: ^9.1.12
MacOS, nodejs - latest versions.

**Comment by egoist** [comment]
Any code sample I can use to reproduce this? what the last working version of Poi?

**Comment by Rayraegah** [comment]
Compile with 
```
minimize: false,
```

in poi.config.js and the build passes.

My project has restricted code - otherwise i would have given you a repo to debug :D

**Comment by egoist** [comment]
then what version did you upgrade Poi from?

**Comment by Rayraegah** [comment]
The last known version of Poi I had used to make a build was 8.1.1. Upgraded to 9.1.12 a couple hours ago and made a new build. Noticed the error.

**Comment by egoist** [comment]
try removing node_modules and re-install 😄

**Comment by Rayraegah** [comment]
lol I feel noob for not trying that first. Yes. it fixed the error.
