### ISSUE TITLE
9.2.3: Sock-js net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by fjc0k** [egoist/poi#222]
The same as: https://github.com/egoist/poi/issues/221

**Additional information:**

![image](https://user-images.githubusercontent.com/13151189/29162735-dee90aac-7dec-11e7-87cf-5c3571e6c2a0.png)

![image](https://user-images.githubusercontent.com/13151189/29162770-f893125e-7dec-11e7-9370-78129926a150.png)

![image](https://user-images.githubusercontent.com/13151189/29162772-fb70f57c-7dec-11e7-85ae-3b9653278222.png)

google: `sockjs-node/info`:
![image](https://user-images.githubusercontent.com/13151189/29162785-01408cf6-7ded-11e7-9f14-43b47267d5bc.png)

Hope them will help.

**Comment by egoist** [comment]
Ah I can't reproduce this, can you provide a repo?

**Comment by fjc0k** [comment]
@egoist https://github.com/fjc0k/today-front-end

**Comment by egoist** [comment]
hmm try re-install deps

**Comment by fjc0k** [comment]
好了...666666😆
