### ISSUE TITLE
SPA style navigation goes away after build with Prerender SPA Plugin

### ISSUE THREAD

**Issue by stursby** [egoist/poi#225]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I'm tying to generate a static site with Poi and [Prerender SPA Plugin](https://github.com/chrisvfritz/prerender-spa-plugin). I've got the static site generation working using the following:

```javascript
// poi.config.js
const path = require('path')
const PrerenderSpaPlugin = require('prerender-spa-plugin')

module.exports = {
  webpack(config) {
    const plugin = new PrerenderSpaPlugin(
      // entry
      path.join(`${__dirname}/dist`),
      // sample routes for testing
      ['/', '/about', '/news/2017/imgix-assets'],
      // options
      {
        captureAfterTime: 1000
      }
    )
    config.plugins.push(plugin)
    return config
  }
}
```

The static site is now in `/dist`

![image](https://user-images.githubusercontent.com/527849/29340345-1f4085a8-81e4-11e7-86bd-47d9d2151c0d.png)

The problem is that now when I run the static site from dist, the browser is doing full page reloads, instead of the desired SPA style route transitions.

cc @chrisvfritz

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would like to keep the SPA style page transitions (if possible).

**If this is a feature request, what is motivation or use case for changing the behavior?**
Feature

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Would this have anything to do with the fact that Poi is using code splitting? There's some info in the Prerender SPA docs --> https://www.npmjs.com/package/prerender-spa-plugin#code-splitting but wasn't sure if that's the right fix.

Any thoughts would be much appreciated!

**Comment by egoist** [comment]
Any demo or code?

**Comment by stursby** [comment]
@egoist Yep! Here you go:

Repo: https://github.com/stursby/vue-prerender-spa-demo

Live demo: https://vue-prerender-spa-demo.surge.sh/

A few notes:
- When running locally (`yarn dev`), everything things works as expected, but as an SPA
- On the live demo, you'll notice clicking on a User link forces a full page reload :/
- In `poi.config.js` I've arbitrarily set the `captureAfterTime` to 1000ms to let the axios calls finish

**Comment by egoist** [comment]
Hmm seems the client-side javascript never bootstraps, because `#app` has gone after prerendering, you need to set the element id to `app` here: https://github.com/stursby/vue-prerender-spa-demo/blob/master/src/App.vue#L2

**Comment by stursby** [comment]
Interesting. Ok, that seems to work, however noticing some odd text glitch as it's still hitting the API endpoints even thought the data is there... hmm wondering how to go "API-less" after build. Will keep digging, thanks for you help! 🙌

**Comment by egoist** [comment]
closing since it's solved 👌

**Comment by stursby** [comment]
@egoist Thanks!
