### ISSUE TITLE
api proxy broken

### ISSUE THREAD

**Issue by steambap** [egoist/poi#228]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
api proxy broken
**If the current behavior is a bug, please provide the steps to reproduce.**
This is my poi.config.js, it works with poi v9.3.0
```JavaScript
module.exports = {
	devServer: {
		proxy: 'http://localhost:8900'
	}
};
```
My request to /api/todo will proxy to http://localhost:8900/todo
If I upgrade to poi v9.3.1, my request to /api/todo will proxy to http://localhost:8900/api/todo, which is not what I want.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
It is a defect in 2ad4a23e75979324acb7d8765f43c474b5992c1c
Before it is replace` '^/api'` with `''`, now it replace `'^' + proxyUrl.path` with `''`

**Comment by egoist** [comment]
made a regression in`v9.3.2`
