### ISSUE TITLE
Static directory copied to dist root in production build

### ISSUE THREAD

**Issue by myst729** [egoist/poi#229]
Assets in `/static` will be copied to `/dist` in production build. Expect them to be copied to `/dist/static`.

https://github.com/egoist/poi/blob/master/packages/poi/lib/create-config.js#L323-L327
```js
      copyOptions.push({
        from: path.resolve(cwd, 'static'),
        to: '.',
        ignore: ['.DS_Store']
      })
```

Say, I have a **picture.png** in static folder. In dev mode, it can be accessed via URL `http://localhost/static/picture.png`. So I reference it like this:

```html
<img src="/static/picture.png">
```

But in production build I get 404, because the picture is copied to `/dist` root and its URL becomes `http://[domain]/picture.png`.

I guess the `to` attribute in copy options should resolve to `/dist/static`. Or are there any particular reasons for current setting?

**Comment by egoist** [comment]
yeah, it's intentional because you can add a `./static/favicon.ico` so that it will be copied to `./dist/favicon.ico` in this way.

**Comment by myst729** [comment]
So the strategy here is to move all assets under `/src` so they are handled by webpack? Is the use case I mentioned above not encouraged?

**Comment by egoist** [comment]
it's fine to put them in `./static`, like `./static/assets` and you can reference them via `/assets/foo.png`

**Comment by myst729** [comment]
This is a little weird when work with multiple sub apps. My repo is like this:

```shell
dist/
  app2/
packages/
  app1/
  app2/
static/
```

My app1 bundle is accessed via `http://[domain]/` and app2 is `http://[domain]/app2/`. Although they are two separate apps but quite coupled from the business perspective, so I put them in one repo to ensure them get built and deployed together.

Here's poi config for app2:

```js
  entry: resolve('packages/app2/entry.js'),
  dist: resolve('dist/app2'),
  homepage: '/app2',
```

In such use case, the path issue bothers me a lot. My approach is to override the default copy option. Is there a better practice that I could adopt?

**Comment by egoist** [comment]
ah I got two questions:

- what do you want to achieve with `copy` option
  >  the path issue bothers me a lot

  I didn't get this either
- what's the problem with your current solution

**Comment by myst729** [comment]
- I want to copy `/static` to `/dist/static` as-is. So I could request assets like `<img src="/static/picture.png>` in both dev and build.

- No, actually. Just need to hand-craft the config. Would like to know if there's a neater way.

**Comment by egoist** [comment]
`./static/static` -> `./dist/static` does this work for you?

**Comment by myst729** [comment]
Still, the path changes. In dev mode it's `http://localhost/static/static/picture.png`, in prod bundle it becomes `http://[domain]/static/picture.png`. The reason I want to use absolute path is because I don't want to right `../../../../` everywhere.

**Comment by myst729** [comment]
Another approach is to define an alias to `/static` and `<img src="~@static/eleme.png">` I guess.

**Comment by egoist** [comment]
hmm I think it's `/static/picture.png` in both prod and dev? no?

If you use webpack to handle this, you can actually use `@` to resolve the path to `./src`
