### ISSUE TITLE
poi lint

### ISSUE THREAD

**Issue by egoist** [egoist/poi#233]
To run eslint as a poi command because something like https://www.npmjs.com/package/eslint-import-resolver-webpack requires a webpack config

**Comment by LucienLee** [comment]
I met that problem too: how can I get the webpack config for import resolver. 
Before making this feature work, is there any work around solution?

BTW, Any idea how to initiate that? I'm not really familiar the sturcture of Poi and want to know how people expect to config their eslint in poi. Maybe I can help this one.

**Comment by egoist** [comment]
@LucienLee To get the full webpack config Poi uses, you need to:

```js
const poi = require('poi')
const app = poi(options)
app.prepare().then(() => {
  const webpackConfig = app.getWebpackConfig()
})
```

Webpack itself supports [async config](https://github.com/webpack/webpack/issues/2697#issuecomment-228862797), but it seems eslint-import-resolver-webpack unfortunately does not.

We currently use `app.prepare()` to load babel/postcss file asynchously but they won't affect how eslint checks your code (looks like so?), so you can skip that and use `app.getWebpackConfig()` directly.

**Comment by LucienLee** [comment]
In addition to lint by CLI, I think that most of developers would set up the editor to lint code with `.eslintrc.js`, which means that we might need a way to generate static `.eslintrc.js`file. 

One possible way is ejecting resolve related configs to a file and link it in `.eslintrc.js`by a script.

**Comment by egoist** [comment]
@LucienLee yeah thats what I mean, you can use `app.getWebpackConfig()` in esline config.

**Comment by LucienLee** [comment]
However, I found that `app.getWebpackConfig()` must have wait `prepare` promise now. That would meet async issue as you said. It look like `toConfig` method is undefined before prepare

https://github.com/egoist/poi/blob/351c0bbf2862d103ba4d83938812a3eb66188012/packages/poi/lib/index.js#L69

**Comment by egoist** [comment]
@LucienLee now with po@9.6.0 you can use `app.createWebpackConfig()`

**Comment by LucienLee** [comment]
Thank you @egoist. That's awesome. It could be work as the following. 

```js
// .eslintrc.js

const poi = require('poi');
const app = poi('./poi.config.js');
const webpackConfig = app.createWebpackConfig();

module.exports = {
  ...,
  plugins: ['import'],
  ...,
  settings: {
    'import/resolver': {
      webpack:{
        config: webpackConfig
      }
    }
  }
}

**Comment by egoist** [comment]
@LucienLee it's actually `poi(require('./poi.config.js'))`, I've updated your example code 😄

**Comment by LucienLee** [comment]
It's `poi(require('./poi.config.js')())` because config is a function received options. Have updated on the previous example.

**Comment by egoist** [comment]
Now `require('poi/webpack.config')` should work (in v12 though 😥)
