### ISSUE TITLE
[Feature Request] Custom resolve path

### ISSUE THREAD

**Issue by gluons** [egoist/poi#235]
**Do you want to request a *feature* or report a *bug*?**  
> Feature

**What is the current behavior?**  
> Resolve path to `src` folder as `@`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**  
> Need to add  my own custom resolve path to the folder outside `src`.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
```
Node v8.4.0
Poi v9.3.5
Kubuntu 17.04
```

**Comment by egoist** [comment]
simply use `extendWebpack` ?

**Comment by gluons** [comment]
It may work. But can be simpler?

**Comment by gluons** [comment]
OK. I'll PR when I'm free.

**Comment by egoist** [comment]
well, what's your use case 🤔

**Comment by gluons** [comment]
- Writing many functions outside `src`. Keep it in `lib` folder (or similars).
- Store some SVG file in `resource` folder (or similars).
- Doing something that need to be kept it away from core `src`.
🙄 🙄 🙄

**Comment by egoist** [comment]
hmm it could be as simple as:

```js
module.exports = {
  webpack: {
    resolve: {
      '@': '/path/to/wherever'
    }
  }
}
```

**Comment by gluons** [comment]
Or
```js
module.exports = {
  extendWebpack(config) {
    config.resolve.alias
      .set('<my custom alias>', '/path/to/my/folder/');
  }
};
```

Indeed! It's totally my laziness. 😪
Closed. 🤣

**Comment by gluons** [comment]
Just created [poi-preset-resolve-alias](https://github.com/gluons/poi-preset-resolve-alias) to solve my laziness. 😪

**Comment by talentlessguy** [comment]
> Just created [poi-preset-resolve-alias](https://github.com/gluons/poi-preset-resolve-alias) to solve my laziness. sleeping

it doesn't work :disappointed: Opened an issue on your preset
