### ISSUE TITLE
Poi can support multi-compiler?

### ISSUE THREAD

**Issue by qqcome110** [egoist/poi#237]
I have a requirement of build for multi outputs, refer to: [webpack multi-compiler](https://github.com/webpack/webpack/tree/master/examples/multi-compiler)

I use `webpack` optional of `poi.config.js`, like below:

```js
module.exports = {
   webpack (config) {
        return [
              Object.assign({}, config, {output: 'path1'}),
              Object.assign({}, config, {output: 'path2'})
        ]
   }
}
```

When I run `poi build`, is failed:

```sh
TypeError: Cannot read property 'output' of undefined
    at runMiddlewares.then (/Users/lalala/.nvm/versions/node/v6.10.0/lib/node_modules/poi/lib/index.js:72:69)

 FAIL  Failed to start!
```

So `poi` has supported multi-compiler feature or my usage is wrong? Please give me some suggestions

**Comment by egoist** [comment]
Currently it doesn't support multi compilers 😅

**Comment by qqcome110** [comment]
Do you intend to support it?

**Comment by egoist** [comment]
Not now cuz I don't really need this, but PR is always welcome.
