### ISSUE TITLE
Expected homepage: "" to override "/" added in paths

### ISSUE THREAD

**Issue by arve0** [egoist/poi#238]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

POI always add an ending `/` to homepage url, avoiding overriding path with `homepage: ""`. E.g. ~~You cannot use relative paths, ref #51.~~ Relative paths are only possible with `homepage: "./"`.

[It happens at this line.](https://github.com/egoist/poi/blame/8db94939d8445f5c136e7ed02785bc4e5998c9b1/packages/poi/lib/utils.js#L17)

**If the current behavior is a bug, please provide the steps to reproduce.**

Add `"homepage": ""` to your configuration.

**What is the expected behavior?**

I expected the explicit `""` to actually give me relative `<link>` and `<script>`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Offline usage, for example download a zip file containing the webapp. Also publishing to relative path, like `http://domain.com/relative/path/to/app/`.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

POI version 9.3.5.

**Comment by egoist** [comment]
@arve0 why not use `./`

**Comment by arve0** [comment]
No reason, just did not cross my mind to be *even more* explicit.

Sounds like you do not want that extra test for empty `homepage`?

```js
  if (mode === 'production' && homepage && homepage.length) {
```

Rather have a note in the documentation?

**Comment by egoist** [comment]
@arve0 if you want relative path I think it's obvious that you need `./some/path` which starts with `./`

**Comment by arve0** [comment]
Hehe, not *obvious* to me. Please consider that other people might have other background than you. For example, only have knowledge of HTML. In HTML, the convention is `src="this/is/a/relative/path"`.

To prove my point, take the first search result for "html relative path": https://www.w3schools.com/html/html_filepaths.asp

**Comment by padcom** [comment]
@arve0  I think that putting everything every time to be at the root isn't such a good idea but it is very easy to change. As a workaround I use the `webpack(config)` function where I specify the `output.publicPath` to be an empty string and that covers it for me.

**Comment by arve0** [comment]
@padcom I think you are misunderstanding the issue. I'm not talking about having all files in one folder, the target files may reside in any folder. This is just an issue about treating `homepage: "./" and `homepage: ""` equivalent.

**Comment by padcom** [comment]
Oh,.. OK
