### ISSUE TITLE
Karma and Typescript, part 2

### ISSUE THREAD

**Issue by AleksueiR** [egoist/poi#240]
Thanks for fixing #239 so quickly!

I'm running into a different issue now - `npm run test` logs errors about not being able to find imported modules, but tests still pass correctly anyway. Similar setup as before but with an import statement:

```js
// app.test.js

import Vue from 'vue'
import app from './app.vue'
import assert from 'assert'

it('ok', () => {
  const Ctor = Vue.extend(app)
  const vm = new Ctor().$mount()
  assert(vm.$el.textContent === '0')
})
```

```vue
// app.vue

<template>
  <div id="app">{{ count }}</div>
</template>

<script lang="ts">
  import Vue from 'vue';

  export default {
    data() {
      return {
        count: 0
      }
    }
  }
</script>
```

```js
// poi.config.js

module.exports = {
    presets: [
        require('poi-preset-typescript')({
            loaderOptions: {
                appendTsSuffixTo: [/\.vue$/]
            }
        }),
        require('poi-preset-karma')({
            port: 5001, // default
            files: ['test/unit/*.test.js'], // default
        })
    ]
}
```

Output:
> (6,17): error TS2307: Cannot find module 'vue'.
>
>  FAIL  Compiled with errors!
>
>
> ERROR in .\test\unit\app.vue.ts
> (6,17): error TS2307: Cannot find module 'vue'.
> 18 09 2017 13:03:50.012:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:5001/
> 18 09 2017 13:03:50.044:INFO [launcher]: Launching browser Chrome with unlimited concurrency
> 18 09 2017 13:03:50.051:INFO [launcher]: Starting browser Chrome
> 18 09 2017 13:03:51.848:INFO [Chrome 60.0.3112 (Windows 7 0.0.0)]: Connected on socket 8U8KK7Nw27ljl2nBAAAA with id 58171579
> INFO: 'Download the Vue Devtools extension for a better development experience:
> https://github.com/vuejs/vue-devtools'
> INFO: 'You are running Vue in development mode.
> Make sure to turn on production mode when deploying for production.
> See more tips at https://vuejs.org/guide/deployment.html'
>   v ok
>
> Finished in 0.019 secs / 0.007 secs @ 13:03:52 GMT-0400 (Eastern Daylight Time)
>
> SUMMARY:
> v 1 test completed

No errors are logged if `lang="ts"` is removed.

Thanks.

**Comment by egoist** [comment]
do you have poi install in your project?

**Comment by egoist** [comment]
see https://vuejs.org/v2/guide/typescript.html#Recommended-Configuration you also need to configure tsconfig.json for Vue project

**Comment by AleksueiR** [comment]
Yes, I have typescript configured and everything compiles correctly with `npm run dev` and `npm run build`.  Here's the typescript config:
```json
// tsconfig.json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "lib": [
            "dom",
            "es5",
            "es2015.promise"
        ],
        "outDir": "./dist/",
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "removeComments": true,
        "module": "es2015",
        "moduleResolution": "node",
        "target": "es5",
        "jsx": "react"
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

I'm getting useless errors with `npm run test` even though tests do pass.
![](https://i.imgur.com/SSDuDLy.png)

Here's a reproducible repo: https://github.com/AleksueiR/tests.git

**Comment by egoist** [comment]
Hmm I'm not entirely sure what's going on since I don't use ts myself 😅

**Comment by gluons** [comment]
1. You should change your test files from **JavaScript file** (`app.test.js`) to **TypeScript file** (`app.test.ts`).
2. You'll need some types declarations.  
    - `npm install --D @types/mocha` for [`mocha`](https://mochajs.org/) (default `poi-preset-karma`'s framework)  
    - `npm install -D @types/node` for `assert`.
3.  Add [`.vue` file declaration](https://github.com/vuejs/vue-class-component/blob/master/example/sfc.d.ts) into your `test` folder. You need it for `.vue` file.
4. Change this in `app.test.ts`:

    ```diff
    import Vue from 'vue'
    import app from './app.vue'
    import assert from 'assert'

    it('ok', () => {
    - const Ctor = Vue.extend(app)
    + const Ctor = Vue.extend(app as Vue.ComponentOptions<Vue>)
      const vm = new Ctor().$mount()
      assert(vm.$el.textContent === '0')
    })
    ```
5. Change `poi.config.js`:

    ```diff
    module.exports = {
        presets: [
            require('poi-preset-typescript')({
                loaderOptions: {
                    appendTsSuffixTo: [/\.vue$/]
                }
            }),
            require('poi-preset-karma')({
                // basePath: 'src',
                port: 5001, // default
    -           files: ['test/unit/*.test.js'], // default,
    +           files: ['test/unit/*.test.ts'], // default,
            })
        ],
        extendWebpack(config) {
            config.resolve.alias
                .set('vue$', 'vue/dist/vue.esm.js'); // vue.esm include template compiler; without it all templates need to be pre-compiled
    +   },
    +   karma: {
    +       mime: {
    +           'text/x-typescript': ['ts']
    +       }
        }
    };
    ```

**Comment by gluons** [comment]
You may **not need** this `poi-preset-typescript` options

```javascript
{
	loaderOptions: {
		appendTsSuffixTo: [/\.vue$/]
	}
}
```

Because, `poi-preset-typescript` already set it for you.

https://github.com/egoist/poi/blob/6fba19fb2214f3ae8920edc52bbcb09cb606e007/packages/poi-preset-typescript/index.js#L16-L20

**Comment by gluons** [comment]
@egoist Does he need this `extendWebpack`?

```javascript
extendWebpack(config) {
	config.resolve.alias
		.set('vue$', 'vue/dist/vue.esm.js'); // vue.esm include template compiler; without it all templates need to be pre-compiled
}
```

I've seen your `resolve.alias` but I'm not sure about `templateCompiler` value.

https://github.com/egoist/poi/blob/db30e421c37fabb7188f2a7a6515cbb6df37ddc5/packages/poi/lib/create-config.js#L127-L129

**Comment by AleksueiR** [comment]
@gluons Thank you very much for your help! It works now. I'll check if there are any snags with more involved tests.

**Comment by AleksueiR** [comment]
Everything seems to be fine so far. Also, I found that instead of using a generic `.vue` declaration, you can dynamically generate declarations for your `.vue` files with [vuetype](https://github.com/ktsn/vuetype).

Thanks again!

This can be closed now.
