### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by egoist** [egoist/poi#242]
<img width="513" alt="2017-09-29 11 34 05" src="https://user-images.githubusercontent.com/8784712/31023539-c167869e-a56e-11e7-87ea-fa6ccbd40b33.png">

Just in case you met the same issue when you're using yarn, try:

```bash
rm -rf yarn.lock
yarn
```

**Comment by egoist** [comment]
This sometimes happens after you upgrade dependencies manually or by running `yarn upgrade-interactive`.

**Comment by gluons** [comment]
This is **poi** issue or its dependencies or something else?

**Comment by egoist** [comment]
@gluons maybe a yarn thing 😅

**Comment by gluons** [comment]
![OMG](https://media.giphy.com/media/Nm8ZPAGOwZUQM/giphy.gif)
