### ISSUE TITLE
Make bundling components even easier

### ISSUE THREAD

**Issue by egoist** [egoist/poi#243]
`poi build --component`

it will be equivalent to `poi build --format cjs --no-minimize --no-html --no-sourceMap`

**Comment by padcom** [comment]
Depending on the time frame for this implementation is there a way for now for this information to find its way to the documentation?

**Comment by mblarsen** [comment]
Nice work @skiano

**Comment by egoist** [comment]
Released https://github.com/egoist/poi/releases/tag/poi%409.5.2 , thanks to @skiano

**Comment by egoist** [comment]
`component` option is renamed to `library` in `v9.6.3`, since it's not essentially a component 😅

`component` option would still work for now for compatibility.
