### ISSUE TITLE
karma-preset: Empty coverage report

### ISSUE THREAD

**Issue by mblarsen** [egoist/poi#245]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Enable `coverage: true` in `poi-preset-karma` config and you should get a lcov report.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the example in the preset and see that lcov.info turns out 0 size:

```
0 drwxr-xr-x  8 mblarsen  staff  272 Oct  2 13:18 lcov-report
0 -rw-r--r--  1 mblarsen  staff    0 Oct  2 13:18 lcov.info
```

**What is the expected behavior?**

A valid non-empty lcov report.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Poi: 9.3.8
Node: 8.6.0
OS: macOS Sierra

**Comment by mblarsen** [comment]
@egoist spotted the issue will do another PR

**Comment by egoist** [comment]
@mblarsen 👍

**Comment by mblarsen** [comment]
I've got a big fat `lcov.info` file now @egoist 😄
