### ISSUE TITLE
preset-karma: static folder serve: true

### ISSUE THREAD

**Issue by mblarsen** [egoist/poi#247]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

If you want to serve files in your Karma tests you'll have to set up file-serving yourself.

```
  presets: [
    require('poi-preset-karma')({
      files: [
        'test/*.test.js',
        {pattern: 'test/*.m??', watched: false, included: false, served: true, nocache: false},
      ]
    })
  ],
```

In my particular test case I'm fetching an audio file for the server for processing. 

**What is the expected behavior?**

`static` folder is already treated in a special way. E.g. webpack automatically copies the files in static folder.

It would be convenient if the karma preset would also serve these when running tests.

```
     {pattern: 'static/*', watched: false, included: false, served: true, nocache: false},
```

(maybe `nocache` should be true, I'm undecided on that one)

**If this is a feature request, what is motivation or use case for changing the behavior?**

Delightful web development for Front-End (and testing)

ps: I can work on a PR if it makes sense to you to have this feature

**Comment by egoist** [comment]
Ah yeah, this makes sense to me too 👍🏻
