### ISSUE TITLE
Separate vue to preset

### ISSUE THREAD

**Issue by natrim** [egoist/poi#248]
**Do you want to request a *feature* or report a *bug*?**
probably feature

tldr; separate vue to preset like react

----

the preffered way in doc says to use
`yarn add poi --dev`
ie. add poi to project

but package `poi` depends on vue

if i want to use it with react
it still installs vue and other vue packages
which pollutes the project with unneeded dependencies

meaning it would be nice to have vue support extracted to separate preset like react

**Comment by egoist** [comment]
Hmm there're actually only 3 deps for Vue support:

<img width="319" alt="2017-10-05 9 01 55" src="https://user-images.githubusercontent.com/8784712/31228973-e748b8c6-a9a4-11e7-98bc-6fe5650c602c.png">

If I removed Vue support it would break all current Vue projects which are built with Poi. btw I want to make this work with Vue out of the box.
