### ISSUE TITLE
Export webpack.config.js

### ISSUE THREAD

**Issue by obrienmd** [egoist/poi#252]
Feature request: I'd love poi to be able to export the webpack config it uses when it runs live or builds. I have a few projects where I am required to have that webpack config for deployment (only a limited subset of npm packages available), and while I love to use poi for development, being able to export webpack.config.js would be fantastic.

**Comment by egoist** [comment]
> I am required to have that webpack config for deployment (only a limited subset of npm packages available)

I don't get this, do you mean that you can't install poi for deployment because of only a limited subset of npm packages available?

---

currently it's impossible to export raw webpack config file because we're using webpack-chain internally.

**Comment by obrienmd** [comment]
Yep sorry, the deployment image I have to use is prebuilt, and the process
to add an npm package is a pain. It's a silly artificial barrier, but
changing it will take a while :) any rate, figure this sort of prtability
might be useful to others as well.

**Comment by egoist** [comment]
@obrienmd even if you got a webpack config file you still need to install webpack and plugins to run the build process 😅

**Comment by obrienmd** [comment]
I understand that, and the image should have the plugins I need, and has
webpack 3.something, already frozen.

**Comment by obrienmd** [comment]
Id like to see what poi is using so I can line up the actual webpack config
where I cannot install poi as closely as possible. If it's not an
interesting feature, feel free to close this up :)

**Comment by egoist** [comment]
yeah I think it's more reasonable to update your deployment image instead 😄
