### ISSUE TITLE
Feature Request - purifycss-webpack with Vue files

### ISSUE THREAD

**Issue by morrislaptop** [egoist/poi#253]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
All the CSS included from Bulma / Bootstrap is included in final build

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To remove any unused CSS using the purifycss-webpack plugin

**If this is a feature request, what is motivation or use case for changing the behavior?**
To reduce file size of the exported CSS like what happens with JS

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
If we add this plugin it will actually work for all files not only Vue files I think 😄

For now you can add that plugin manually or make a poi preset for it.

**Comment by marvinroger** [comment]
I second that, that'd we awesome - even as a poi preset -.

**Comment by BorisTB** [comment]
any progress on this?

**Comment by egoist** [comment]
@BorisTB what needs to change to make it work with Poi? you can extend webpack config currently https://poi.js.org/#/home?id=webpack

I will consider having it built-in in Poi v10

**Comment by morrislaptop** [comment]
I had a stab at making a preset - https://www.npmjs.com/package/poi-preset-purifycss

Let me know what you think!
