### ISSUE TITLE
Production source maps include absolute local paths

### ISSUE THREAD

**Issue by bmaland** [egoist/poi#257]
**What is the current behavior?**

Absolute local paths are provided in production source maps.

**What is the expected behavior?**

I would expect it to behave like create-react-app (absolute in dev, relative in production). See their implementation here: https://github.com/facebookincubator/create-react-app/blob/a0030fcf2df5387577ced165198f1f0264022fbd/packages/react-scripts/config/webpack.config.prod.js#L79-L82

**Comment by egoist** [comment]
Fixed in `v9.4.2`
