### ISSUE TITLE
TypeScript plugin can't find App.vue module

### ISSUE THREAD

**Issue by padcom** [egoist/poi#261]
**Do you want to request a *feature* or report a *bug*?**
This is a bug report

**What is the current behavior?**
```
(2,17): error TS2307: Cannot find module './App.vue'.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
index.ts
```
import * as Vue from 'vue'
import App from './App.vue'

new Vue({
    el: '#app',
    render: h => h(App)
})
```
App.vue
```
<template>
  <div>Hello</div>
</template>

<script>
import * as Vue from 'vue'

export default Vue.extend({
})
</script>
```
tsconfig.json (copied over from official Vuejs documentation)
```
{
  "compilerOptions": {
    // this aligns with Vue's browser support
    "target": "es5",
    // this enables stricter inference for data properties on `this`
    "strict": true,
    // if using webpack 2+ or rollup, to leverage tree shaking:
    "module": "es2015",
    "moduleResolution": "node"
  }
}
```
poi.config.js
```
module.exports = {
  presets: [
    require('poi-preset-typescript')(/* options */)
  ]
}
```
Execute like this:
```
poi index.ts
```
Will yield the following error:
```
(2,17): error TS2307: Cannot find module './App.vue'.

 FAIL  Compiled with errors!
```

**What is the expected behavior?**
I would expect the App component to be found and used in the render method

**If this is a feature request, what is the motivation or use case for changing the behavior?**
No it is a bug report

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Linux, Node 8, poi 9.4.3

**Comment by egoist** [comment]
@padcom see https://github.com/vuejs/vue/issues/5298

**Comment by padcom** [comment]
I hate when that happens - as soon as you get an answer for one question another one pops up:
```
(2,10): error TS1192: Module '"example/node_modules/vue/types/index"' has no default export.
```
What's up with this one? Shall I open another issue for it?

**Comment by padcom** [comment]
I just checked and removing the `Vue.extend` call when exporting doesn't change anything

**Comment by egoist** [comment]
Use Vue 2.5+

**Comment by padcom** [comment]
It's working! Yeah! Finally! A simple way to have TypeScript and Vue in one project! Thank you Thank you Thank you!!!

**Comment by trusktr** [comment]
Got it. I just had to add the [sfc.d.ts](https://github.com/vuejs/vue-class-component/blob/master/example/sfc.d.ts) file to the project, and add it in tsconfig.json, 

```json
{
    "module": "es2015",
    "moduleResolution": "node",
    "include": [
        "src/**/*",
        "test/**/*"
    ],
    "files": [
        "vue.d.ts"
    ]
}
```

**Comment by padcom** [comment]
It'd be awesome if the typescript preset could somehow provide this file.
It's just a pain in the ass to add it to every project...

2018-04-16 22:29 GMT+02:00 Joe Pea <notifications@github.com>:
