### ISSUE TITLE
Example VueJs standalone component

### ISSUE THREAD

**Issue by artyprog** [egoist/poi#263]
Hy

Could  you please give the command line to compile a  .vue
file to a standalone component usable in a browser ?

Regards

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
Here're some useful link: https://poi.js.org/#/recipes/cjs-and-umd-format?id=related

Well only one for now: https://medium.com/poi-js/bundle-and-publish-your-vue-componet-like-a-pro-9ce27f9b5f65

**Comment by artyprog** [comment]
Thank you very much. I have to understand how to use cjs format in the browser...

**Comment by mblarsen** [comment]
Here is one I just made with poi https://github.com/mblarsen/vue-browser-acl

**Comment by mblarsen** [comment]
Here is another example https://github.com/paliari/v-autocomplete

**Comment by mblarsen** [comment]
@egoist maybe add a wiki page of projects that uses poi and link to it in the readme?

**Comment by egoist** [comment]
@mblarsen maybe follow the trend and make an `awesome-poi` repo for this 😅

**Comment by mblarsen** [comment]
That is a way to get some awareness as well. Although the scope is a bit different. What would be the categories:

* presets
* examples
* X uses

**Comment by egoist** [comment]
Yeah, we can discuss this elsewhere, I'm closing this issue since it's solved.

**Comment by artyprog** [comment]
Thank you very much all of you

Regards

2017-10-30 7:25 GMT+01:00 EGOIST <notifications@github.com>:

**Comment by egoist** [comment]
Just created https://github.com/egoist/awesome-poi, welcome to make pull requests there 😄

**Comment by klarkc** [comment]
Checkout my template for creating vue components, it's using poi under the hood: https://github.com/InCuca/vue-standalone-component

**Comment by artyprog** [comment]
Thanks all of you :-)
