### ISSUE TITLE
Error while accessing API through DevServer proxy

### ISSUE THREAD

**Issue by padcom** [egoist/poi#266]
**Do you want to request a *feature* or report a *bug*?**
This is a bug report

**What is the current behavior?**
404 not found

**If the current behavior is a bug, please provide the steps to reproduce.**
1. In poi.config.js add the following section as per documentation (https://poi.js.org/#/home?id=proxy-api-request):
```
  devServer: {
    proxy: 'https://jsonplaceholder.typicode.com/posts'
  }
```
2. Start application
3. Navigate to http://localhost:4000/posts/1

**What is the expected behavior?**
https://jsonplaceholder.typicode.com/posts/1 returns data in JSON format

**If this is a feature request, what is the motivation or use case for changing the behavior?**
It is a bug report

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Linux, Node 8.8, poi 9.4.3

**Comment by mblarsen** [comment]
The docs stats that you can proxy URLs from `/api/*`

So for example if you have:

```
 devServer: {
    proxy: 'https://jsonplaceholder.typicode.com'
  }
```

(note the absence of posts at the end)

You will get your posts when you visit `http://localhost:4000/api/posts/1`

**Comment by padcom** [comment]
Well, this is pretty useless to force the `/api/` path on resources. Is there any way to configure that?

**Comment by mblarsen** [comment]
I wouldn't call it useless. It is a pretty common URL for API routes. To answer your question it doesn't look like it can be configured. https://github.com/egoist/poi/blob/b6a0d64da8338dc57b7bd5cfdd2a02ebfc1a333a/packages/poi/lib/server.js#L17

You can create a PR or an issue for it.

**Comment by padcom** [comment]
Thanks for pointing me in the right direction. It looks like if the `proxy` key is not a string then it will be used as-is therefore full capabilities of webpack-dev-server proxy mechanism are available.

**Comment by mblarsen** [comment]
Ah yeah you are right.

**Comment by padcom** [comment]
Just to summarize:

```
  devServer: {
    proxy: {
      '**': {
        target: 'https://jsonplaceholder.typicode.com',
        changeOrigin: true
      }
    }
```
This means _proxy everything that you don't know to https://jsonplaceholder.typicode.com and make sure the proxy requests are sent with the proper Host HTTP header_

**Comment by mblarsen** [comment]
> ... requests are sent with the proper Host HTTP header

That's the `changeOrigin: true` part?

**Comment by padcom** [comment]
That is about changing the Host header so that the name-based virtual host knows which virtual server to use
