### ISSUE TITLE
poi -c xx.js build failed, but poi build -c xx.js works

### ISSUE THREAD

**Issue by xiaoping0x** [egoist/poi#267]
version: `9.4.1`

`poi -c xx.js build` failed, but `poi build -c xx.js` works

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

I think it better support both.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
`poi -c xx.js build` is very confusing since `poi` itself is a command which is an alias To `poi dev`

**Comment by egoist** [comment]
And it's done by https://github.com/cacjs/cac so anyways we can't do anything here.
