### ISSUE TITLE
option to not clear terminal buffer

### ISSUE THREAD

**Issue by mgutz** [egoist/poi#268]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Terminal screen clears when poi starts

**What is the expected behavior?**

An option to not clear the screen.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

As a new user of poi, it's hard to see what's in the config. All I wanted to log was the webpack config so I can diagnose and customize it. The terminal buffer has been cleared even after stopping poi.

**Comment by mgutz** [comment]
i had old version

**Comment by ksmithut** [comment]
@mgutz What was the option to not clear the terminal?
