### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by RokkerRuslan** [egoist/poi#272]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

> npm run dev  # works correctly

> npm run build print that error:
> [31mUglifyJS error: unexpected ES6+ code in module "ts-loader??ref--18-0!.", full error message:
> 
> client.915f8ca4.js from UglifyJs
> Unexpected token: operator (>) [./node_modules/ts-loader??ref--18-0!./static_src/index.ts:12,0][client.915f8ca4.js:79,15]
> 
>  TIP  To fix this, try adding "ts-loader??ref--18-0!." to "transformModules" option, eg:
> 
> // poi.config.js
> module.exports = {
>   transformModules: ['ts-loader??ref--18-0!.'],
>   // ...other config
> }
> 
>  FAIL  Compiled with errors!
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! static_src@0.1.0 build: `poi build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the static_src@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/r/.npm/_logs/2017-10-30T17_59_37_659Z-debug.log

package.json

>   "dependencies": {
>     "axios": "^0.17.0",
>     "buefy": "^0.5.4",
>     "bulma": "^0.6.0",
>     "font-awesome": "^4.7.0",
>     "node-sass": "^4.5.3",
>     "normalize.css": "^7.0.0",
>     "object-assign": "^4.1.1",
>     "promise-polyfill": "^6.0.2",
>     "sass-loader": "^6.0.6",
>     "vue-class-component": "^6.0.0",
>     "vue-router": "^3.0.1"
>   },
>   "devDependencies": {
>     "typescript": "^2.5.3",
>     "poi-preset-typescript": "^9.0.2",
>     "poi": "^9.0.0",
>     "poi-preset-bundle-report": "^2.0.0",
>     "serve": "^6.1.0"
>   }

**What is the expected behavior?**

Successful build.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by mblarsen** [comment]
@RokkerRuslan how does your `npm run dev` and `npm run build` scripts in `package.json` look like?

Also do you have a `poi.config.js` file?

**Comment by egoist** [comment]
hmm how are your using poi-preset-typescript? please provide a minimal repro 😄

**Comment by RokkerRuslan** [comment]
Yes :)
It is poi.config.js:

> const path = require('path')
> const pkg = require('./package')
> 
> module.exports = {
>   entry: [
>     'static_src/polyfills.js',
>     'static_src/index.ts'
>   ],
>   html: {
>     template: path.join(__dirname, 'index.ejs')
>   },
>   presets: [
>     require('poi-preset-bundle-report')(),
>     require('poi-preset-typescript')(),
>   ]
> }

**Comment by egoist** [comment]
your tsconfig.json? you should configure it to compile app to es5

**Comment by RokkerRuslan** [comment]
Yes, it is:

> {
>   "compilerOptions": {
>     "target": "es2017",
>     "strict": true,
>     "module": "es2015",
>     "moduleResolution": "node",
>     "allowJs": true,
>     "experimentalDecorators": true
>   }
> }
>

**Comment by egoist** [comment]
then set target to `es5`

**Comment by RokkerRuslan** [comment]
But I use es6 syntax in source code, and set target to `es5` produce this errors:

> [37m(54,43): error TS2339: Property 'entries' does not exist on type 'ObjectConstructor'.
> (60,43): error TS2339: Property 'entries' does not exist on type 'ObjectConstructor'.
> (72,43): error TS2339: Property 'entries' does not exist on type 'ObjectConstructor'.
> (93,16): error TS2693: 'Promise' only refers to a type, but is being used as a value here.

**Comment by gluons** [comment]
It should be great if you use `Code Block` instead of block quote.

```javascript
let msg = "It's easier to read.";
```

**Comment by gluons** [comment]
@RokkerRuslan Add this compiler options into your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "lib": [
      "es2015",
      "es2017"
    ]
  }
}
```

**Comment by RokkerRuslan** [comment]
For message Iam sorry. I will use `code block`!
Working for me:
`    "lib": [
      "es5",
      "dom",
      "es2015",
      "es2017"
    ]`

**Comment by RokkerRuslan** [comment]
Thanks! But I have a question. What does mean that error? And why I cannot use `target es2017`?

**Comment by gluons** [comment]
```
UglifyJS error: unexpected ES6+ code in module "ts-loader??ref--18-0!.", full error message:

client.915f8ca4.js from UglifyJs
Unexpected token: operator (>) [./node_modules/ts-loader??ref--18-0!./static_src/index.ts:12,0][client.915f8ca4.js:79,15]
```

[UglifyJS](https://github.com/mishoo/UglifyJS2) does not yet support ES6 and above now.  
> `uglify-js` only supports ECMAScript 5 (ES5).

Maybe you're using some ES6+ syntax.
