### ISSUE TITLE
The postcss plugin can not be loaded correctly

### ISSUE THREAD

**Issue by HcySunYang** [egoist/poi#276]
**Do you want to request a *feature* or report a *bug*?**
This is a bug

**What is the current behavior?**
I got the following error:
```
> Running in development mode
> Using external Poi config file
> location: "~/meituan/test/test-poi/poi.config.js"

Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-adaptive'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at load (/Users/huochunyang/gitrope/poi/packages/poi/node_modules/postcss-load-plugins/lib/plugins.js:52:18)
    at /Users/huochunyang/gitrope/poi/packages/poi/node_modules/postcss-load-plugins/lib/plugins.js:66:18
    at Array.forEach (native)
    at plugins (/Users/huochunyang/gitrope/poi/packages/poi/node_modules/postcss-load-plugins/lib/plugins.js:65:8)
    at /Users/huochunyang/gitrope/poi/packages/poi/node_modules/postcss-load-config/index.js:64:18

 FAIL  Failed to start!
```
**If the current behavior is a bug, please provide the steps to reproduce.**
First I execute the `npm install --save-dev postcss-adaptive` command to install the postcss plugin.
Then I modify the package.json file and add the postcss related configuration:
```
{
  "name": "test-poi",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "postcss-adaptive": "^0.4.0"
  },
  "postcss": {
    "plugins": {
      "postcss-adaptive": {
        "remUnit": 75
      }
    }
  }
}
```
So get the above error.

**What is the expected behavior?**
No error and can load postcss plugin

**If this is a feature request, what is the motivation or use case for changing the behavior?**
No, it is a bug report

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

poi 9.4.4
Node.js 6.9.1
Mac OS

**Comment by egoist** [comment]
this is actually a bug from postcss-load-plugins https://github.com/michael-ciniawsky/postcss-load-plugins/issues/42

work around: install poi locally in your project

**Comment by HcySunYang** [comment]
Okay thank you
