### ISSUE TITLE
Generate static website

### ISSUE THREAD

**Issue by egoist** [egoist/poi#279]
## The problem

You know, what Poi generates is an SPA, there's no contents but `<div id="app"></div>` before scripts and your data are ready.

To make your website have greater performance and SEO friendly, you can either pre-render it or generate static website.

## The solution

SSR is out of the scope for this project (it is also possible though), but I saw some other solutions that might apply to Poi as well:

- [react-static](https://github.com/nozzle/react-static)
- [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin)
- `ream generate` `nuxt generate` `next export`
## How the API would look like

Let's take Vue as example, it should be similar for React, this is actually inspired by react-static and [ream](https://github.com/ream/ream):

```js
// poi.config.js
const routes = async () => {
  const users = await getUserNamesFromSomeWhere()
  return [
    { 
      path: '/', 
      component: 'pages/Home.vue', 
      async getData() {
        const list = await getSomeList()
        return { list }
      } 
    },
    { 
      path: '/user',
      component: 'pages/User.vue',
      children: users.map(username => ({
        path: username,
        component: 'pages/UserProfile.vue',
        async getData() {
          return {
            user: await getUserProfile()
          }
        }
      }))
    }
  ]
}


module.exports = {
  presets: [
    require('poi-preset-vue-static')({
      routes
    })
  ]
}
```

## What does this preset actually do

It generates HTML files for all routes, in this case it will generate `index.html` and `user/userA/index.html`, `user/userB/index.html` (using vue-server-renderer).

Note the `getData` option, we save the returned data to `dist/.route_data/{route_id}.json`, it will be used on the client-side.

---

This is just a proposal, your feedback is more than welcome :)

**Comment by raneio** [comment]
Wow, this is just what I need.

**Comment by darcnite3000** [comment]
I've put together and published a preset wrapping [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin/tree/v3) as [poi-preset-prerender-spa](https://github.com/darcnite3000/poi-preset-prerender-spa)

It's not the best, but prerender-spa-plugin is made by a member of the Vue team, so my code is sitting on something stable at least.

Biggest issue with my preset would be regarding poi configs with a `homepage`, and I'm not sure how to resolve that

**Comment by egoist** [comment]
So here it is: https://github.com/egoist/poi/blob/master/docs/guides/vue-static.md

**Comment by darcnite3000** [comment]
also note: the `poi build` command doesn't clean the dist before building anymore causing a buildup of hashed files.

**Comment by egoist** [comment]
@darcnite3000 

> and noticed that the html was missing the data from the html-webpack-plugin, that is the title, description et al.

Yep, `vue-static` does not use `html-webpack-plugin` at all

> I'm assuming you need to install vue-meta to make this work because diving into the info, you don't use the given html to build but a hardcoded one from the plugin.

Yes, vue-meta

> also note: the poi build command doesn't clean the dist before building anymore causing a buildup of hashed files.

Fixed.

---

I just migrate a project to using this plugin:

https://github.com/egoist/vue-land/commit/3000b90c36eb692124e891e06740e9ebf80d1160

**Comment by egoist** [comment]
@darcnite3000 now `vue-static` plugins uses the `vue-meta` by default

https://poi.js.org/plugins/vue-static.html#manipulating-head
