### ISSUE TITLE
Drop node 6 support

### ISSUE THREAD

**Issue by egoist** [egoist/poi#283]
Can we do this already since node 8 is the new LTS? 😄

**Comment by mblarsen** [comment]
What does Webpack support at min?

**Comment by egoist** [comment]
node 4 😅

**Comment by mblarsen** [comment]
In my opinion I don't think that users that start using Poi will still be on Node 6. 

Node versions on VPSs are either really up to date or really old (so you would have to upgrade node anyway).

**Comment by mblarsen** [comment]
Btw I just recalled, I ran into some issue with 8 a few days ago. Solved by 7 and 9 but not latest 8 — if I could just remember what it was.

**Comment by egoist** [comment]
https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0

Nuxt.js now requires node^8, and so for vue-cli 3.0 soon 😄

**Comment by egoist** [comment]
This is done by https://github.com/egoist/poi/commit/cf05fe4b222cabddabee48e56feb61306d6a0191
