### ISSUE TITLE
Add 'no-progress' option to ignore progress plugin

### ISSUE THREAD

**Issue by QingWei-Li** [egoist/poi#284]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

The progress bar is always displayed in the production mode, it is annoying in the CI log.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is the motivation or use case for changing the behavior?**

We can provide the `no-progress` option to ignore progress plugin.

```shell
poi build --no-progress
```

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

I can submit a PR for this feature. 😉

**Comment by egoist** [comment]
that's nice to have, and well we can actually disable progress by default when `process.env.CI` is true
