### ISSUE TITLE
No poi command if installed locally

### ISSUE THREAD

**Issue by yjchen** [egoist/poi#286]
If poi is installed locally (yarn add poi --dev), there is no poi command. Steps to reproduce:

1. mkdir demo_poi
2. cd demo_poi
3. yarn add poi --dev
4. poi

The only way to run poi is to use node:

    node ./node_modules/poi/bin/cli.js

It is different from the guide.

**Comment by mblarsen** [comment]
When you install poi (or any other CLI tool) locally there is no command available since your local `node_modules` directory is not in your environment path.

If you have `npm` installed you can run:

```
npx poi <poi params>
```
(note it is `npx` not `npm`)

or you can add a scripts section to package.json:

```
  "scripts": {
    "poi": "poi"
  }
```

and then you can:

```
yarn poi <poi params>
```

**Comment by egoist** [comment]
@mblarsen I think there's no need to add `poi` to `scripts` to use `yarn poi` 😄 it works exact the same way as `npx`

**Comment by mblarsen** [comment]
Great, even easier :D — but the point is still the same for local installs no?

**Comment by mblarsen** [comment]
<3 yarn

**Comment by yjchen** [comment]
Then this issue can be closed with a mention of using 'yarn poi' instead of 'poi' for local installation. Thanks !!

**Comment by egoist** [comment]
A complete guide:

- Installed globally:
  - You can directly run the `poi` command
- Installed locally:
  - In your terminal, run `npx poi` or `yarn poi`

---

You are recommended to use `poi` command in npm scripts like:

```json
{
  "scripts": {
    "dev": "poi",
    "build": "poi build"
  }
}
```

By running `npm run dev` or `yarn dev` it will find fisrt `poi` command in the `$PATH`, and `./node_modules/.bin` will be automatically prepended to `$PATH`. See https://docs.npmjs.com/misc/scripts
