### ISSUE TITLE
Ability to modify the file loader

### ISSUE THREAD

**Issue by jigarzon** [egoist/poi#287]
Sorry for asking here, I know this is supported by poi but i could not find the way to modify the inherited webpack config in order to add:
```  
publicPath: 'http://myassetsite.com/',
useRelativePath: true,
```
To the default `file-loader`.
I tryied this:
```
  extendWebpack(config) {
    config.merge({
      'file-loader': {
        publicPath: 'http://myassetsite.com/',
        useRelativePath: true,
      }
    })
  },
```
But it didnt work.
Suggest: it would be great to have a forum/gitter.
Thanks!

**Comment by mblarsen** [comment]
@jigarzon there is a forum here https://discord.gg/qXPR5M

**Comment by egoist** [comment]
For `publicPath`, try [homepage](https://poi.js.org/#/options?id=homepage) option, or manually:

```js
extendWebpack(config) {
  config.output.publicPath('/xxx')
},

// or
webpack(config) {
  config.output.publicPath = '/xxx'
  return config
}
```

I don't know what is `useRelativePath` 😅

**Comment by jigarzon** [comment]
Thanks both of you. The `homepage` option did the job.
