### ISSUE TITLE
Ability to build in dev mode

### ISSUE THREAD

**Issue by jigarzon** [egoist/poi#288]
**Do you want to request a *feature* or report a *bug*?**
*Feature*
**What is the current behavior?**
Currently we have fixed this:
```
poi # development
poi build # production
poi test # test
poi watch # development
```
**What is the expected behavior?**
To allow execute build and have `process.env.NODE_ENV == 'development'`.
**If this is a feature request, what is the motivation or use case for changing the behavior?**
 This is useful in this case: I have some environment configuration that work on production. But, what if I want to test a build on my local environment?

**Comment by egoist** [comment]
If you only want `process.env.NODE_ENV == 'development'` you can already do this by:

```bash
poi build --env.NODE_ENV development
```

Or set it in config file if you prefer that way.

**Comment by egoist** [comment]
Wow it's been a year 😅 Now running `poi` alone will actually build the entry files in dev mode.

Check out the new docs if you are still using Poi :P: https://poi.js.org/guide/cli-usages.html#modes
