### ISSUE TITLE
Extract mutiple css from .vue <style> tag

### ISSUE THREAD

**Issue by StarXY** [egoist/poi#292]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
Styles are inserted into html's <style> tag. It seems like 'development' behavior
**If the current behavior is a bug, please provide the steps to reproduce.**

poi.config.js
`const env = (options.env && options.env.NODE_ENV) || 'development';`
` process.env.NODE_ENV = env;`
` return {`
`   extractCSS: env === 'production',`
` };`

in a .vue file
`<style src="path/to/css" lang="postcss">`
run command
`npm run poi build -- --env.NODE_ENV=\"production\"`

**What is the expected behavior?**
output single css file
**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Firefox: v58,
Chrome: v62
Node.js: v8.2
poi: v9.5.2
os: win7 sp1

**Comment by StarXY** [comment]
However,
the behavior is expected correctly If I write
`import 'path/to/css';`

**Comment by mblarsen** [comment]
`import 'path/to/css';` would be the way to import css.

`<style>` is not supposed to reference another file afaik—have not seen it used for that before. 

Also you should leave out the postcss-lang part. PostCSS should kick in on what ever is output to it.

**Comment by StarXY** [comment]
@mblarsen 
Hi, 
`vue-loader` introduces that format.
reference: [https://github.com/vuejs/vue-loader](url)

**Comment by egoist** [comment]
In your code:

```js
const env = (options.env && options.env.NODE_ENV) || 'development';
```

`env` is always `development`, so `extractCSS` is always `false` here

**Comment by mblarsen** [comment]
@StarXY I'm only referring to your use of `src=` in the style tag. Can you link to the docs where this described?

**Comment by egoist** [comment]
@mblarsen yeah that's supported, all the tags in SFC support `src`

**Comment by mblarsen** [comment]
I wasn't aware, can you hit me with a link to the docs?

Anyway, it is kind of an anti-pattern for `.vue` files.

**Comment by egoist** [comment]
@mblarsen https://vue-loader.vuejs.org/en/start/spec.html#src-imports

**Comment by StarXY** [comment]
@egoist 
Hi, 
But I run with this command `npm run poi build -- --analyze --env.NODE_ENV=\"production\"`,
I even check process.env.NODE_ENV in index.js, it output 'production'

**Comment by StarXY** [comment]
@egoist 
sorry, I just find that if deploying with `python -m SimpleHTTPServer 9000`,
It would automatically insert css in <style> tag.
Thanks

**Comment by egoist** [comment]
@StarXY so is it some browser cache issue? I sometimes forget to clear registered service worker too 😅

**Comment by StarXY** [comment]
@egoist 
Hi,
repository: [https://github.com/StarXY/poi-test](url)

**Comment by egoist** [comment]
@StarXY here https://github.com/StarXY/poi-test/blob/master/package.json#L13

it should actually be:

```diff
- "poi": "./node_modules/.bin/poi",
- "build": "npm run poi build -- --env.NODE_ENV=\"production\""
+ "build": "poi build --env.NODE_ENV=\"production\""
```

then `npm run build`

**Comment by egoist** [comment]
And I'm not sure why you want `--env.NODE_ENV=\"production\"`, `NODE_ENV` is set to corresponding value by default.

**Comment by StarXY** [comment]
@egoist 
Hi, 
[https://github.com/StarXY/poi-test/commit/ef8d925366ece85ea8f89654bd82f085332d9d36#diff-b9cfc7f2cdf78a7f4b91a753d10865a2](url)
**The Problem still exists** ? The reason why i want `--env.NODE_ENV=\"production\"` is just want to ensure that process.env.NODE_ENV is set correctly

**Comment by StarXY** [comment]
Should I delete `lang="postcss"` in <style> tag, I find that if I delete it, the problem get resolved?

**Comment by egoist** [comment]
Ah indeed, we didn't add support for `lang="postcss"` since postcss is always used.
