### ISSUE TITLE
Use Storybook poi-preset-react

### ISSUE THREAD

**Issue by marvinroger** [egoist/poi#293]
Hi @egoist!

My current app uses the `poi-preset-react`. I would like to use Storybook with the webpack config of poi. I saw there was a `poi-preset-storybook`, but how to use it along our existing stack, given the fact that we want the `entry` to still be our app?

Thanks!

**Comment by egoist** [comment]
Basically your storybook app and your actual app are two independent ones, so you can have another `poi.config.js` for your storybook app, eg. populate it at `.storybook/poi.config.js` and add an npm script:

```js
{
  "scripts": {
      "storybook": "poi --config .storybook/poi.config.js"
   }
}
```

Here's the example for Vue.js but React could share the idea: https://github.com/poi-examples/storybook-vue-example

**Comment by marvinroger** [comment]
And don't forget to add `jsx: 'react'`. It works great, thanks!

**Comment by egoist** [comment]
you dont need that option while using poi-preset-react 😄

**Comment by marvinroger** [comment]
Oh, when I tried to use both presets, the compilation failed. But setting
‘jsx’ did work.

**Comment by egoist** [comment]
hmm that's unexpected since we already set `jsx` to `react` here if you're not using a custom babel config:

https://github.com/egoist/poi/blob/f581a5be5af8c24f5678656e14c55450fbd82fea/packages/poi-preset-react/index.js#L13

**Comment by marvinroger** [comment]
I misspoke.

Given the following config:

```js
module.exports = {
  entry: ['.storybook/config.js', '.storybook/addons.js'],
  presets: [
    require('poi-preset-storybook')()
  ]
}
```

It does compile, but obviously, I get an `h is not defined` error in the component view of Storybook.

```js
module.exports = {
  entry: ['.storybook/config.js', '.storybook/addons.js'],
  presets: [
    require('poi-preset-storybook')(),
    require('poi-preset-react')()
  ]
}
```

Does not compile : `Error: Currently only client entry is supported`

```js
module.exports = {
  entry: ['.storybook/config.js', '.storybook/addons.js'],
  presets: [
    require('poi-preset-react')(),
    require('poi-preset-storybook')()
  ]
}
```

Does compile, but the component view of Storybook stays empty (e.g. the stories are shown on the left side, but nothing on the right side appears).

```js
module.exports = {
  entry: ['.storybook/config.js', '.storybook/addons.js'],
  jsx: 'react',
  presets: [
    require('poi-preset-storybook')()
  ]
}
```

Works as intended.

**Comment by egoist** [comment]
Fixed in latest version of poi-preset-storybook, now the order matters:

```js
module.exports = {
  presets: [
    // react then storybook
    require('poi-preset-react')(),
    require('poi-preset-storybook')()
  ]
}

```

**Comment by marvinroger** [comment]
I still get nothing on the right side of Storybook. 😕

**Comment by egoist** [comment]
@marvinroger check out the example I just made here: https://github.com/poi-examples/storybook-react-example

**Comment by marvinroger** [comment]
I have the *exact* same thing, but the right screen is blank. Removing the react preset and adding `jsx: 'react'` fixes that

**Comment by egoist** [comment]
then there must be something different 😄

**Comment by marvinroger** [comment]
If it works for you, definitely, yes. Are you using yarn? I do. If you don't, maybe our versions don't match.

**Comment by weirongxu** [comment]
I have same issue on Windows 10

**Comment by egoist** [comment]
@weirongxu does https://github.com/poi-examples/storybook-react-example work for you?

**Comment by weirongxu** [comment]
I use the https://github.com/poi-examples/storybook-react-example on Windows, storybook preview screen was empty.
BTW, It's work for me on Linux.

**Comment by marvinroger** [comment]
Window 10 for me also! Great starting point.

**Comment by kfird214** [comment]
https://github.com/poi-examples/storybook-react-example not working for me, on win 10.

**Comment by egoist** [comment]
@kfird214 you may check out https://github.com/egoist/poi/tree/master/packages/plugin-storybook instead, those examples under poi-examples org are kinda outdated.

**Comment by kfird214** [comment]
thanks @egoist but it looks like it should work but as i mentioned the is not `@poi/plugin-react`.
there is `poi-plugin-react` which didn't work for me, probably because its incompatible with poi 10.
i the example you shared the is a use of it:
```javascript
// poi.config.js
module.exports = {
  entry: '.storybook/config.js',
  plugins: [
    require('@poi/plugin-react')(), // <- ?
    require('@poi/plugin-storybook')()
  ]
}
```

**Comment by egoist** [comment]
OK, I forgot about that, now you don't need a plugin for React, https://poi.js.org/guide/hot-reloading.html#react

Will update the README.md later

**Comment by egoist** [comment]
@kfird214 I've updated the react example: https://github.com/poi-examples/storybook-react-example/commit/9a2aa125fca8f79e81e90669163e3961678b6443 should work now
