### ISSUE TITLE
Errors when using devServer proxy

### ISSUE THREAD

**Issue by Rayraegah** [egoist/poi#294]
**Do you want to request a *feature* or report a *bug*?**
Don't know, bug maybe?

**What is the current behavior?**
CROS error or connection refused 

**If the current behavior is a bug, please provide the steps to reproduce.**
 * Add devServer proxy to config, set target to a live server e.g. api.google.com
 * use fetch() in app
 * CROS error in console or connection refused

**[EDIT]**

This web pack [devServer config](https://webpack.js.org/configuration/dev-server/#devserver-proxy) (1) works

```
    proxy: [
      {
        context: ["/auth", "/api"],
        target: "https://api.myserver.io",
        secure: false
      }
    ]
```

While this one (2) does not

```
    proxy: {
      "/api": {
        target: "https://api.myserver.io",
        secure: false
      }
    }
```

**What is the expected behavior?**
 * Should work like create-react-app

**Comment by egoist** [comment]
Can you provide a repo? I've got my hands full and it could dramatically reduce the time for me to fix your problem 😄

**Comment by Rayraegah** [comment]
Sure, give me a few minutes :D

**Comment by Rayraegah** [comment]
Actually, the CROS error is not the actual problem. Perhaps I should change the issue:

This web pack devServer config (1) works

```
    proxy: [
      {
        context: ["/auth", "/api"],
        target: "https://api.myserver.io",
        secure: false
      }
    ]
```

While this one (2) does not

```
    proxy: {
      "/api": {
        target: "https://api.myserver.io",
        secure: false
      }
    }
```

Since (2) does not apply proxy, I get connectionRefused and CROS errors (for fetch req with full URL).

I believe this would be a web pack issue not poi?

**Comment by egoist** [comment]
hmm yeah `proxy` is actually directly feed to `webpack-dev-server`

**Comment by Rayraegah** [comment]
I'll take it up with Webpack, closing this.
