### ISSUE TITLE
Update to uglifyjs-webpack-plugin

### ISSUE THREAD

**Issue by egoist** [egoist/poi#296]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin

> webpack =< v3.0.0 currently contains v0.4.6 of this plugin under webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack.optimize.UglifyJsPlugin is scheduled for webpack v4.0.0

**Comment by emzero** [comment]
How can I make use of this plugin in poi?

**Comment by egoist** [comment]
@emzero  https://poi.js.org/#/home?id=webpack

see https://github.com/edus44/poi-preset-uglifyjs also
