### ISSUE TITLE
homepage key in package.json is ignored

### ISSUE THREAD

**Issue by maggo** [egoist/poi#299]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When adding a `homepage` key in package.json the path it not prepended to the scripts in the built html.

**If the current behavior is a bug, please provide the steps to reproduce.**

See https://github.com/maggo/dialog-polyfill-dynamic
`homepage` is set to `/dialog-polyfill-dynamic/`
Run `$ poi build` (or check committed html)
JS paths in `docs/index.html` are output as `/*.js` instead of `/dialog-polyfill-dynamic/*.js`

**What is the expected behavior?**

The path defined in the `homepage` key should be prepended to the generated script tags in index.html as described in https://poi.js.org/#/recipes/deployment

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

poi 9.5.11

**Comment by egoist** [comment]
@maggo ah that recipe is outdated, you need to set `homepage` in your poi config since I find many people set `pkg.homepage` to their repo address, which would break the website.

**Comment by egoist** [comment]
I have updated the doc.

**Comment by maggo** [comment]
Thanks for the info!
