### ISSUE TITLE
Add path options to poi-preset-transform-test-files

### ISSUE THREAD

**Issue by LucienLee** [egoist/poi#301]
**Do you want to request a *feature* or report a *bug*?**
Feature

**If this is a feature request, what is the motivation or use case for changing the behavior?**
Now, `poi-preset-transform-test-files` transform all test files as one `output_test/test.js` file.
I suggest that open options to set path enable to bundle separate test files by setting webpack multiple entry rather than hardcode as test. 

https://github.com/egoist/poi/blob/master/packages/poi-preset-transform-test-files/index.js#L24

The example scenario is that Jest suggests creating test file in `__test__` next to source code. Then, it generates snapshot under `src/__snapshot__...`. Because we can't assign the place of snapshot [for now](https://github.com/facebook/jest/issues/1650), so our snapshot would be next to bundled test code (`output_test/__snapshot__/...`). That's weird we put snapshot files under temporary bundled directory and add it to version control. Although I could set rule in `.gitignore` like the following, I still want the power to change the path.

```
output_test
!output_test/__snapshot__/
```

Instead of the previous workaround, my ideal solution is bundling test code next to source as `*.test.transform.js`. We then add this pattern to `.gitignore` and test with `Jest *.test.transform.js`.

I would like to discuss whether to add this feature and if we do, what's the option specs. Then, I can make PR about this.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
- Node v8.9
- Poi v9.5.10

**Comment by LucienLee** [comment]
One possible proposal is:
`options.inPlaceTransform` (Boolean|String) default is false, which works as current plugin. 
If it is set as true, it would transfrom test files in place as [name].transform.js. Further more, it could be set as webpack filename [pattern](https://webpack.js.org/configuration/output/#output-filename) to generate individual test files.

**Comment by egoist** [comment]
`inPlaceTransform` looks good to me, and feels like it should be the default behavior?

we can actually transform all `dir/[name].test.js` to `dir/[name].test.transformed.js` and allow use to use `outputDir` option to use another directory for transformed files.

**Comment by LucienLee** [comment]
Okay, it sounds we make the agreement. I'll make a PR for that.

**Comment by egoist** [comment]
@LucienLee I've actually started one https://github.com/egoist/poi/pull/308 😄  but help is welcome

ref: https://github.com/avajs/ava/blob/master/docs/recipes/precompiling-with-webpack.md

**Comment by LucienLee** [comment]
Oops, It looks like what I did yesterday. 

https://github.com/LucienLee/poi/tree/support-in-place-transform/packages/poi-preset-transform-test-files

**Comment by egoist** [comment]
@LucienLee You can create a PR then I'll close mine.

**Comment by LucienLee** [comment]
@egoist I have made a version on #309.😀

**Comment by egoist** [comment]
A new release `poi-preset-transform-test-files@10.0.0` is now available for this.
