### ISSUE TITLE
Tailwincss with purgecss configuration

### ISSUE THREAD

**Issue by ansarizafar** [egoist/poi#303]
How  Tailwindcss with purgecss can be configured with poi.

Reference: https://tailwindcss.com/docs/controlling-file-size, 
https://medium.com/@AndrewDelPrete/using-purifycss-to-remove-unused-tailwind-css-classes-173b3ee8ee01

**Comment by egoist** [comment]
I think it's just similar to PurifyCSS? I will update https://github.com/poi-examples/tailwindcss-example later and PRs welcome.

**Comment by ansarizafar** [comment]
@egoist  Any update on this issue? I have tried this configuration but its not working.
````
const glob = require('glob')
const path = require("path");
const PurgecssPlugin = require("purgecss-webpack-plugin");

/**
 * Custom PurgeCSS Extractor
 * https://github.com/FullHuman/purgecss
 * https://github.com/FullHuman/purgecss-webpack-plugin
 */
class TailwindExtractor {
    static extract(content) {
      return content.match(/[A-z0-9-:\/]+/g);
    }
  }
 
  const PATHS = {
    src: path.join(__dirname, 'src')
  }

module.exports = {
  entry: './src/index.js', 
  extendWebpack(config) {
      // Disable progress bar while building
     // config.plugins.delete('progress-bar')
     config
  .plugin('purge')
  .init(() => new PurgecssPlugin({
    paths:  glob.sync(`${PATHS.src}/*.js`),
    extractors: [
      {
        extractor: TailwindExtractor,
        extensions: ["html", "js"]
      }
    ]
  }));
  
    }
  }
````

**Comment by gilesbutler** [comment]
Hey @ansarizafar,

It might be easier to use the [PostCSS](https://www.purgecss.com/with-postcss) plugin. I struggled trying to get the Webpack setup working too then tried it with PostCSS and it worked first time.

Just add this to your `postcss.config.js`...
```
const tailwindcss = require("tailwindcss");
const purgecss = require("@fullhuman/postcss-purgecss");

module.exports = {
  plugins: [
    tailwindcss("./tailwind.js"),
    purgecss({
      content: ["./**/*.html"]
    })
  ]
};
```

**Comment by egoist** [comment]
I'm closing this. btw Tailwind now has builtin purgecss supporr!
