### ISSUE TITLE
poi-preset-karma should enable sourcemaps for test files by default

### ISSUE THREAD

**Issue by klarkc** [egoist/poi#304]
https://github.com/klarkc/sandbox-component

**Do you want to request a *feature* or report a *bug*?**

It's a new feature probably.

**What is the current behavior?**

The test will fail but the reported code line (34 here) is incorrect

**If the current behavior is a bug, please provide the steps to reproduce.**

run `$ poi test`.

**What is the expected behavior?**

Show the right test code line

**If this is a feature request, what is the motivation or use case for changing the behavior?**

The tests should show to the developer the real source of the error not the compiled, it's too hard to search and find errors in built files.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

In my machine node is v8.9.1, the poi version is 9.6.0

**Comment by egoist** [comment]
It's fixed in `poi-preset-karma@9.2.3`
