### ISSUE TITLE
Enable compilation of webfonts using webfonts-loader and webfonts-generator

### ISSUE THREAD

**Issue by padcom** [egoist/poi#305]
**Do you want to request a *feature* or report a *bug*?**

This is a feature request

**What is the current behavior?**

Webfonts need to be manually compiled outside of the default process.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

All modules ending with .font.js should be processed by webfonts-loader (https://www.npmjs.com/package/webfonts-loader), the generated font should be available as an external resource loaded by css generated by the webfonts-loader.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

In most of modern projects people use webfonts as means to include custom icons. This is a good practice as it allows to minimize the number of files that need to be downloaded thus speeding things up when loading the page.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
> Although if it will be too long then at least a preset to enable this feature would be nice.

Yeah you can make a preset out of it.

**Comment by padcom** [comment]
What do you mean?

**Comment by egoist** [comment]
I mean a preset would be nice, PR is welcome for that.

**Comment by padcom** [comment]
I'm working on it :)

2017-12-20 16:41 GMT+01:00 EGOIST <notifications@github.com>:
