### ISSUE TITLE
Document vue usage

### ISSUE THREAD

**Issue by joma74** [egoist/poi#311]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build. ...

(found in <Root>)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. yarn install --dev poi
2. yarn install --dev babel-preset-poi
3. yarn install --dev vue-class-component
4. make first vue component with template section
5. make a $cwd/poi.config.js
```
module.exports = {
    html: {
        template: "./src/index.ejs",
    },
    presets: [
        require("babel-preset-poi")
    ]
}
```
6. run poi

**What is the expected behavior?**
No warn, displays component.

Update docs what to install or configure to run vue component.

Workaround: Found https://github.com/egoist/poi/issues/73. So installed vue-loader and vue-template-compiler and vue(just in case). Was still not working with mentioned Warn. Then found templateCompiler option in poi.config.js. Configured
```
...
templateCompiler: true
...
```
Then vue happy :)

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
poi 9.6.1
babel-preset-poi 1.1.2
VSCode 1.19.1
node 8.1.1
Ubuntu

**Comment by egoist** [comment]
I think it's already well documented on vuejs.org (https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only) and the error message is very clear too.

btw here the `presets` is for poi presets not babel presets:

```js
module.exports = {
    html: {
        template: "./src/index.ejs",
    },
    presets: [
        require("babel-preset-poi")
    ]
}
```
