### ISSUE TITLE
Support for JSX fragment syntax

### ISSUE THREAD

**Issue by marvinroger** [egoist/poi#312]
**Do you want to request a *feature* or report a *bug*?**

A feature: JSX fragment syntax support (see https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)

**What is the current behavior?**

Using the new JSX fragment syntax:

```javascript
<>
      Some text.
      <h2>A heading</h2>
      More text.
      <h2>Another heading</h2>
      Even more text.
</>
```

Fails with `SyntaxError: Unexpected token`

**What is the expected behavior?**

In React, this desugars to a `<React.Fragment/>` element.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

It allows use to use a shorter syntax for the fragment feature of React, which allows to return a list of children without having to wrap it in `span` or `div`.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Latest Poi version.

**Comment by egoist** [comment]
It's only supported by babel 7 which is still in beta 😅

**Comment by marvinroger** [comment]
That's what I thought. It's already the 11th beta release of Babel 7, so hopefully it'll be released soon. 😉

**Comment by mblarsen** [comment]
Still not there yet, but beta 37 now
