### ISSUE TITLE
.poirc

### ISSUE THREAD

**Issue by dsommerville** [egoist/poi#314]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

Config file called ".poirc" not being detected?

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a file called ".poirc" in root of project with following contents:

{
  "entry": "./src/app.js",
  "port": 5000
}

Run poi, expecting config to be detected and used.

**What is the expected behavior?**

Config is detected and used to load app - feel like I'm missing something obvious...

**If this is a feature request, what is the motivation or use case for changing the behavior?**

n/a

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Version: 9.6.2

**Comment by egoist** [comment]
Oh sorry I forgot to update the docs about that, we no longer use cosmiconfig (which supports `.rc` file) to load config file, instead we now only load `poi.config.js` or `poi` field in `package.json`:

https://github.com/egoist/poi/blob/88b5082a0a3727a92b0dddf29605087326ef6a74/packages/poi-load-config/poi.js#L9

What's your use case of `.poirc`? I find it better to use `package.json` to reduce config files.

**Comment by dsommerville** [comment]
Thanks for the fast response.

No specific use-case - was simply working through the docs and couldn't get it to work.

I'm marginally in favour of isolating framework-specific configuration (separation of concerns), so would probably go with using **poi.config.js**, which seems to tie in well with webpack overrides, etc.

So - all good - was just querying.

**Comment by egoist** [comment]
Nice, I've also completely updated the docs.

**Comment by egoist** [comment]
We're supporting `.poirc` again in `v9.6.10`
