### ISSUE TITLE
HMR not working for React components

### ISSUE THREAD

**Issue by emzero** [egoist/poi#321]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

Creating a simple project with the react preset and a plain component breaks the HMR and does a full reload saying: `[HMR] Cannot apply update. Need to do a full reload!`

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `poi` in the following [gist project](https://gist.github.com/emzero/31337aa41d0885a47f57f4144e4a4eda) and then change something in `HelloMessage.jsx`

**What is the expected behavior?**
Should not do a full reload but a hot reload.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Any modern browser.
Node v8.9.0
Poi v9.6.4
Windows 7 x64

**Comment by emzero** [comment]
Actually it doesn't even work for the simple Vue example in the page.

**Comment by egoist** [comment]
check out https://github.com/egoist/poi/tree/master/examples/react

do you have something missing?

**Comment by egoist** [comment]
I saw yourgist, actually React hmr doesn't work out of box, you need to: https://github.com/egoist/poi/blob/2bfa00b0682482be7470dfb752c4ac03b6dcf0a9/examples/react/index.js#L6-L19

**Comment by emzero** [comment]
Yes, sorry, I just saw the react example!
