### ISSUE TITLE
use postcss plugins

### ISSUE THREAD

**Issue by Alx-l** [egoist/poi#323]
**Do you want to request a *feature* or report a *bug*?**
I'd like to report a bug

**What is the current behavior?**
First, thank you for this project, it's quite a time saver :)
So, my problem is, I can't use postcss plugins, except for 'autoprefixer' which is already incuded

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is a link to a [gist](https://gist.github.com/Alx-l/4917e8e50bc744d93f6ee4e363c0dcf4), so you can have an idea of what's going on.

I don't get any errrors, but my css is not affected by the plugin I declared.

Even if I add 'autoprefixer':
```
 postcss: {
    use: ['autoprefixer'],
    'autoprefixer': {
       browsers: [ 'last 10 versions' ]
    },
    append: true
  },

```
This won't be taken into account.

Whereas if I set options using:
```
module.exports = {
  autoprefixer: {
    browsers: [ 'last 10 versions' ]
  }
}
```

I can see that my css will be updated accordingly.

**What is the expected behavior?**
I also made a `postcss.config.js`file, but I can't manage to get poi to use it...
I tried to use it inside webpack loaders:
```
{
  test: /\.css$/,
  loader: 'postcss-loader',
  options: {
    config: {
      path: computePath('./postcss.config.js')
    }
  }
}
```
But this is never called.
**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
I'm using npm 5.5.1, poi 9.6.8 on a macOS Sierra

**Comment by egoist** [comment]
it's `plugins` not `use`, and I don't know what `append: true` does.

`poi` will load `postcss.config.js` in current working directory.

**Comment by Alx-l** [comment]
Alright, so I managed to get it working with this:

```
const autoprefixer = require('autoprefixer')
const otherPosstCssPlugin = require('foo')

module.exports = {
...
postcss: {
    plugins: [
      autoprefixer({
        browsers: [ 'last 10 versions' ]
      }),
      otherPosstCssPlugin({...})]
  }
...
}
```

Regarding the `append` thing, I actually picked that from your [doc](https://egoist.gitbooks.io/vbuild-handbook/content/options.html) ^^

Thanks for the quick answser 👍

**Comment by egoist** [comment]
Ah that doc is quite old 😅
