### ISSUE TITLE
Tree shaking not working?

### ISSUE THREAD

**Issue by emzero** [egoist/poi#327]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I started to notice in my project that code splitting doesn't seem to be working. Meaning, even if I import one function from a whole package, everything gets into the bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've made a simple example project using lodash to demonstrate this.
https://gist.github.com/emzero/c383255968607885327be361eff26cee

You can alternate between the imports in `index.js` and run the build script and you'll see that the whole lodash package is included in the bundle.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Node LTS 8.9.3
Poi 9.6.9
Windows 7 x64

**Comment by emzero** [comment]
Sorry, I've just realized that webpack does not do any tree shaking by itself. Instead it relies on plugins like UglifyJS.

I'll play around and see if I can add the plugin into the poi config.

**Comment by egoist** [comment]
Webpack does no tree shaking by itself, it just do not remove dead code. Instead you use a minifier for that. Currently the default uglifyjs plugin works already, so you don't have to add any other plugin to make tree shaking work.

**Comment by emzero** [comment]
But if the default `poi build` command runs the ugligyjs plugin then why the resulting bundle includes the whole lodash library instead of just the curry function in my example?

**Comment by egoist** [comment]
@emzero Are you using the [lodash-es](https://www.npmjs.com/package/lodash-es) package? tree shaking only works with es modules.

**Comment by emzero** [comment]
@egoist I've switched to lodash-es and the result is the same. The whole library gets into the vendor bundle.
![image](https://user-images.githubusercontent.com/412489/34485315-ac657948-efa8-11e7-845e-be01f36fb2d8.png)

**Comment by egoist** [comment]
Hmm seems it's related to this https://github.com/webpack/webpack/issues/1750

**Comment by emzero** [comment]
Bummer. It happens too with https://github.com/date-fns/date-fns

**Comment by emzero** [comment]
Bummer. It happens too with https://github.com/date-fns/date-fns
