### ISSUE TITLE
unnecessary slash "/" in the js path built with poi

### ISSUE THREAD

**Issue by eaststrong** [egoist/poi#344]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

After I execute the command of "poi build", the path of all js files has the first "/" in the created index.html in the dist folder.  Under the Windows OS, all js files can not be linked correctly.

e.g.

![default](https://user-images.githubusercontent.com/1632182/34708630-ff9f5788-f556-11e7-8a5d-f22edc9423aa.jpg)

**Comment by egoist** [comment]
The `dist` folder is meant to be served via an http server like [serve](https://www.npmjs.com/package/serve).
