### ISSUE TITLE
import other modules

### ISSUE THREAD

**Issue by eaststrong** [egoist/poi#346]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Can poi import other modules other than react or vue?
e.g.

import BootstrapVue from 'bootstrap-vue'

**Comment by egoist** [comment]
sure have you tried?

**Comment by eaststrong** [comment]
I failed.  It can not import it.

**Comment by egoist** [comment]
@eaststrong details? did you install it?

**Comment by eaststrong** [comment]
Sorry, I forgot to install them.
I thought poi would install all the imports automatically. ^_^

**Comment by egoist** [comment]
That's possible with https://github.com/webpack-contrib/npm-install-webpack-plugin but I'm afraid that it couldn't handle everything well.

btw you don't need to `ctrl+c` after installing a new dependency, a rebuild will automatically be triggered.
