### ISSUE TITLE
Why NODE_ENV is undefined on first start in poi.config.js?

### ISSUE THREAD

**Issue by RobinCodeX** [egoist/poi#349]
This code in `poi.config.js`:
```js
console.log('[DEBUG]', process.env.NODE_ENV)
if(process.env.NODE_ENV === 'development') {
  fs.writeFileSync('./...')
}
```
First start:
![image](https://user-images.githubusercontent.com/8408783/34843278-f70177de-f748-11e7-8f1f-5f8686664183.png)

Reload:
![image](https://user-images.githubusercontent.com/8408783/34843313-0a50cdbc-f749-11e7-8fc6-95e9493e765d.png)

I need to write files with different environment.

**Comment by egoist** [comment]
https://github.com/egoist/poi/blob/532b7b146d6016087a08a5ccae49d290c4596288/packages/poi/lib/index.js#L41-L45

So we need to move these line to cli before loading the config file 😅

btw you can use `options.mode` in config file too or manually set `NODE_ENV` as a workaround for now

**Comment by RobinCodeX** [comment]
😄 OK, thank you
