### ISSUE TITLE
How to import stylus/sass from the template?

### ISSUE THREAD

**Issue by nachocab** [egoist/poi#350]
I would like to apply a global stylesheet at the template head, but I'm not able to figure out how to go about it. My `poi.config.js` file looks like this:

    module.exports = (options, req) => ({
      html: {
        template: 'my_template.ejs'
      },
      mergeConfig: {
        module: {
          loaders: [
            {
              test: /\.styl$/,
              loaders: ['style-loader', 'css-loader', 'stylus-loader']
            }
          ]
        }
      }
    });

Assuming I have `./styles/main.styl`, what do I need to do so webpack picks it up?

I would like to do something like this:

    <!DOCTYPE html>
    <html>
    <head>
        <style src="./styles/styles.css"></style>
    </head>
    ...

**Comment by egoist** [comment]
you can't, that's not how webpack works.

btw there's no `mergeConfig` option and sass/stylus are supported by default so you don't need to add loader.

**Comment by nachocab** [comment]
Thanks! Do you have any pointers or workarounds I could try?

**Comment by egoist** [comment]
Just `import './style.scss` in your js file.

**Comment by egoist** [comment]
See https://github.com/egoist/poi/tree/master/examples/with-css

**Comment by nachocab** [comment]
So simple! Thank you, I was overthinking it!
