### ISSUE TITLE
poi preset for parallel/multicore build

### ISSUE THREAD

**Issue by DrSensor** [egoist/poi#356]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Webpack runs single-threaded

**If this is a feature request, what is the motivation or use case for changing the behavior?**
In case `poi` want to compete with `parcel`

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
https://github.com/trivago/parallel-webpack
https://github.com/amireh/happypack
https://survivejs.com/webpack/optimizing/performance/

**Comment by egoist** [comment]
It's available under `--parallel` flag in Poi 12.
