### ISSUE TITLE
NODE_ENV always set to development

### ISSUE THREAD

**Issue by gilesbutler** [egoist/poi#357]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `NODE_ENV` is always set to development

Running `poi build --env.NODE_ENV test` results in `console.log(process.env.NODE_ENV); #development`

Even running `NODE_ENV=test && poi build` has the same result `console.log(process.env.NODE_ENV); #development`

Poi config:
```
module.exports = {
  entry: "./src/index.js",
  html: {
    // `pkg` is the data from `package.json`
    // title: pkg.productName || pkg.name,
    // description: pkg.description,
    template: "src/index.ejs" // Defaults to $cwd/index.ejs if it exists, otherwise use built-in template
    // pkg: {} // All package.json data
  },
  presets: [
    require("poi-preset-react")(), // eslint-disable-line
    require("poi-preset-bundle-report")() // eslint-disable-line
  ]
};
```

**What is the expected behavior?**
Running `poi build --env.NODE_ENV test` should result in `console.log(process.env.NODE_ENV); #test`

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Poi: 9.6.12
Chrome: 63
Node: 8.9.3
OSX: 10.13.2

**Comment by gilesbutler** [comment]
Helpful  🙄

**Comment by gilesbutler** [comment]
Could you at least tell me why you closed this with no response please @egoist??

**Comment by egoist** [comment]
what do you mean by no response? it's closed by a commit...

**Comment by gilesbutler** [comment]
Arghhh I'm so sorry @egoist I didn't see that. I just thought it had been closed without a response. Poor form on my side 😖 and thank you for the fix 👍

**Comment by gilesbutler** [comment]
Hey @egoist,

Just an fyi, it looks like `NODE_ENV=test && poi` works but `poi  --env.NODE_ENV test` doesn't.

**Comment by egoist** [comment]
`--env.NODE_ENV` does only set `process.env.NODE_ENV` in your app code, not the node process.

**Comment by egoist** [comment]
btw, in which case you need to use `NODE_ENV=test && poi`?

**Comment by gilesbutler** [comment]
Yep looking to set it in the app code not the node process.

Our app relies on a config file which will pull in different configs based on the environment...
```
const isDev = process.env.NODE_ENV === "development";
const isProduction = process.env.NODE_ENV === "production";
const isTest = process.env.NODE_ENV === "test";

export { isDev, isProduction, isTest };
```
