### ISSUE TITLE
Can't disable build stats output through CLI

### ISSUE THREAD

**Issue by VitorLuizC** [egoist/poi#359]
**Do you want to request a *feature* or report a *bug*?**

I'm requesting a *feature*.

**What is the current behavior?**

I didn't find any setting to disable build stats output. I tried run build with `--silent`, `--quiet`, `--no-stats` and they also don't work, so I think there's no way to disable build stats output.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

A flag, like `--silent`, `--quiet` or other to disable build stats output.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

GitLab pipeline don't have memory enough to show all my project bundled files (+2000 files). And execute poi through a script wouldn't be cool.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by egoist** [comment]
Maybe add a `--displayStats` option to customize [`stats`](https://webpack.js.org/configuration/stats/#stats) for webpack

**Comment by egoist** [comment]
btw I think we can tweak it a bit to only output stats for `main` assets instead of all files.

**Comment by egoist** [comment]
No longer a problem in v12, only a success message is printed when executing in CI.
