### ISSUE TITLE
Default POI webpack configuration breaks 'vue-svg-loader'

### ISSUE THREAD

**Issue by fungl164** [egoist/poi#362]
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
When trying to load svg files via ```vue-svg-loader``` application logs an error to console claiming an invalid component.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install ```vue-svg-loader```
2. Follow instructions to load an svg file as a vue component

**Current Workaround**
Modify poi's ```create-config.js``` file to exclude svg default behavior or modify to suit your needs.

**Comment by fungl164** [comment]
To enable ```vue-svg-loader``` add the following to your ```poi.config.js```
```JS
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      loader: 'vue-svg-loader'
    })
    return config // <-- Important, must return it
  }
```
and remove the same rule in the default webpack config located at ```create-config.js```

**Comment by egoist** [comment]
This is actually not a bug, if a rule for specific type of file already exists, it's expected that you need to remove it first before adding your own rule. And that's how `webpack-chain` gets handy:

```js
extendWebpack(config) {
	// Remove exisiting
	config.module.rules.delete('svg')
	// Add your own
	config.module.rule('svg')
		.test(/\.svg$/)
		.use('vue-svg-loader')
}
```

**Comment by egoist** [comment]
I will add some docs about existing rules later 😄

**Comment by fungl164** [comment]
Thnxs for the explanation @egoist!  This is great! : D
