### ISSUE TITLE
Modifying a `.elm` file other than `Main.elm` does not hot reload the browser or even recompile the application.

### ISSUE THREAD

**Issue by utkarshkukreti** [egoist/poi#364]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Modifying a `.elm` file other than `Main.elm` does not hot reload the browser or even recompile the application. I have to explicitly press Cmd+S on `Main.elm` to trigger a recompile and hot reload.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Apply this diff on the current master:

```diff
diff --git a/packages/poi-preset-elm/Const.elm b/packages/poi-preset-elm/Const.elm
new file mode 100644
index 0000000..281a434
--- /dev/null
+++ b/packages/poi-preset-elm/Const.elm
@@ -0,0 +1,4 @@
+module Const exposing (..)
+
+one : Int
+one = 1
diff --git a/packages/poi-preset-elm/example/Main.elm b/packages/poi-preset-elm/example/Main.elm
index bede488..8a11586 100644
--- a/packages/poi-preset-elm/example/Main.elm
+++ b/packages/poi-preset-elm/example/Main.elm
@@ -2,6 +2,7 @@ module Main exposing (..)
 
 import Html exposing (..)
 import Html.Events exposing (onClick)
+import Const
 
 
 type alias Model =
@@ -22,10 +23,10 @@ update : Msg -> Model -> Model
 update msg model =
     case msg of
         Increment ->
-            model + 1
+            model + Const.one
 
         Decrement ->
-            model - 1
+            model - Const.one
 
 
 view : Model -> Html Msg
```

2. From `packages/poi-preset-elm`, run `yarn install && yarn example`.

3. Visit http://localhost:4000, press "+" a few times.

4. Now edit Const.elm to change 1 to 2.

    Note that the browser will not reload.

5. Now run `touch src/Main.elm`

    The browser will reload. The state will be preserved and clicking "+" or "-" now will increment/decrement by 2.

**What is the expected behavior?**

The app should reload on changing `Const.elm`.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Browser: Chrome 63. Node: 8.6.0. Poi: 9.6.13. OS: MacOS 10.13.2

Please let me know if you need any more info!

**Comment by pierrebiver** [comment]
I have exact same issue with React. Even when restarting poi. My app does not refresh with the latest code.

**Comment by utkarshkukreti** [comment]
@pierrebiver that's very strange. Restarting `poi` recompiles all the Elm code for me.

@egoist do you have any pointers as to what could be causing this? I'll try to dive into the code to find and fix this bug and a pointer on where I should start would be really appreciated!

**Comment by mblarsen** [comment]
Reproduced the error. Looking into it. @utkarshkukreti

**Comment by mblarsen** [comment]
Issue described here also (the title refers to cache, but actually also the case with cache disabled as can be read in the comments) https://github.com/elm-community/elm-webpack-loader/issues/75

**Comment by mblarsen** [comment]
Got it working in another setup (webpack only). Trying to work out the differences. Will have to take a break from it for now.

**Comment by aaahrens** [comment]
any chance this is fixed?
