### ISSUE TITLE
Single-file .vue components don't render template tags

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/poi#371]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Single-file vue components don't render template tags.

**What is the expected behavior?**
Poi to use the compiler-included build when it sees a template tag in a single-file Vue component.

**If this is a feature request, what is the motivation or use case for changing the behavior?**
This would allow not only small single file apps to use this but also larger ones where each template is separated into its own `.vue`.

**Comment by egoist** [comment]
@OmgImAlexis .vue doesn't need compiler included build

**Comment by OmgImAlexis** [comment]
I thought the same thing but I can't seem to get it working. I'm sure I've just missed something.

I have my main file pointed at `index.vue`.

```html
<template>
  <div id="app">
    <span>Hello world</span>
  </div>
</template>

<script>
import Vue from 'vue';
import Buefy from 'buefy';
import 'buefy/lib/buefy.css';

Vue.use(Buefy);

export default {
  data() {
    return {};
  }
};
</script>
```

**Comment by egoist** [comment]
@OmgImAlexis hmm you didn't mount that component to a dom element?

**Comment by OmgImAlexis** [comment]
I was hoping by exporting using the {} way instead of creating a new vue instance poi would auto mount it into the `#app` div that's created in the `index.html`?

**Comment by egoist** [comment]
@OmgImAlexis I don't know why would you need that

**Comment by OmgImAlexis** [comment]
I'm still not able to get templates working. 

```
<template>
  <span>Hello world</span>
</template>

<script>
import Vue from 'vue';
import Buefy from 'buefy';
import 'buefy/lib/buefy.css';

Vue.use(Buefy);

export default new Vue({
  el: '#app',
  data() {
    return {};
  }
});
</script>
```

```
vue.runtime.esm.js:574 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

**Comment by OmgImAlexis** [comment]
If I wrap the span in `<div id="app"></div>` I still get the error. I've also tried overriding the vue import in webpack with the compiled version and still nothing.

**Comment by egoist** [comment]
@OmgImAlexis that's not how Vue SFC works, you export a Vue component in SFC and use it to create Vue instance in another file.

**Comment by OmgImAlexis** [comment]
Oh okay. There isn't that much documentation around how to use anything but a single `.js` file with Poi so I wasn't 100% sure and the way I was using it I had assumed was how Poi works.

I'm guessing the `index.js` should be the root intace with just a single div for example and the other components, pages, etc. all in single vue files that're loaded into the main one?

Maybe more docs need to be added?

**Comment by egoist** [comment]
@OmgImAlexis Maybe you should check out the vue sfc docs? Poi uses webpack under the hood so I'm assuming you have some basic webpack/bundler knowledge.
