### ISSUE TITLE
Poi is not working with hyperHtml

### ISSUE THREAD

**Issue by ansarizafar** [egoist/poi#375]
Poi is not working with hyperhtml https://viperhtml.js.org/ may be because of an issue like this https://github.com/parcel-bundler/parcel/issues/477. Could you please help me find a solution.

**Comment by egoist** [comment]
@ansarizafar I think that's an issue with hyperhtml itself, they point `broswer` field in `package.json` to a bundle that can't be used with webpack, and webpack actually resolves main file in this order: `browser` ＞ `module` ＞ `main` by default
