### ISSUE TITLE
Proxy in production

### ISSUE THREAD

**Issue by eaststrong** [egoist/poi#385]
proxy only has effects in development?

Does that mean proxy will not work if I run poi build for production?

**Comment by mblarsen** [comment]
If you are referring to [Proxy API request](https://poi.js.org/#/home?id=proxy-api-request), then yes. This is only for development.

**Comment by egoist** [comment]
Yep, `proxy` is likely to be used in development to solve CORS problem, but in production you should solve that in your backend part, i.e. whitelist your domain.

**Comment by eaststrong** [comment]
Thanks for all your kind replies.

Since the proxy API request doesn't work in production, so I have to make a proxy myself, for example, using Nginx, to build a poi app for production. (Same domain, different ports)

According to you guys' suggestions, I shall develop backend API with koa, and develop frontend with poi, and at last use a proxy tool (Nginx) to connect backend and frontend for production.

**Comment by mblarsen** [comment]
You use `poi` (with no additional arguments) during development and when you deploy you run `poi build` this will generate all the static files that your front-end uses.

These files you can server for example via Koa (eg. install koa-static) and from the same application you can serve the API. There is no need for an extra port or a proxy for that matter.

(I know this is a super simplified anwser, but it is also a bit out of scope for the issue)

**Comment by mblarsen** [comment]
Think of poi as zero config tool for developing your front-end and bundling it for production. It is not an application framework with a backend.

Under the hood a fairly complicated webpack configuration is being built up based on best practices.

**Comment by eaststrong** [comment]
Got it. Prefect answer.
