### ISSUE TITLE
Update to Webpack 4

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#388]
Hi, webpack 4 is now released and I think it's time to use it in POI. I read in many articles the new power of Webpack 4 : Better files optimization, reduce size, ...

It's possible to upgrade to webpack 4 ?

Thanks

**Comment by egoist** [comment]
Yeah I'm currently working on it but some plugins are not yet compatible with it.

**Comment by cadejscroggins** [comment]
@egoist just curious, why'd you remove your PR?

**Comment by egoist** [comment]
@cadejscroggins hmm which one? I've merged the one that adds webpack 4 support, the development branch will be merged into master soon too https://github.com/egoist/poi/tree/x

**Comment by cadejscroggins** [comment]
@egoist ah. missed that. sweet!

**Comment by davidmoshal** [comment]
I'd suggest caution on upgrading to Webpack 4, many plugins will break.

Main reason for me switching to POI this week was to avoid having to figure out what version each dev dependency needed to be pegged to.

**Comment by egoist** [comment]
Poi with webpack 4 is under `next` channel on npm, we will only release it in stable channel once everything works fine with webpack 4.

**Comment by egoist** [comment]
https://github.com/egoist/poi/releases/tag/poi%4010.0.0-rc.0
