### ISSUE TITLE
Specify extractCSS option to configure ExtractTextPlugin

### ISSUE THREAD

**Issue by conechan** [egoist/poi#390]
Poi is awesome and I am trying to use her in daily projects.

I hope it can expose more options to configure the webpack plugins.

Such as `ExtractTextPlugin` options. It's hardcoded now, so I can't configure the `publicPath`. (Due to this issue: https://github.com/vuejs/vue-loader/issues/481#issuecomment-306202382)

I found it depends on the `webpack-handle-css-loader` module, which also hardcoded.

I am seeking a workaround, but it seems difficult to modify it by the `extendWebpack` option.

**Comment by egoist** [comment]
See https://github.com/egoist/poi/blob/76387054606da38a4f107a0787f2c17a9d6ebd7c/packages/poi/lib/create-config.js#L237-L243 its options is actually configurable with webpack-chain: https://github.com/mozilla-neutrino/webpack-chain e.g.

```js
extendWebpack(config) {
	config.plugin('extract-css')
	.tap(([options]) => {
		options.filename = '/custom-name/foo.css'
		return [options]
	})
}
```

**Comment by conechan** [comment]
Thanks for your quick respone!

Actually, it's configured in 

https://github.com/egoist/webpack-handle-css-loader/blob/b02c9f7da92d2b53e21e634723bc9f55c941650c/src/index.js#L100-L112

And I need to modify it as below

```js
    config.module.rules.values().forEach(rule => {
      rule.uses.values().forEach(use => {
        use.tap(option => {
          if (option && Object.prototype.hasOwnProperty.call(option, 'omit')) {
            option.publicPath = '../../'
          }
          return option
        })
      })
    })

    config.module.rule('vue').use('vue-loader').tap(option => {
      Object.keys(option.loaders).forEach((loader => {
        if (option.loaders[loader][0]) {
          option.loaders[loader][0].options.publicPath = '../../'
        }
      }))
      return option
    })
```

**Comment by egoist** [comment]
why do you want to modify the `publicPath`? It defaults to `webpackConfig.output.publicPath`.

**Comment by conechan** [comment]
If we configure the `publicPath` as relative path, then the path in the css files may have problems. Because the img path is relative to the css file, not the html file. And the `webpackConfig.output.publicPath` is set to relative to the html file.

If we set it as absolute path, then no issues.
