### ISSUE TITLE
Edit dist CSS and JS folders

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#391]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Actually, on build, POI place compiled css and js files into `dist` root foldier.

**What is the expected behavior?**

Possibility to add an option to change js and css directory inside `dist`, (like `/css` to go in `/dist/css`, ...)

**If this is a feature request, what is the motivation or use case for changing the behavior?**

Have more options to organize compiled code

**Comment by egoist** [comment]
This option might work, not tested though https://poi.js.org/#/options?id=filename

**Comment by throrin19** [comment]
I try this : 

```
filename : {
    js  : 'js/[name].js',
    css : 'css/[name].css',
},
```

And it works find. Thanks 👍

**Comment by throrin19** [comment]
Or not, After test, only vendor, manifest and client are move on it. Not on demand js files : 

```
const Dashboard         = () => import(/* webpackChunkName: "dashboard" */ './pages/Dashboard.vue');
```

**Comment by egoist** [comment]
try setting `filename.chunk` too

**Comment by throrin19** [comment]
it works fine (sorry, i'm late for this response)
