### ISSUE TITLE
very slow relative to webpack ForkTsCheckerWebpackPlugin

### ISSUE THREAD

**Issue by davidmoshal** [egoist/poi#396]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Bundling seems to take a very long time on a project of around 200 files, relative to Webpack.
Reminds me of webpack without ForkTsCheckerWebpackPlugin.

**What is the expected behavior?**

Bundling should not be slower than ForkTsCheckerWebpackPlugin.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

BUNDLING TIME:   
`DONE  Build 65e3dd finished in 257572 ms!`

Almost 5 minutes, which is what I was seeing without ForkTsCheckerWebpackPlugin.
With ForkTsCheckerWebpackPlugin, my old webpack config would bundle in about 20 seconds. 

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Wondering if it's possible to do this (webpack equivalent):

```ts
.....
   module: {
        rules: [
......
          {
                test: /\.ts$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'ts-loader',
                        options: {
                            appendTsSuffixTo: [/\.vue$/],
                            transpileOnly: true // used with ForkTsCheckerWebpackPlugin
                        },
                    }
                ],
            },
....

 plugins: [
        new ForkTsCheckerWebpackPlugin(),
.....
```
My impression is that poi is bundling MUCH slower than the above webpack config.

**Comment by egoist** [comment]
Can you provide a repo that demonstrate this?

**Comment by davidmoshal** [comment]
Unfortunately I cannot share the repo that has 200 modules of proprietary code.
However, the config it uses is exactly the same as this one I created to test out poi:
https://github.com/davidmoshal/poi-ts-vue-jest-example

I have fixed the problem though, by implementing the above code as a preset, based on your 'poi-preset-typescript':

```js
 const poi_preset_ts_forked = ({loaderOptions} = {}) => {
  return poi => {
    poi.extendWebpack(config => {
      config.resolve.extensions
        .add('.ts')
        .add('.tsx')
      config.module.rule('typescript')
        .test(/\.tsx?$/)
        .use('ts-loader')
        .loader('ts-loader')
        .options(
          Object.assign({
              appendTsSuffixTo: [/\.vue$/],
              transpileOnly: true  // add this option for ForkTsCheckerWebpackPlugin
            },
            loaderOptions
          ))
      config.module.rule('vue')
        .use('vue-loader')
        .tap(vueOptions => {
          vueOptions.esModule = true
          vueOptions.loaders.ts = [{
            loader: 'ts-loader',
            options: loaderOptions
          }]
          return vueOptions
        })
    })
  }
}

module.exports = options => {
  return ({
    entry: options.entry || './src/index.ts',
    templateCompiler: true,
    presets: [
      poi_preset_ts_forked(),
      //require('poi-preset-typescript')(/* options */),
      require('poi-preset-bundle-report')(),
      require('poi-preset-webpackmonitor')()
    ],
    define: {
      IS_PRODUCTION: options.mode === 'production',
      BUILD_TIMESTAMP: JSON.stringify(new Date().toLocaleString())
    },
  })
}
```

The the compilation time drops from around 300 seconds, down to 5 seconds:
`DONE  Build 48dfd1 finished in 5478 ms!`

I noticed that I did not need to import the plugin ForkTsCheckerWebpackPlugin so I assumed you are already importing it, so, I tried to simply pass the options to your preset, ie:

```ts
module.exports = options => {
  return ({
    entry: options.entry || './src/index.ts',
    templateCompiler: true,
    presets: [
      require('poi-preset-typescript')({
        transpileOnly: true // add this option for ForkTsCheckerWebpackPlugin
      }),
      require('poi-preset-bundle-report')(),
      require('poi-preset-webpackmonitor')()
    ],
    define: {
      IS_PRODUCTION: options.mode === 'production',
      BUILD_TIMESTAMP: JSON.stringify(new Date().toLocaleString())
    },
  })
}
```
 DONE  Build c6f1f5 finished in 11077 ms!

Now, that really baffled me!
If I re-implement your typescript preset and change the options, then I get 5 seconds.
However, if I pass the options to your plugin, I get 10 seconds.
How can that be, aren't the two equivalent?

Surely passing the option {transpileOnly: true} to your preset is the same as re-implementing the preset with just that option added?

David

**Comment by egoist** [comment]
Mind giving poi v12 a try? Now `@poi/plugin-typescript` is using cache-loader + fork-ts-checker-plugin

**Comment by davidmoshal** [comment]
ok, thanks will do, though that build is currently broken, due to a dependency issue unrelated to Poi, was planning to tackle that this week.
