### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by maple3142** [egoist/poi#397]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Use vue-router lazyload, but get error.
```javascript
const Home = import(/* webpackChunkName: "Home" */ '@/vue/Home').then(x=>x.default)
const routes = [
	{ path: '/', component: Home }
]
Home.then(console.log) //correctly print a component
```

**If the current behavior is a bug, please provide the steps to reproduce.**
[repo](https://github.com/maple3142/WynnStats/tree/5d6210d7895384952f3889e05486933b7155c50f)
Type `poi` and open browser, and get an error: `Failed to mount component: template or render function not defined.`

**What is the expected behavior?**
No error.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
```
node v9.2.1
chrome 65.0.3325.162
poi 9.6.13
Windows 10 1709
```

**Comment by egoist** [comment]
`component` should not be a Promise I suppose.
