### ISSUE TITLE
Dev server didn't start when using app.dev()

### ISSUE THREAD

**Issue by NemoAlex** [egoist/poi#398]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Dev server didn't start when using API.
https://poi.js.org/#/api?id=app-dev

**If the current behavior is a bug, please provide the steps to reproduce.**
I created a repo: https://github.com/NemoAlex/test 

when I run

```
node dev.js
```

Browse http://localhost:4000/ has no response.

But if I run

```
node_modules/poi/bin/cli.js
```
Everything works well.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Node v9.7.1
macOS 10.13.3

**Comment by egoist** [comment]
`app.dev()` only returns the server instance without actually listening to a certain port: https://github.com/egoist/poi/blob/76387054606da38a4f107a0787f2c17a9d6ebd7c/packages/poi/bin/run.js#L140

**Comment by NemoAlex** [comment]
Thanks.
I was mislead by message shown in console:

```

> Open http://localhost:4000 (copied!)
> On Your Network: http://192.168.1.64:4000

 DONE  Build 1c61be finished in 1615 ms!
```
