### ISSUE TITLE
How about support es2015+ on supported browsers.

### ISSUE THREAD

**Issue by maple3142** [egoist/poi#399]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Only generate es5 for production

**If this is a feature request, what is the motivation or use case for changing the behavior?**

Generate both es2015+ and es5, and use `<script type="module"></script>` to use es2015+ version on supported browsers.
And use `<script nomodule></script>` for old browsers.

Inspired by: [Deploying ES2015+ Code in Production Today](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/)

**Comment by egoist** [comment]
webpack does not suppport es target https://github.com/webpack/webpack/issues/2933

**Comment by maple3142** [comment]
No, I means only transpile necessary features like es2015 module, object spread...
And keep those features supported modern browser for production.
`<script type="module"></script>` only for detect modern browser.

**Comment by egoist** [comment]
You can just use a .babelrc file for this?

**Comment by maple3142** [comment]
But how can I make it to generate two version of `.js` files with poi?
One for es2015+, one for es5.

**Comment by egoist** [comment]
@maple3142 run two builds..

**Comment by maple3142** [comment]
I think the result will be one html contains:
```javascript
<script type="module" src="main.js"></script>
<script nomodule src="main-legacy.js"></script>
```
But every build will delete `dist`, and generated files name is random.
Is is hard to make merge two build to one html.

**Comment by egoist** [comment]
Closing since this is beyond the scope Poi currently focuses on.
