### ISSUE TITLE
API: TypeError: this.setDynamic is not a function

### ISSUE THREAD

**Issue by fjc0k** [egoist/poi#400]
`poi: ^9.6.13`

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
code:
```javascript
const poi = require('poi')

module.exports = options => {
  poi({
    mode: 'development',
    ...options
  })
    .dev()
    .then(
      ({ server, host, port }) => {
        console.log(server, host, port)
      },
      console.error
    )
}
```
run but throw error:
```shell
TypeError: this.setDynamic is not a function
    at PluginPass.pre (***\node_modules\babel-plugin-transform-runtime\lib\i
ndex.js:31:12)
    at transformFile (***\node_modules\@babel\core\lib\transformation\index.js:98:25)
    ............
```

**What is the expected behavior?**
run and no error

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by OmgImAlexis** [comment]
May be related https://github.com/babel/babel-loader/issues/560#issuecomment-428544754
