### ISSUE TITLE
Using Envs in Poi v10

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#412]
**Do you want to request a *feature* or report a *bug*?**

a bug I think.

**What is the current behavior?**

In my poi config, I set my evironment variables like this : 

```javascript
{
    env : {
        ENVIRONMENT : process.env.ENVIRONMENT || 'development',
    }
};
```

When I run my command I do this : 

```
ENVIRONMENT=local poi
```

**What is the expected behavior?**

`process.env` is empty in my project code part. This is works fine in POI v9. How I can do this in POI v10 ?

**Comment by egoist** [comment]
`env` no longer accepts an object since v10, https://github.com/egoist/poi/blob/master/docs/options.md#env

If you want to set it in config file, use [define](https://github.com/egoist/poi/blob/master/docs/options.md#define) instead, e.g.:

```js
module.exports = {
  define: {
    'process.env.FOO': '"foo"'
  }
}
```

**Comment by throrin19** [comment]
It works fine. Thanks 👍
