### ISSUE TITLE
Dist for chunk css files

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#415]
**Do you want to request a *feature* or report a *bug*?**

a Feature

**What is the current behavior?**

Actually, in `filename` options, we just can set this types : 

- js
- css
- chunk (js and css without any difference)
- image
- font

It would be great if we can set differents target directories/format for chunk js and chunk css.

In my case, actually I've this configuration :

```javascript
{
	filename : {
        js      : 'js/[name].[hash].js',
        css     : 'css/[name].[hash].css',
        chunk   : 'js/[name].chunk.[hash].js',
    },
}
```

And this is the targets : 

```
dist/js/forms.chunk.95158af075aeeed3f896.css
dist/js/forms.chunk.95158af075aeeed3f896.js
dist/js/dashboard.chunk.95158af075aeeed3f896.css
dist/js/dashboard.chunk.95158af075aeeed3f896.js
dist/js/vendors~main.chunk.95158af075aeeed3f896.css
dist/js/vendors~main.chunk.95158af075aeeed3f896.js
```

I just wan't to move chunk CSS files into `dist/css/`

**Comment by ChiaJune** [comment]
Have the exact same issue

**Comment by egoist** [comment]
So I removed the `chunk` option in v12, it's automatically inferred from `js` and `css` filename now.
