### ISSUE TITLE
Poi's move to babel 7.x (beta) breaks apps that use packages stuck at babel 6.x

### ISSUE THREAD

**Issue by paulpv** [egoist/poi#416]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
jest test framework errors out with `Requires Babel "^7.0.0-0", but was loaded with "6.26.0"`

**If the current behavior is a bug, please provide the steps to reproduce.**
* Create a Vue app that uses tyu or common vue-test-utils/babel-jest/jest-vue-processor/etc packages
* `yarn test`

My specific project is at:
https://github.com/paulpv/vuetify-number-field

**What is the expected behavior?**
Tests succeed

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Node 8.9.1 on MacOS 10.12.6

I have a Vue app that uses https://github.com/egoist/poi 10.0.3 and https://github.com/egoist/tyu 1.0.6.
(Both are by egoist)

poi has a dependency of "@babel/core": "^7.0.0-beta.40"
  https://github.com/egoist/poi/blob/master/packages/babel-preset-poi/package.json#L26
This change from 6.x to 7.x was made on 2018/04/08
  https://github.com/egoist/poi/commit/5f9d2f8d45fe65541efda0ac6321501da4d2dc8d

tyu has a dependency of "babel-core": "^6.26.0"
  https://github.com/egoist/tyu/blob/master/package.json#L32
babel-jest has a dependency of "babel-core": "^6.0.0"
  https://github.com/facebook/jest/blob/master/packages/babel-jest/package.json#L16
vue-test-utils has a dependency of "babel-core": "^6.26.0"
  https://github.com/vuejs/vue-test-utils/blob/dev/package.json#L31
jest-vue-preprocessor uses 6.x
Almost everything has a dependency on the non-beta ^6.x

However, on 2018/03/04 babel made a master branch change that makes anything using babel 7.x subpackages *require* 7.x core
https://github.com/babel/babel/commit/a4795408b47e713aa2635d54197343be77e30f35
(97 hits when you search for "api.assertVersion(7)")

Here is the specific line that throws "Requires Babel "^7.0.0-0", but was loaded with "6.26.0"":
https://github.com/babel/babel/commit/a4795408b47e713aa2635d54197343be77e30f35#diff-dfc7d21125468c9179a283f78d45391bR71

Either poi needs to revert back to pre-a4795408b47e713aa2635d54197343be77e30f35
(No idea what precise version that is)...
...or revert back to 6.x...
...or, tyu (and perhaps all of the other packages) need to move to ^7.x beta

I don't think the latter is possible.
I don't know if the others are possible.

**Comment by egoist** [comment]
Closing since Babel 7 is now stable.
