### ISSUE TITLE
Documentation for 10.x sucks

### ISSUE THREAD

**Issue by padcom** [egoist/poi#417]
**Do you want to request a *feature* or report a *bug*?**
This is basicaly a missing feature request

**What is the current behavior?**
Documentation sucks. Big time.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/egoist/poi/tree/master/docs <- this is way not enough

**What is the expected behavior?**
At minimum a description such as the docs for 9.x.

**If this is a feature request, what is the motivation or use case for changing the behavior?**
Learning POI using the new docs is simply impossible.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by padcom** [comment]
No offence, @egoist but since this is the default when you install POI using npm then the confusion is great. For example there is a breaking change for JSX (used to be vue, now it is react, what the hell is poi-preset-react for these days?). I am using POI for over a year now and I love it very much. I hate to see it take a dive. There have been no announcements on the main page (poi.js.org) and there is absolutely nothing about a migration path from 9.x to 10.x.

Please help us use the new version! I beg you!

**Comment by egoist** [comment]
Yeah indeed the new docs are incomplete, I didn't announce it publicly because of this, so you can still stick to v9 for now.

Will try to use https://vuepress.vuejs.org/ to rewrite the docs 😄 including a migration guide

**Comment by egoist** [comment]
btw poi-preset-react no longer makes sense now, since it's quite easy to configure `.babelrc` for both JSX and HMR support.

**Comment by padcom** [comment]
Like I mentioned before the problem is that nowadays if you npm install
--save-dev poi or npm install -g poi it will install 10.x by default. From
my point of vue this is a major setback for new users.

2018-04-16 18:03 GMT+02:00 EGOIST <notifications@github.com>:

**Comment by egoist** [comment]
Docs have been moved to https://poi.js.org

**Comment by padcom** [comment]
Looks better, just the content is very... limited. Is the 10.x version very
different from 9.x? Maybe it'd be possible to just update the old docs?

2018-04-18 4:44 GMT+02:00 EGOIST <notifications@github.com>:

**Comment by padcom** [comment]
It as been quite some time since I opened that ticket, POI is now in version 10.2.x and the docs are still incomplete. EGOIST, please get it sorted out. Since version 10 everything started falling apart (missing features, changed configuration options, broken behavior). I used to be a hard-core POI evangelist but now I tell people to stick with version 9.x because 10.x is just broken.

**Comment by dimensi** [comment]
I can't understand how to migrate to poi 10.
In docs no words about vue-loader 15.
What's happen with options inlineImageMaxSize?

**Comment by egoist** [comment]
I'm working on v12 beta docs, should be much better now so I'm closing this issue.
