### ISSUE TITLE
vue-static is not honoring extractCSS

### ISSUE THREAD

**Issue by cj** [egoist/poi#421]
**Do you want to request a *feature* or report a *bug*?**

bug.

**What is the current behavior?**

vue-static is not honoring extractCSS.

**If the current behavior is a bug, please provide the steps to reproduce.**

If you run https://github.com/egoist/poi/tree/master/packages/plugin-vue-static/example you'll see the css is embedded into the index.html and no css files are generated.

**What is the expected behavior?**

css files to be generated.

**Comment by egoist** [comment]
yeah there's some issue with that, so I disabled that for now

**Comment by cj** [comment]
what was the issue, maybe I can help?

**Comment by cj** [comment]
ah nm, I see the comment in the code.

**Comment by cj** [comment]
@egoist looks like `vue-loader@next` solves the issue 😄 https://github.com/vuejs/vue-hackernews-2.0/pull/302#issuecomment-382741947

**Comment by cj** [comment]
here's a full gist of `poi build` https://gist.github.com/54ac6d1251ea73ed0c81a1439c1c67a6

**Comment by egoist** [comment]
no longer an issue, closing.
