### ISSUE TITLE
ESLint Validation does not works correctly

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#423]
**Do you want to request a *feature* or report a *bug*?**

a bug on POI or poi/plugin-eslint

**What is the current behavior?**

When the plugin is activated, eslint validation does not works. I try to make an eslint error and the build don't show any error or cancel compilation. If I have any warns, they are not presents in terminal or web console.

**If the current behavior is a bug, please provide the steps to reproduce.**

Make an ESlint error on one file, compile and voilà, no error shown

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

- POI : 10.1.2
- poi/plugin-eslint : 10.0.0
- eslint : 4.19.1
- babel-preset-poi : 10.0.0

> This works fine with POI 9.x

**Comment by egoist** [comment]
hmm it's working correctly for me after running `poi build`

**Comment by throrin19** [comment]
this is my config for this part and I confirm that, Poi don't show errors in last version :

```javascript
{
    plugins : [
        // reglages propres au test d'eslint au build des fichiers
        require('@poi/plugin-eslint')({
            loaderOptions : {
                configFile  : path.resolve(__dirname, './.eslintrc.json'),
                useEslintrc : true,
            },
            mode : '*',
        }),
    ],
}
```

and this is my `.eslintrc.json` :

```json
{
  "extends" : "throrinstudio/vue"
}
```

**Comment by throrin19** [comment]
Ok I found the problem. I use the old option `mode`. But, in new versions, the option is now `command`.

I change that and it works fine ;)
