### ISSUE TITLE
Globally installed Poi not working 

### ISSUE THREAD

**Issue by ansarizafar** [egoist/poi#427]
I am using latest version of globally installed poi but getting this error
````
 Failed to compile with 2 errors

Cannot find module "babel-loader" in "/home/zafar/projects/tailwindcss"!
You may run npm install babel-loader to install missing dependencies.
You may also append -D flag for devDependencies.

Cannot find module "vue-style-loader" in "/home/zafar/projects/tailwindcss"!
You may run npm install vue-style-loader to install missing dependencies.
You may also append -D flag for devDependencies.

````
I think these two dependencies are missing.

**Comment by mikerockett** [comment]
Same thing with `vue` and `vue-loader`. Installing those manually says something about a missing Webpack RuleSet...?

**Comment by caimaturo** [comment]
Same thing here and I'm not even using Vue, it's asking me to install `vue-loader`.

**Comment by egoist** [comment]
Try Poi 12, I'm glad to help if it's still not working.
