### ISSUE TITLE
the compile time is not the correct one

### ISSUE THREAD

**Issue by tinchoz49** [egoist/poi#431]
Hi @egoist, how are you?

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The compile time is not correct during the web development

![peek 2018-05-06 13-00](https://user-images.githubusercontent.com/819446/39675175-b11ebc92-512d-11e8-9c44-0402161c9f14.gif)

**What is the expected behavior?**

Show the real compile time during a reload which is about 80ms in my current test

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Chrome 66.0.3359.139
Node 10
Poi version 10.1.5
Manjaro xfce

**Comment by tinchoz49** [comment]
wow!! that's really weird indeed haha :smile:  I will keep testing to provide more info

**Comment by dpaez** [comment]
Hi 👋 
Same odd behavior here.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/837500/39881685-06216140-5458-11e8-8eeb-2a304a6049c2.gif)

- poi version: 10.1.6
- node version: 8.4.0
- OS: MacOS High Sierra

**Comment by egoist** [comment]
Seems no longer an issue in Poi v12, mind giving a try?

**Comment by tinchoz49** [comment]
Indeed! thanks @egoist!
