### ISSUE TITLE
Environment variables, poi 9 vs poi 10

### ISSUE THREAD

**Issue by bmaland** [egoist/poi#433]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

In poi 10, environment variables has to be loaded via dotenv files. In many scenarios (e.g. CI) this is less practical than the previous behavior where the `env` key in `poi.config.js` simply could contain an object, e.g.:

```
env: {
	GIT_HASH: process.env.GIT_HASH,
	RAVEN_DSN: process.env.RAVEN_DSN
}
``` 

I suggest supporting both usages. If `env` is a boolean then it can load using dotenv. If `env` is an object, then poi 9 behavior is used. If you agree then i can provide a PR

**Comment by egoist** [comment]
> If env is a boolean then it can load using dotenv. If env is an object, then poi 9 behavior is used.

LGTM. PR welcome. btw [define](https://poi.js.org/options.html#define) can be used as a workaround.

**Comment by bmaland** [comment]
Using `define` instead of `env` is a decent workaround (if a bit more verbose), closing this
