### ISSUE TITLE
UMD format relies on `window` which errors in Node

### ISSUE THREAD

**Issue by jakelucas** [egoist/poi#434]
**Do you want to request a *feature* or report a *bug*?**

Either depending on how you look at it.
To me it's a bug.

**What is the current behavior?**

When a Vue component is built using `poi build` with the `--format` option set to `umd`, the final JS file that's output passes the `window` object into as the first argument to the IIFE.

**If the current behavior is a bug, please provide the steps to reproduce.**

Build a Vue component with the `--format` set to `umd` and look at the final JS output.
(I don't use the CJS format so I can only speak for UMD in this issue)

**What is the expected behavior?**

To not rely on `window` being available.

I use Poi to build Vue components which are dynamically fetched and instantiated in Node for SSR. The built components work fine in the browser, but Node doesn't have a `window` object which causes it to error.

Currently I'm getting around this by attempting to replace the word `window` with `global` in the JS string before I run it, but this isn't ideal since it has the potential to break things. So it would be nice if the generated output didn't assume a browser and tested to see which object it should pass in.

I'm not sure if I'm just missing something from the documentation, but I couldn't see anything that would change the output to not assume `window` exists.

The main reason I bring this up as an issue is because it didn't used to error in version 9.5.5 of Poi, which is the version I used before updating.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

To not crash Node.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Poi is at the latest version at the time of writing (10.1.6).

**Comment by egoist** [comment]
<img width="657" alt="2018-05-11 7 59 06" src="https://user-images.githubusercontent.com/8784712/39923348-d393acf2-5555-11e8-8e25-b483afb64b1b.png">

The `window` object would not be used when running in node.js because of line 2

**Comment by jakelucas** [comment]
@egoist Thanks for the quick reply. In that case then it must be something to do with how I'm executing the script, because I just edited the JS file to console log the `typeof` the variables in those checks and for me they're all undefined.

I'll close this issue and have a look into it on my end again.
