### ISSUE TITLE
library option is removed.

### ISSUE THREAD

**Issue by rasteiner** [egoist/poi#438]
**Do you want to request a *feature* or report a *bug*?**

Feature request

**What is the current behavior?**

Documentation mentions that the library options has been removed

**What is the expected behavior?**

the library option was the only reason I was using poi. Are there any plans to bring it back? Are there other options I can use instead?

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Poi v10

**Comment by egoist** [comment]
use `format` directly https://poi.js.org/options.html#format

**Comment by rasteiner** [comment]
Ok thanks! 

Going with 
```bash
poi build --outDir . --filename.js index.js --filename.css index.css && rm index.html
```
