### ISSUE TITLE
10.* poi is using command line cli flags 

### ISSUE THREAD

**Issue by k1r0s** [egoist/poi#441]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

current version 10.1.10

`poi index.js --jsx h` fails with custom pragma (preact)

**If the current behavior is a bug, please provide the steps to reproduce.**

after checking https://poi.js.org/options.html#babel i tried `poi index.js --babel.jsx h` and its working perfectly

**What is the expected behavior?**

perhaps changing documentation will be fine. Maybe im confused about what is CLI and what is not.

Does poi 10.1.10 stands for `CLI`?

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

thanks

**Comment by egoist** [comment]
`jsx` is an option for Poi 9 only https://poi.js.org/migrate-from-9-to-10.html#jsx

**Comment by k1r0s** [comment]
thanks @egoist 

Does poi 10.* and so on, stands for CLI? if so, this is correct. If not we need to update https://poi.js.org/options.html#babel

**Comment by egoist** [comment]
what needs to be updated? CLI means command-line interface

**Comment by k1r0s** [comment]
https://www.youtube.com/watch?v=qYMuDXQG9K4
