### ISSUE TITLE
[BUG] vue-loader failed to load

### ISSUE THREAD

**Issue by mubaidr** [egoist/poi#446]
*bug*

**What is the current behavior?**

Building a script (collection of components for Vue.js) using poi results in following error message:

> Error: [VueLoaderPlugin Error] vue-loader 15 currently does not support vue rules with oneOf.
  at VueLoaderPlugin.apply (D:\current\vue-fluent\node_modules\vue-loader\lib\plugin.js:47:13)
  at webpack (D:\Current\vue-fluent\node_modules\webpack\lib\webpack.js:37:12)
  at Poi.createCompiler (D:\Current\vue-fluent\node_modules\poi\lib\index.js:104:50)
  at Poi.runCompiler (D:\Current\vue-fluent\node_modules\poi\lib\index.js:113:27)
  at Command.poi.cli.handleCommand [as handler] (D:\Current\vue-fluent\node_modules\poi\lib\plugins\build.js:9:17)
  at Cac.parse (D:\Current\vue-fluent\node_modules\cac\dist\cac.js:418:27)
  at CLI.runCommand (D:\Current\vue-fluent\node_modules\poi\lib\cliEngine.js:32:21)
  at Poi.run (D:\Current\vue-fluent\node_modules\poi\lib\index.js:240:32)

**If the current behavior is a bug, please provide the steps to reproduce.**

- Create a script which install vue component (from single file component)
- Add `vue-loader` to the webpack config using:
```js
const { VueLoaderPlugin } = require('vue-loader')

module.exports = {
  configureWebpack(config, context) {
    config.plugins.push(new VueLoaderPlugin())
    return config
  },
}
```
- Compile using `poi build`

**What is the expected behavior?**

Library/script should be compiled successfully. 

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Node.js 10.2.1
Poi 10.2.1
Windows 10 x64

**Comment by egoist** [comment]
Just remove that config, v10.2.1 uses vue-loader 15 by default.

**Comment by mubaidr** [comment]
If the config is removed then following error message appears for each `.vue` in the project:

```sh
× Failed to compile with 73 errors

vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.
```

`package.json` with build script: https://github.com/mubaidr/vue-fluent/blob/master/package.json

**Comment by egoist** [comment]
hmm the build script in that repo is using vue-cli 😅

I just tested `yarn poi src/docs/src/main.js` in that repo and it works fine

**Comment by mubaidr** [comment]
No it is not. I am talking about the root `package.json` (not the one in `src/docs`)

https://github.com/mubaidr/vue-fluent/blob/master/package.json#L65

This: 
```sh
"build-lib-js": "poi build src/lib/index.js --out-dir dist --filename.js vue-fluent.js --format cjs"
```

**Comment by egoist** [comment]
hmm 
<img width="354" alt="2018-05-31 9 46 09" src="https://user-images.githubusercontent.com/8784712/40772259-14284ac4-64f2-11e8-8aac-3aed80d90777.png">

maybe you should try remove your `node_modules`

**Comment by mubaidr** [comment]
Ok I will do that. Thanks for quick response. Appreciated!

**Comment by mubaidr** [comment]
@egoist Removed the `node_modules`folder and installed package again. Still same error. :(

I will try to clean the yarn/npm cache and do the installation again.

**Comment by mubaidr** [comment]
Looks like `poi` installation is not supported via `yarn`, when installed via `npm`, scripts compiled successfully without any error. 

To make sure this behavior I will test again after installing `poi` using `yarn`.

**Comment by egoist** [comment]
well I literally just cloned your repo and run it with yarn and it works 😂

**Comment by mubaidr** [comment]
This is very strange behavior, now installing `poi` gathers lots of more packages than the last time and it works! Both with `yarn` and `npm`. Time to rebuild my development environment I guess. :joy:

Sorry for all the inconvenience. 

**Solution: It was a bad installation**

**Another issue**

Source map is not being generated for final script. build command: 
```sh
poi build --source-map true --out-dir dist --filename.js vue-fluent.js --format cjs
```
or
```sh
poi build --out-dir dist --filename.js vue-fluent.js --format cjs
```

**Comment by egoist** [comment]
fyi you can use `--inspect-webpack` (like vue-cli 3) to inspect generated webpack config to see if `devtool` is correctly set.

**Comment by egoist** [comment]
well poi always disables sourcemap when `format` is set, 
https://github.com/egoist/poi/blob/c90b81dba3139cccf9d2ebd42bfd5e414870ffd5/packages/poi/lib/handleOptions.js#L106

since I think it's useless for a library

**Comment by mubaidr** [comment]
Awesome. Thanks for the help and quick reply.
