### ISSUE TITLE
Several public paths

### ISSUE THREAD

**Issue by Aymkdn** [egoist/poi#447]
**Do you want to request a *feature* or report a *bug*?**

I think it's a feature (except if it's already possible to do it ?).

**What is the feature?**

I'd like to define several public path during development (for a multiple-pages application), just how it's exposed here:
https://github.com/webpack/webpack-dev-server/issues/200#issuecomment-139666063

The idea is to access sub folders during development, for example, accessing http://localhost:4000/one/ and http://localhost:4000/two/

**Comment by egoist** [comment]
You mean https://poi.js.org/options.html#staticfolder?

**Comment by Aymkdn** [comment]
Thanks for the quick reply. Let me try to explain better (maybe I totally wrong on how to do it).

Below is my folders' structure:
```
./
Gruntfile.js
index.ejs
package.json
poi.config.js
src/Projects/App.vue <-- my app for Projects
src/Projects/App.js  <-- used to compile it
src/Projects/Dev.vue  <-- used for dev webserver
src/Projects/Dev.js
src/Assets/App.vue  <-- my app for Assets
src/Assets/App.js   <-- used to compile it
src/Assets/Dev.vue   <-- used for dev webserver
src/Assets/Dev.js
src/common.js
dist/
```

`Projects` and `Assets` are two different pages/app (but that belongs to the same entity, and that could share some `.js` files etc). When compiling (with `poi build`) I want something like that:
```
dist/projects.hash.js
dist/assets.hash.js
dist/vendors.projects.hash.js
dist/vendors.assets.hash.js
```

When I develop (with `poi`) I'd like to be able to go to http://localhost:4000/Projects/ to execute my `src/Projects/Dev.vue`, and to http://localhost:4000/Assets/ to execute my `src/Assets/Dev.vue`.

On production, I'll access to https://mywebsite/path/projects/index.html and https://mywebsite/path/assets/index.html

Does it make sense ?

Thanks

(I'm kind of new with webpack/poi ...)

**Comment by Aymkdn** [comment]
After hours searching for a solution (saying some leads with the multi-compiler), I gave up. It looks like it might be possible but my knowledge of webpack is not good enough to figure out a solution.

So I ended up with several projects, and each project has its own webdev on a different port, and I use some tricks to make them work altogether during development :-/

Feel free to close this issue.
