### ISSUE TITLE
Hot reload index.ejs

### ISSUE THREAD

**Issue by gilesbutler** [egoist/poi#449]
**Do you want to request a *feature* or report a *bug*?**
Sorry not sure if this is a feature or a bug

**What is the current behavior?**
index.ejs doesn't hot reload on save

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Expect custom index.ejs to hot reload on save

**If this is a feature request, what is the motivation or use case for changing the behavior?**
index.js and styles.css hot reload already. When you're working on html components you have to refresh

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Node: v8.10.0
Poi: 10.2.1
MacOS: 10.13.4

**Comment by egoist** [comment]
Fixed in v11 beta, changes made in your [custom html template](https://poi.js.org/guide/custom-html-template.html) will trigger full reload.
