### ISSUE TITLE
ReferenceErr on dev-utils/hotDevClient.js 

### ISSUE THREAD

**Issue by k1r0s** [egoist/poi#450]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
JS exception on browse dev build
![image](https://user-images.githubusercontent.com/6052309/40914892-40600b26-67fa-11e8-9ec3-0613d527f9b5.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
$ `poi src/index`

there is no config

just a React repo

**What is the expected behavior?**

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
poi version is 10.2.*

**Comment by egoist** [comment]
Fixed in a newer version
