### ISSUE TITLE
Add Support for .env.{environment}.local overrides

### ISSUE THREAD

**Issue by jchamb** [egoist/poi#452]
**Do you want to request a *feature* or report a *bug*?** *feature*

**What is the current behavior?** .env.{environment}.local is not loaded and only variables in .env.{environment} are set

**What is the expected behavior?** .env.{environment}.local should load and override any variables assigned. Matching functionality of [create react app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env) 

**If this is a feature request, what is the motivation or use case for changing the behavior?**
Across different devs and teams we have our own local dev environments with different hostnames/etc. This would allow for use to set defaults per environment to be part of a repository while providing an easy way to override the values.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**  poi 10.2.4

**Comment by jchamb** [comment]
#453

**Comment by egoist** [comment]
So I updated it a bit to match CRA's behavior: https://poi.js.org/guide/features.html#adding-development-environment-variables-in-env
