### ISSUE TITLE
TSLint plugin

### ISSUE THREAD

**Issue by padcom** [egoist/poi#454]
**This is a *feature* request**

**TSLint plugin for validating TS files **

**If this is a feature request, what is the motivation or use case for changing the behavior?**

A TSLint plugin (just like the ESLint one) should enable linting of typescript files

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

POI 10.x

**Comment by egoist** [comment]
Added in v12 beta, it's available in `@poi/plugin-typescript`, use it manually or simply: `create-poi-app my-app`
