### ISSUE TITLE
Stop being such smarter than webpack with publicPath

### ISSUE THREAD

**Issue by padcom** [egoist/poi#460]
**Do you want to request a *feature* or report a *bug*?**
It is a bug introduced intentionally

**What is the current behavior?**
Setting publicPath only works in production build

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Set `publicPath` in config
2. Run `$ npx poi`
3. See the generated html and/or css still being based on `/` rather than the specified `publicPath`

https://github.com/egoist/poi/blob/master/packages/poi/lib/utils/getPublicPath.js

**What is the expected behavior?**
Regardless of the mode honor `publicPath`

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
POI: 10.2.0

**Comment by dangreaves** [comment]
👍 for this.

I am changing the `publicPath` so my assets resolve correctly from the compiled CSS. Currently, I cannot use `poi watch` as the path will fallback to `/` and my assets no longer resolve.

I am interested as to why the `getPublicPath` utility is required.

**Comment by padcom** [comment]
@dangreaves Thanks for the info! I did that too but it completely broke hot reload in my project.
What I ended up doing was to leave the `publicPath` for both dev and prod builds as `/` and I specified all names for files with the full path. It looks ugly but it works.
