### ISSUE TITLE
can not digest the vue single file component (SFC) directly

### ISSUE THREAD

**Issue by kenberkeley** [egoist/poi#472]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Not render the component

**If the current behavior is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/13287948/43437302-eb0cf380-94ba-11e8-9cd8-75f74fe37d3f.png)

**What is the expected behavior?**
Display `Hello, world!`

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Windows 10, Chrome 67, Node v9.10.1, poi 10.2.9

**Comment by kenberkeley** [comment]
Not working even though `el` indicated

![image](https://user-images.githubusercontent.com/13287948/43437280-caad879e-94ba-11e8-802a-c89727f161be.png)

**Comment by egoist** [comment]
that's not how Vue works, create a root Vue instance in a .js file instead:

```js
import Vue from 'vue'
import App from './App.vue'

new Vue({
	el: '#app',
	render: h => h(App)
})
```
