### ISSUE TITLE
Cannot find module 'postcss-load-config' (pnpm install)

### ISSUE THREAD

**Issue by kenberkeley** [egoist/poi#473]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error: Cannot find module 'postcss-load-config'

**If the current behavior is a bug, please provide the steps to reproduce.**
Install dependencies with [pnpm](https://github.com/pnpm/pnpm)

**What is the expected behavior?**
Work as normal

**If this is a feature request, what is the motivation or use case for changing the behavior?**
add `postcss-load-config` to https://github.com/egoist/poi/blob/master/packages/poi/package.json

![image](https://user-images.githubusercontent.com/13287948/43445892-0b30cca8-94da-11e8-83da-081691e34739.png)

**Comment by egoist** [comment]
I'm going to make v10 support pnpm, since it might require a lot of efforts.

However, for v12, feel free to open another issue if you find a problem there.
