### ISSUE TITLE
Ignore folders from being cleaned in dist.

### ISSUE THREAD

**Issue by jchamb** [egoist/poi#486]
Using poi 10.2.10.  
Working on an older app we are slowing migrating fully over to react. We have some required files that are in our public folder, however anytime we use yarn watch because we have hashes in our dist it is cleaned and it removes those folders.

Is there any way I can have those files/folder ignored from the clean? Or alternatively have it copy the contents of public to our dist when running poi watch?

I did some digging around, but wasn't able to find where the configuration was to tell it to clean those folders. Any help would be appreciated

**Comment by egoist** [comment]
For v10, files inside `static` folder will be copied to `dist`. 

BTW For v11 we copy `public` folder since both CRA and Vue CLI use that one.

**Comment by jchamb** [comment]
Thanks egoist. not sure how i missed that. Hopefully moving to 11 soon jsut need to make time to do the transition

**Comment by jchamb** [comment]
Looks like there is still an issue during "watch". It copies properly during the initial compile after running "poi watch" but for every recompile after saving a file it clears the folder but never recopies the static folder over.

Reopening for now, I'll try to test this later in a v11 project to see if the problem still persists there.

**Comment by jchamb** [comment]
confirmed 11 only clears during build.
