### ISSUE TITLE
babel include option doesn't work

### ISSUE THREAD

**Issue by lili21** [egoist/poi#492]
the default minimizer doesn't support es6 syntax. 

![image](https://user-images.githubusercontent.com/4456380/48817537-e26a9500-ed81-11e8-9fa7-239edacca3da.png)

```javascript
// poi.config.js
module.exports = {
  ...
  babel: {
    include: ['query-string']
  }
}
```

the module `query-string` should be compiler by babel and wouldn't contain es6 syntax. But it' not. same error. 

Am I doing something wrong ?

I'm using Poi@10.2.11.

**Comment by egoist** [comment]
Which version are you using?
