### ISSUE TITLE
Multi complier for different frameworks like micro frontend?

### ISSUE THREAD

**Issue by brandonxiang** [egoist/poi#493]
https://github.com/egoist/poi/blob/1fda9120435b129157784356a935837be106d503/packages/poi/lib/utils/load-pkg.js#L17-L25

POI can be used in different frontend framework like vue, preact, react. However，jsx compiler is judged by dev packages.

In the micro frontend situation, it is difficult to deal with the problem.

May the commandar like follows be suitable?

```shell
poi dev --framework vue
```

**Comment by egoist** [comment]
I removed this feature in the latest beta version 😅
