### ISSUE TITLE
Basic installation guide?

### ISSUE THREAD

**Issue by joeldbirch** [egoist/poi#494]
Coming back to POI after a year or more, I can't remember how to begin. The "Getting Started" part of the documentation skips installation. I imagine this may be hurdle for beginners. Should we install globally? If so, what is the code to do so? Is it `npm install poi -g`? Is that the only step required before the "Getting Started" instructions work? Thanks.

**Comment by egoist** [comment]
well the basic usage doesn't really change.

**Comment by joeldbirch** [comment]
I just think installation should be explicitly mentioned to prevent beginners headbutting their desk in frustration. 😃

**Comment by egoist** [comment]
I will include more information in the new docs for the next Poi version (which will be released soon)

**Comment by egoist** [comment]
Done: https://poi.js.org/guide/installation.html

Feel free to improve it by sending Pull Requests.

**Comment by joeldbirch** [comment]
Perfect, thanks so much. I’m a big fan of your work.
