### ISSUE TITLE
Publish type definitions

### ISSUE THREAD

**Issue by egoist** [egoist/poi#497]
Someone interested in adding `@types/poi` to https://github.com/DefinitelyTyped/DefinitelyTyped? :P

**Comment by egoist** [comment]
We can start with adding the type for Poi config:

```js
/** @type {import('poi').Config} */
const config = {}

module.exports = config
```

**Comment by bolasblack** [comment]
Hi I have a question, why not put declaration file(.d.ts file) in poi npm package, but put in `@types/poi`? In this case, the user does not need to install another package for type checking and autocompletion.

**Comment by egoist** [comment]
@bolasblack that will add a few mega bytes to Poi 😅

**Comment by bolasblack** [comment]
@egoist I created a PR: DefinitelyTyped/DefinitelyTyped#34424, I think you can review the code and confirm that there is no problem with the type definition I wrote.

**Comment by bolasblack** [comment]
Finally, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34424 merged

**Comment by egoist** [comment]
woot, thanks 😄
