### ISSUE TITLE
Updated guide for starting a React app in Poi v12

### ISSUE THREAD

**Issue by SeedyROM** [egoist/poi#501]
I've used Poi in the past to for Vue projects, but just recently decided to try it out with react. The current documentation is almost completely devoid of any hints as to how to get started. I ended up using an older version of Poi to get up and running.

I think if this project wants to keep up with the other framework specific tools it needs to atleast document what's changed since v9~

I know @egoist is probably very busy, so let me know if I can help in anyway!

**Comment by egoist** [comment]
I just added this page: https://poi.js.org/migration-guide/9-to-12.html

I'm not sure how the Getting Started guide can be improved though, contributions to documentations are welcome.

**Comment by egoist** [comment]
btw did you check ou this? https://poi.js.org/guide/frameworks.html#react

**Comment by SeedyROM** [comment]
I did, but since I've been adapting things to Typescript I was getting a few weird bugs. I've decided to keep studying for now and I'll definitely submit documentation when I come back to this project next weekend.

**Comment by egoist** [comment]
More examples are available here: https://github.com/poi-bundler/examples
