### ISSUE TITLE
Hot entries validation does not allow lists longer than one item

### ISSUE THREAD

**Issue by tingard** [egoist/poi#503]
The config validation script restricts `config.devServer.hotEntries` to having length one.

I think can be fixed by changing using a list not a tuple: `struct.tuple(['string'])` => `struct(['string'])`

https://github.com/egoist/poi/blob/ae8235a800e454a36e8e2885ef0a4f476e1f0522/core/poi/lib/utils/validateConfig.js#L78

Happy to open a PR if you'd like.

**Comment by egoist** [comment]
Available in 12.2.0 and above, thanks for the contribution.
