### ISSUE TITLE
Get server instance from API

### ISSUE THREAD

**Issue by pedronauck** [egoist/poi#506]
Hi, first of all, congratulations you really made an excellent job with Poi 👏 
So, I'm the creator of [docz](https://github.com/pedronauck/docz), a framework to write documentation.

Docz internally uses webpack to serve and build documentation. But, often I need to care about webpack configuration and keep my eyes open with that, this not a good thing at all because I would like to just worry about the other things since today we have so concise tools that lead with the bundle.

With that in mind, I'm searching some tool to replace the bundle configuration on docz and I think that Poi is the best choice that I can have. But, I had some troubles when I tried to implement it.

1. In docz, we have a [Bundler](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/Bundler.ts) that's responsible to get the bundler config and pass to the server (how you can see [here](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/webpack/index.ts)), then we have a [websockets server](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/DataServer.ts) that [runs using the same server instance](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/commands/dev.ts#L38) of devserver. So, I didn't see how I can get the instance of the poi server, maybe you can help me with that.

2. We need some [implicit configuration](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/utils/babel-config.ts#L46-L67) for babel, and I saw that in Poi if I have a `babelrc` config file we need to explicit add `poi/babel`. So, what you think that is the best way to accomplish this implicit config?

Will be awesome have your help on this 🙏

**Comment by egoist** [comment]
> 1. So, I didn't see how I can get the instance of the poi server

Maybe you can implement docz as a poi plugin and build a CLI that runs Poi with this plugin added by default:

```js
// docs/cli.js
const Poi = require('poi')

const poi = new Poi(process.argv.concat('--plugin', require.resolve('poi-plugin-docz')))
```

In `poi-plugin-docz` you can use a hook to extend the devServer:

```js
// should've been `createDevServer` instead to match other hooks
// will fix later
api.hook('onCreateDevServer', server => {
  //...
})
```

> 2. We need some implicit configuration for babel

If I remember correctly you can add babel presets and plugins via `babel-loader`'s loader options and they will always be used even if a babel config file is found?

---

An example plugin for reference is [@poi/plugin-vue-static](https://github.com/egoist/poi/tree/master/plugins/vue-static), like `react-static` but as a Poi plugin.

**Comment by pedronauck** [comment]
That's a pretty good idea, I didn't realize that I can create a plugin, with this in mind is easier to define things for docz inside the plugin, since we have the `onCreateWebpackChain`, that btw I copied to docz before I knew Poi 😂 

Thanks, I'll try to figure out how I can implement this using the actual structure, maybe I put this in the v1 that I'm building now 🙏
