### ISSUE TITLE
import a poi built CJS bundle get empty object

### ISSUE THREAD

**Issue by leafiy** [egoist/poi#511]
there is a ui toolkit I've built by `vue-cli3 commonjs` and just move to `poi`

the config are
```javascript
// poi.config.js
entry: ["packages/index.js"],
  output: {
    format: "cjs",
    fileNames: {
      js: "gelatin-ui.[name].js",
      css: "gelatin-ui.[name].css",
      font: "gelatin-ui.[path][name].[ext]",
      image: "gelatin-ui.[path][name].[ext]"
    }
  },

// babel.config.js
presets: [
    [
      "poi/babel",
      {
        jsx: "vue"
      }
    ]
  ],
```

the entry file looks like
```javascript
export default {compA,compB,...}
```

then I import `gelatin-ui.index.js` in another poi project, I got empty object
```javascript
import("../node_modules/gelatin-ui/dist/gelatin-ui-index.js").then(m=>{
 console.log(m) //m.default is an empty object
})


import GelatinUi from "gelatin-ui";
console.log(GelatinUi) // got empty object

const ge = require('gelatin-ui')
console.log(ge)  // got empty object
```

then I change to 'format:umd', the import works but `*.vendors.chunk.js` got 404

Is this a bug or some configurations I missed?

**Comment by egoist** [comment]
I just tried it like this and it's working just fine:

<img width="1051" alt="2018-12-23 3 56 17" src="https://user-images.githubusercontent.com/8784712/50381822-596db300-06cb-11e9-9a86-bf7b0251c5a4.png">

**Comment by leafiy** [comment]
@egoist Thanks for replying. Just figured it out, it caused by my nginx forwarding rule, not a poi issue. Closing this issue.
