### ISSUE TITLE
the alias css files out of src have changed, but the HMR triggered is empty

### ISSUE THREAD

**Issue by leafiy** [egoist/poi#512]
make a alias css file through babel config

```javascript
[
      "module-resolver",
      {
        root: ["./"],
        alias: {
          'anotherCss':'../test/test.css'
        }
      }
    ]
```

then make some changes in test.css, nothing happens but will be an empty hot-update.js/json in the network panle

**Comment by leafiy** [comment]
`css.extract = false` will fix this, but will it be better as default support?

**Comment by egoist** [comment]
Maybe you should use webpack alias instead.
