### ISSUE TITLE
use a HTML file as an entry point?

### ISSUE THREAD

**Issue by huruji** [egoist/poi#513]
Hello, I know **webpack don’t support this** right now，But **will poi support this**？

I just test in the terminal：

```bash 
bogon:src huruji$ poi index.html
./index.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <html>
|
| <head>
```

or do you **have any idea** at this problem? Not limited to using webpack or poi

**Comment by egoist** [comment]
> webpack don’t support this

I'm not sure if webpack 5 or future versions will support this natively, ping @TheLarkInn 😄

> will poi support this?

I've done some experiments on this, currently a webpack plugin should be able to make the dream become reality, my prototype works but not good enough for production use so I didn't release it.

**Comment by egoist** [comment]
https://poi.js.org/guide/html-entry.html

Check out the experimental html entry support in 12.5.0

**Comment by huruji** [comment]
thanks @egoist
