### ISSUE TITLE
Support poi.config.ts

### ISSUE THREAD

**Issue by fjc0k** [egoist/poi#516]
Like this:

```ts
// poi.config.ts

import { Config } from 'poi'

const config: Config = {
  // ....
}

export default config
```

`cli.js`:

```js
require('ts-node').register({ transpileOnly: true })

const config = require('./poi.config.ts').default
```

**Comment by egoist** [comment]
We need to implement https://github.com/egoist/poi/issues/497 first, `.ts` extension is optional since you can just import the types in a regular js file.

**Comment by egoist** [comment]
https://changelog.egoist.sh/poi/whats-new-in-v12.6.1
