### ISSUE TITLE
Spawn a process to run additional command

### ISSUE THREAD

**Issue by egoist** [egoist/poi#519]
Add `poi-spawn` to your npm scripts:

```json
{
  "scripts": {
     "poi-spawn": "electron ./main/index.js"
  }
}
```

Then Poi will run `npm run poi-spawn` once compiling succeeded.

You can override it with `poi --spawn start-api-server` too

**Comment by youngkaneda** [comment]
so, you want this in poi package.json, right?

**Comment by youngkaneda** [comment]
i want to help with, but i don't know what exactly you want, in the way that you described doesn't sounds like something to be added in the project, you can explain a little bit more? my english is not soooo good

**Comment by egoist** [comment]
@youngkaneda it basically does what [npm-run-all](https://github.com/mysticatea/npm-run-all) does, so you can run poi and your back-end server (or electron) in one command.

**Comment by youngkaneda** [comment]
okay, so I add this to my ``package.json`` if i use poi right? So, which part of the ``good first contribution`` I'm not understanding.
