### ISSUE TITLE
Additional devServer options

### ISSUE THREAD

**Issue by borna223** [egoist/poi#531]
Is there a way to specify additional devServer options (ones that are not included in validator)? If I'm not mistaken using chainWebpack/configureWebpack for this doesn't work because devServer options are extracted from config before those methods are called.

**Comment by egoist** [comment]
which option? we can add it to the validator if that makes sense

**Comment by borna223** [comment]
e.g. devServer.headers would be useful for me

**Comment by egoist** [comment]
PR welcome, you can add it here https://github.com/egoist/poi/blob/master/core/poi/lib/utils/validateConfig.js#L80

**Comment by egoist** [comment]
Fixed in 12.4.8
