### ISSUE TITLE
typescript with css modules

### ISSUE THREAD

**Issue by primozs** [egoist/poi#541]
how to integrate this?
typings-for-css-modules-loader
https://github.com/Jimdo/typings-for-css-modules-loader

I could not override original css loader.
Cheers

**Comment by egoist** [comment]
I added new page in docs regarding this topic: https://poi.js.org/guide/customizing-webpack-config.html

Basically you can use following code to change the css-loader of `.module.css`:

```js
config.module.rule('css')
  .oneOf('normal-modules')
  .use('css-loader')
  .loader(require.resolve('typings-for-css-modules-loader'))
```

**Comment by primozs** [comment]
Perfect! Thank You!
Cheers
