### ISSUE TITLE
specify a tsconfig path for poi plugin typescript

### ISSUE THREAD

**Issue by leoparis89** [egoist/poi#542]
Hello

Is it possible to specify explicitly the path of the tsconfig file ?
Can't find how to do that in the [docs](https://poi.js.org/guide/plugin-typescript.html#introduction)

many thanks

**Comment by egoist** [comment]
Supported in @poi/plugin-typescript@12.1.0 https://poi.js.org/guide/plugin-typescript.html#configfile
