### ISSUE TITLE
.babelrc is not taken into account

### ISSUE THREAD

**Issue by Alx-l** [egoist/poi#544]
Hello,

Thanks again for this library 👍

I'm running the latest version of POI at the moment (v12.5.7),
and it seems POI doesn't look up my `.babelrc`config file.

I've made a [repo](https://github.com/Alx-l/poi-babel) so you can have a look when you have some time, maybe I've done something wrong.

There's more details inside the README.

**Comment by egoist** [comment]
The `@poi/plugin-typescript` doesn't use babel to process `.ts` files. Maybe we should add an option to enable babel support in the `ts` rule.

**Comment by Alx-l** [comment]
Thanks for your quick reply.

Yes, it would be cool if you could add this option in a next release 👍

**Comment by egoist** [comment]
Should work in `@poi/plugin-typescript` 12.2.0 with the `babel` option: https://poi.js.org/guide/plugin-typescript.html#babel

**Comment by Alx-l** [comment]
Thanks, but actually inside `index.js` (@plugin-typescript) you mismatched the order ;)

It should be:
```
rule
.use('ts-loader')
...

if (useBabel) {
  rule
  .use('babel-loader')
  ...
}
```

**Comment by egoist** [comment]
that's intended, we run babel after typescript

**Comment by Alx-l** [comment]
Yes, that's my point, currently, you run babel before typescript.

I had to invert the order locally, and then it worked as expected.

**Comment by egoist** [comment]
the current behavior is that babel-loader will be ran after ts-loader, the loader chain is executed in reverse order.

so you want to transform the code with babel first?

**Comment by Alx-l** [comment]
When I look at the index [file](https://github.com/egoist/poi/blob/master/plugins/typescript/index.js#L37),
to me, babel is run before typescript.

And when I switch the order, (move the `if useBabel` block below l.63,
it works as expected (inside the browser, I have the sourcemaps available for my styles defined with `emotion`).

Because from what I understand (after my local update), the ts files will be transpiled to js, and then, those js files will be processed by babel.

**Comment by Alx-l** [comment]
I've made a little video, so that you can have a clearer idea of what I mean.

[streamable link](https://streamable.com/cjvum)
