### ISSUE TITLE
Public assets are not hashed

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#546]
I Have a problem with POI and the project build with all files in the public folder. 

After build, all files have not their name hashed like `myfile.afe345df234dcb17.png`. 

I see nothing about that in the documentation

**Comment by egoist** [comment]
Obviously public assets should be not contain hashes in their filenames.

**Comment by throrin19** [comment]
But How to resolve navigator problem with hashes if public resources are modified ?

**Comment by egoist** [comment]
Then just include it in your webpack build process.
