### ISSUE TITLE
Do you insterest to integrate astroturf?

### ISSUE THREAD

**Issue by bolasblack** [egoist/poi#548]
From [astroturf](https://github.com/4Catalyzer/astroturf) official README:

> astroturf lets you write CSS in your JavaScript files without adding any runtime layer, and with your existing CSS processing pipeline.
>
> * Zero runtime CSS-in-JS. Get many of the same benefits as CSS-in-JS, but without the loss of flexibility in requiring framework-specific CSS processing, and while keeping your CSS fully static with no runtime style parsing.
> * Use your existing tools – Sass, PostCSS, Less – but still write your style definitions in your JavaScript files
> * Whole component in the single file. Write CSS in a template literal, then use it as if it were in a separate file

If you insterest, I think maybe I can create a PR to integrate it.

**Comment by egoist** [comment]
Yeah sure, you can create a `@poi/plugin-astroturf` if we have to modify webpack config, but it seems that we can use it without [webpack](https://github.com/4Catalyzer/astroturf#use-without-webpack)?

**Comment by bolasblack** [comment]
@egoist Yes, but if we want use astroturf to write sass, we need webpack loader to compile the extracted sass code.

**Comment by bolasblack** [comment]
I have tried with the official example project of astroturf, and it does support use without webpack, but it will write some file to disk like `Button__extracted_style.module.scss`

I think most people won't like this solution.
