### ISSUE TITLE
How to use node_modules in config

### ISSUE THREAD

**Issue by Richienb** [egoist/poi#553]
My current poi config looks like this:

```js
module.exports = () =>
    ({
        "entry": ["core/custom.js", "core/custom.scss"],
        "css": {
            "sourceMap": true
        }
    })

```

How do I `@import` scss files from the node_modules folder? Using a tilde only resolves the file specified and not it's children.

**Comment by egoist** [comment]
Just use absolute path.

**Comment by Richienb** [comment]
@egoist what about for the files the imported SCSS imports?
