### ISSUE TITLE
Use workbox and workbox-window for pwa template

### ISSUE THREAD

**Issue by chimon2000** [egoist/poi#559]
Workbox provides a robust set of features over other similar plugins

* Background syncing with fallbacks
* Precaching
* Common Runtime caching strategies are built in
* Request routing

Workbox Window also simplifies the registration process

**Comment by chimon2000** [comment]
Here's a React example that I have built that incorporates workbox's InjectManifest plugin.

https://github.com/chimon2000/offline-react

**Comment by egoist** [comment]
we're already using workbox I think?

**Comment by chimon2000** [comment]
Sorry, yes it does.  For some reason, I thought it was using the offline plugin.  Does the PWA option support `InjectManifest`?  It looks like it only supports generating one?
