### ISSUE TITLE
Using jquery ui and time picker with poi

### ISSUE THREAD

**Issue by cksachdev** [egoist/poi#561]
I am trying to setup poi with jquery ui, but couldn't figure out how to use jquery ui components. I need to load following js files
```
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js
https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.js
https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-sliderAccess.js
```
and 
css files
```
https://code.jquery.com/ui/1.10.0/themes/smoothness/jquery-ui.css
https://cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.css
```
To make the timepicker work. Here is a codepen link where I have tested the functionality.
https://codepen.io/cksachdev/pen/EJgGVR

Any suggestions on how should I go about loading these using poi.

**Comment by egoist** [comment]
Adding them to [`public/index.html`](https://poi.js.org/guide/custom-html-template.html).

**Comment by cksachdev** [comment]
@egoist Is it possible to load them as modules, such that the css is scoped and doesn't interfere with global css. In webpack, it goes something like below:
```
module: {
    loaders: [
      { test: /\.css$/, loader: ['style-loader', 'css-loader'] },
      { test: /\.(jpe?g|png|gif)$/i, loader: 'file-loader' },
    ],
  },
  plugins: [
    // eslint-disable-next-line no-undef
    new webpack.ProvidePlugin({
      $: 'jquery',
      jquery: 'jquery',
      'window.jQuery': 'jquery',
      jQuery: 'jquery',
    }),
  ],
  resolve: {
    alias: {
      'jquery-ui': '../../../node_modules/jquery-ui/ui/widgets',
      'jquery-ui-css': '../../../node_modules/jquery-ui/../../themes/base',
    },
  },
```

**Comment by egoist** [comment]
You can use custom webpack config: https://poi.js.org/guide/customizing-webpack-config.html
