### ISSUE TITLE
[html-entry] Don't strip external resources in development mode

### ISSUE THREAD

**Issue by r0skar** [egoist/poi#570]
At the moment Poi strips all external script resources from the HTML template while in dev mode:

https://github.com/egoist/poi/blob/e7cd5c2010f51f5000e71ea25668eb287fc8d49b/plugins/html-entry/lib/html-entry-loader.js#L42-L53

Is it possible to change this behavior and return the unprocessed `node`? IMO most users will want external resources to be available during development.

For example: I have integrated `netlify-cms` in my app, but cant use it in dev mode, because both of this scripts are removed:

```html
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
```

**Comment by egoist** [comment]
Sure, PR welcome
