### ISSUE TITLE
Babel config file is ignored when using HTML Entrypoint

### ISSUE THREAD

**Issue by r0skar** [egoist/poi#574]
When I run poi using a HTML file as entry point, my custom babel config file is not picked up. You can see that `debug Using external babel config file: /__HDD/__persistent/dev/app/.babelrc.js` is only logged when not using an HTML entrypoint:

**poi src/index.html --prod --debug --no-clear-console**
```
debug Apply plugin: `html-entry`
debug location: /__HDD/__persistent/dev/app/node_modules/@poi/plugin-html-entry/lib/index.js
debug Using default handler
debug Applying custom PostCSS config at /__HDD/__persistent/dev/app/.postcssrc.js
✔ Build completed in 360ms
```

**poi --prod --debug --no-clear-console**
```
debug Apply plugin: `html-entry`
debug location: /__HDD/__persistent/dev/app/node_modules/@poi/plugin-html-entry/lib/index.js
debug Using default handler
debug Applying custom PostCSS config at /__HDD/__persistent/dev/app/.postcssrc.js
debug Using external babel config file: /__HDD/__persistent/dev/app/.babelrc.js
✔ Build completed in 678ms
```

**Comment by egoist** [comment]
Perhaps the log was erased by the spinner (https://github.com/egoist/poi/commit/92146e9ab139e2229114c9ad89a70d3f249ce0a2), try `poi@12.6.10`

**Comment by r0skar** [comment]
I should have mentioned it earlier: to verify it is ignored, I have used invalid syntax in my babel file and the build was still successful as long as a HTML entrypoint was used.

**Comment by egoist** [comment]
@r0skar Can you provide a repo? I tried that too but it's working fine for me.

**Comment by r0skar** [comment]
Here it is: https://github.com/r0skar/poi-babel-html-entrypoint

**Comment by egoist** [comment]
It seems you are only building an html file without javascript involved.

**Comment by r0skar** [comment]
I forgot to include the poi config file that defines `index.js` as `entry`. But you are right: it works fine when it is referenced in the HTML file. I was under the impression that when using an HTML entrypoint, Poi would still be processing the JS from the defined `entry` file and inject it in the template. But it makes more sense that it works just like Parcel does. Sorry for the noise!
