### ISSUE TITLE
Support both HTML and JS entries together

### ISSUE THREAD

**Issue by jenil** [egoist/poi#581]
Hey, 

can we do multiple entry points? Like `poi --prod --clean src/plugin.ts src/ui.html`

I want the `dist/` to contain `plugin.js` and `ui.html`

**Comment by jenil** [comment]
hey @egoist any update on this?

**Comment by egoist** [comment]
No but contribution welcome.

**Comment by egoist** [comment]
Actually I think you should just bundle them separately if you're not using plugin.js from ui.html

**Comment by jenil** [comment]
okay, thanks
