### ISSUE TITLE
How to ignore .babelrc in my project directory?

### ISSUE THREAD

**Issue by akira-cn** [egoist/poi#582]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/poi/issues/582)

Hi,

I want to use poi to build some demos in my project. Thus I don't want to reuse the babel config file in my project.

How can I force poi to use default babel config rather than use the `.babelrc` in my project dir?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/poi/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
You can only update the options for babel-loader manually now to disable that: https://github.com/egoist/poi/blob/5b4bbafc1dc828df69743190d6ff543804d39278/core/poi/lib/plugins/config-babel.js#L67

I think we can add a few options [`babebl.configFile`, `babel.babelrc`](https://poi.js.org/config.html#babel) to toggle this.

**Comment by egoist** [comment]
You can only update the options for babel-loader manually now to disable that: https://github.com/egoist/poi/blob/5b4bbafc1dc828df69743190d6ff543804d39278/core/poi/lib/plugins/config-babel.js#L67

I think we can add a few options [`babebl.configFile`, `babel.babelrc`](https://poi.js.org/config.html#babel) to toggle this.

**Comment by egoist** [comment]
Released in `poi@12.7.0`, https://poi.js.org/config.html#babel-babelrc
