### ISSUE TITLE
CSS modules should export camelCased names by default

### ISSUE THREAD

**Issue by egoist** [egoist/poi#584]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/poi/issues/584)

We also need to update css-loader to v3

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#614 Update css loader and camel case by default](https://issuehunt.io/r/egoist/poi/pull/614)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/poi/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by maykefreitas** [comment]
Hey @egoist.

I just opened a PR upgrading the css-loader to v3 and enabling camelCase by default. Let me know if it helps or needs some change.

**Comment by maykefreitas** [comment]
Oh my. Now I saw that you opened a PR before. 🙄 Sorry. I came from IssueHunt and I don't payed attention.
