### ISSUE TITLE
Keep `poi --serve` URLs and `output.publicUrl` Consistent

### ISSUE THREAD

**Issue by chanjsq** [egoist/poi#586]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/poi/issues/586)

When I set `output.publicUrl` in `poi.config.js`, the URL should have a training path.

So if the output URLs of `poi --serve` contain the `output.PublicUrl`, that can be nice.

Example:

![](https://i.loli.net/2019/07/07/5d21d475ac68926952.png)

![](https://i.loli.net/2019/07/07/5d21d4759f7da62722.png)

If the output URLs like below shoud be better:

```
Local:             http://localhost:4000/admin/
On Your Network:   http://192.168.0.104:4000/admin/
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#587 Append `poi -s` output URLs with `output.publicUrl`](https://issuehunt.io/r/egoist/poi/pull/587)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/poi/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by chanjsq** [comment]
If you give me a hint where to modify, I can make a PR myself.

**Comment by chanjsq** [comment]
I found [the file](https://github.com/egoist/poi/blob/master/core/dev-utils/printServeMessage.js). I will try.

**Comment by chanjsq** [comment]
I have no idea how to get `output.PublicUrl` in `./core/dev-utils/printServeMessage.js`. Can you help?

**Comment by egoist** [comment]
`output.PublicUrl` is only used in production build, in development it's always `/`

**Comment by chanjsq** [comment]
`output.publicUrl` is still used in `development` mode?

I setup an empty demo:

```js
// poi.config.js

module.exports = {
  output: {
    publicUrl: '/admin/',
  },
};
```

```js
// index.js

import Vue from 'vue';
import App from './App.vue';

new Vue({
  el: '#app',
  render: h => h(App),
});
```

```vue
// src/App.vue

<template>
  <div>
    Hello Poi!
  </div>
</template>
```

Result screenshots:

![](https://i.loli.net/2019/07/07/5d21ec4b602c127910.png)

![](https://i.loli.net/2019/07/07/5d21ec4b7616f83062.png)

**Comment by egoist** [comment]
Oh I forgot that 😅

**Comment by chanjsq** [comment]
The current path behavior should ok. It makes development and production consistent.

Then how to make the generated URLs with the path to make development experience better?

**Comment by chanjsq** [comment]
I made a PR to fix this issue and earn the fund. How can I test the modified version of Poi in an demo project myself? Thanks.
