### ISSUE TITLE
Consider using the `main` field in package.json as an option for the entry

### ISSUE THREAD

**Issue by chanjsq** [egoist/poi#610]
Currently Poi is using `pkg.source` as the entry, can it also use `main` field as an option?

Which means `pkg.source || pkg.main || index` as the `entry`.

Thanks.

**Comment by egoist** [comment]
Nope I'm trying to make it consistent with Parcel.

btw I don't think it makes sense to use `main` as the entry, if you're building a library, `main` should point to your library target.

**Comment by chanjsq** [comment]
Got it. Thank you.
