### ISSUE TITLE
Poi build consumes too much memory

### ISSUE THREAD

**Issue by talentlessguy** [egoist/poi#615]
For a simple preact + babel + postcss build it takes more than 100 mb (!!!).

```sh
✔ Build completed in 115ms

Local:             http://localhost:3000
On Your Network:   http://127.0.0.1:3000

> 101 MB memory used
```

Here are my computer specs:

```
OS: Ubuntu 18.04.2 LTS x86_64
CPU: Intel i7-4702MQ (8) @ 3.200GHz
GPU: NVIDIA GeForce GT 740M 
Max memory: 7893MiB
```

Node.js version:

```sh
➜ node -v
v12.7.0
```

**Comment by egoist** [comment]
I think it's pretty common for a webpack + babel + postcss project to consume 100+ memory.

**Comment by talentlessguy** [comment]
@egoist okay then :confused: closing the issue. Thought it was too much memory
