### ISSUE TITLE
poi never responds on localhost:4000

### ISSUE THREAD

**Issue by KsRyY** [egoist/poi#637]
When I run `poi --server` and opened `localhost:4000` in the browser, it loads forever and there is always a blank page, but if I uses the URL of `On your network` (for example, `192.186.100.104:4000`), it loads normally.

Poi version: `12.7.2`
Node version: `12.9.1`

Uses `vue`and `sass`.

**Comment by egoist** [comment]
It's probably related to your system proxy settings, you can provide a repro if you believe it's a bug.
