### ISSUE TITLE
vendor split

### ISSUE THREAD

**Issue by francescoagati** [egoist/poi#648]
hi, 
the vendor options has been removed in version 12. how i can split between vendor and main code with v12? i must use the weback configuration?

**Comment by egoist** [comment]
It automatically split vendor (node_modules) code now.

**Comment by francescoagati** [comment]
in poi 12.7.3 when i run poi [fie.js] i see only two files one index.js and one index.css. i dont know if  i must write some other configuration

**Comment by egoist** [comment]
@francescoagati You need to run Poi in production mode, i.e. using --prod flag

**Comment by francescoagati** [comment]
now works thanks. sorry for the mistake
