### ISSUE TITLE
XSS vulnerability in a dependency of a dependency

### ISSUE THREAD

**Issue by AlexGustafsson** [egoist/poi#655]
Running `npm audit` on a project using the latest published version of Poi yields:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/14974112/71165060-75f5ea00-2250-11ea-9dd0-58e27c55aae7.png">

Poi (Poi core) relies on copy-webpack-plugin 4.6 which in turn relies on a vulnerable version of serialize-javascript (pre 2.1.1). copy-webpack-plugin has since updated to a patched version of serialize-javascript.

I would advise to update the copy-webpack-plugin to the latest version (5.1.1) to get rid of the vulnerability warning when auditing dependencies.

Also, is there a reason for the core package not having a package-lock.json file?

**Comment by egoist** [comment]
Because we're using Yarn and Yarn workspaces and there's a root `yarn.lock`, PR is welcome.

**Comment by AlexGustafsson** [comment]
Thanks for a quick response! See #656.

**Comment by AlexGustafsson** [comment]
Closing as the PR is merged.
