### ISSUE TITLE
Document how to override the target of the babel preset

### ISSUE THREAD

**Issue by AlexGustafsson** [egoist/poi#681]
In [the transforms guide](https://poi.js.org/guide/transforms.html#javascript) there is mentioning of configuration of the `poi/babel` preset by specifying the options `jsx`, `flow` and `typescript`. [The code](https://github.com/egoist/poi/blob/master/core/poi/lib/babel/preset.js#L21,L28), however, supports overriding of the `env` parameter in order to effectively control the target.

For example, I'm using the following `babel.config.js` file in order to use a more up-to-date target over the default IE 9:

```JavaScript
const env = process.env.BABEL_ENV || process.env.NODE_ENV;
const isTest = env === 'test';
const browserlist = require('./package.json').browserslist;

const targets = isTest ? {node: 'current'} : browserlist;

module.exports = {
  presets: [
    ['poi/babel', {
      env: {targets}
    }]
  ]
}
```

**Comment by egoist** [comment]
Update. https://poi.js.org/guide/transforms.html#options-env
