### ISSUE TITLE
[Question] How can I get the document?

### ISSUE THREAD

**Issue by cxh0312** [egoist/poi#745]
[poi document site](https://poi.js.org/) cannot access now @egoist

**Comment by egoist** [comment]
hmm it works for me 🤔

**Comment by cxh0312** [comment]
> hmm it works for me 🤔

I cannot access this website at home or at work. Can I view the document elsewhere?

**Comment by Zhwt** [comment]
Hi, @cxh0312 
The raw documentation file is located in [poi-bundler/website](https://github.com/poi-bundler/website), inside the `docs` folder.
